### ISSUE TITLE
Frequent Youtube-dl updates

### ISSUE THREAD

**Issue by IUCPROD** [meeb/tubesync#104]
Since youtube is frequently breaking youtube-dl in some way, they update it very often, sometimes every couple days. If youtube-dl breaks you have to update and make a new release just for the update every time. This won't be sustainable and will become very annoying for you, so **could you find a way for the user to update youtube-dl by himself?**

**Comment by meeb** [comment]
The short answer, with the "easy to use container" method of distribution, is no. Containers are meant to be immutable once built and even if such a facility (e.g. a "update youtube-dl button") was built into the application it would be very unintuitive such as restarting the container would roll back the embedded `youtube-dl` version to the last version you `docker pull`d and silently lose your update.

Once there's a stable 1.0 release I plan on looking into a semi-automated update procedure for the bundled packages including `youtube-dl` as discussed in a few other issues (like #36). This needs planning and a bunch of new tests written though to make sure, in most common instances, this doesn't automatically break stuff for everyone which would be even more annoying than an occasional channel not working for a day.

In the interim pre-1.0 phase I'll be active and push updates as well, it's not a lot of effort to update.

Also if you're happy to play with the internals a bit and have some experience with Python, you can build your own container by:

1. Clone this repo
2. Install Python3.X with pip and install pipenv (`pip install pipenv`)
3. Activate the pipenv shell with `pipenv shell`
4. Update all libraries with `pipenv update`
5. Build your container image with `docker build ...`

The container you build in step 5. will have up to date `youtube-dl` in it.

**Comment by meeb** [comment]
Closing as no further work will likely be done related to this issue and the instructions are verbose enough to be archived.
