### ISSUE TITLE
The "video" directory should be an option not the default

### ISSUE THREAD

**Issue by subasically** [meeb/tubesync#107]
The `video` directory should be an option in the UI instead of a default/hardcoded parameter.

**Comment by meeb** [comment]
It''s pretty important for linking up to a media server that audio and video media be downloaded to different directory paths to be handled by different libraries which is the core use cause for TubeSync. Is there a technical reason you want this? Or is it just you don't like "video" in your media server directory path as a preference?

**Comment by Extarys** [comment]
I was looking into this too!
My reason would be that I won't download music/audio only file from youtube. Therefore my filepath would be "/NAS/Youtube/Channel/Video.mp4". It could lead to less hierarchy/folder pollution.

**Comment by meeb** [comment]
OK, makes sense. What would you expect to happen if you toggled a theoretical UI option to remove the "audio/video" directory prefixes then added an audio-only source? Just bundle it all into the same directory regardless?

**Comment by Extarys** [comment]
Probably show a warning that this might screw up the library (jellyfin/plex),
- suggest to toggle the option (video/audio folder) with a warning that new downloads will use the new path name
- it's the user's responsibility to move files around if needed (to make your coding easier, at least for now)
OR make the user select a path for audio only download and start the download only once there is a path for audio stuff

**Comment by meeb** [comment]
Generally I've been attempting to keep the number of options to a minimum for TubeSync where possible, there is no global options settings in the application itself beyond the container environment variables. Your examples could work, but could also introduce foot-guns where media potentially gets re-downloaded in bulk or libraries break in unobvious ways.

These issues are easily fixable by knowledgeable users or by more code to auto-rename files of course, however this seems like moderate effort to appease some OCD directory naming. I can see why some users might find the forced directory prefixes a bit annoying but they are, unless someone thinks of a something I've not thought of, only cosmetic annoyances at worst and serve a purpose most of the time.

I'll put this onto the extended wishlist to look into, but to be honest unless someone wants to submit a sensible PR it's probably going to be near the bottom of my current priority list.

**Comment by go2tom42** [comment]
> 
> 
> I was looking into this too!
> My reason would be that I won't download music/audio only file from youtube. Therefore my filepath would be "/NAS/Youtube/Channel/Video.mp4". It could lead to less hierarchy/folder pollution.

If using docker change volume to
```
    volumes:
      - /some/directory/tubesync-downloads:/downloads/video
```

**Comment by meeb** [comment]
@pjrezai the example given was for a docker-compose setup, you would need to modify your volume paths in unraid wherever that option is presented.

**Comment by mckayc** [comment]
OK. I am going crazy here. I have tried 
```
volumes:
      - /some/directory/tubesync-downloads:/downloads/video
```
and it is not working for me. No matter what I do it still adds a "video" folder.

This is my use case:
The way I have Plex setup is that I have a "TV-Kids" folder and I put all the TV shows and Youtube channel videos in that folder. Because Tubesync keeps on adding the "video" folder however I have to manually move files.

I feel like I have had this working before where the video folder didn't show up but now for the life of me whatever I do it ALWAYS comes back up. 

Here is my Docker config:

```
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /srv/dev-disk-by-uuid-......SSDrive...../SSD/tubesync/tubesync-config:/config
      - /srv/dev-disk-by-uuid-.....HDDrive...../tubesync-downloads:/downloads/video
    environment:
      - TZ=America/Denver
      - PUID=998
      - PGID=100    
```

Can anyone see anything I am doing wrong? I have seriously spent the last 3 hours trying to get this to work and every time I think it is working the video folder pops up again. 

Thanks!

**Comment by meeb** [comment]
@mckayc  I can't see anything particularly wrong with your setup, using the volume mounting to `/downloads/video` in the container should hide this in the `/tubesync-downloads` directory outside of the container. Just to really confirm, what does

```bash
docker inspect -f '{{ .Mounts }}' tubesync
```

show?

You could also just change the directory of the Plex library to point to the `videos` folder as well I suppose.

**Comment by mckayc** [comment]
`[{bind  /srv/dev-disk-by-uuid-da442823-0107-40a7-be63-61e6841a5711/SSD/tubesync/tubesync-config /config  rw true rprivate} 
{bind  /srv/dev-disk-by-uuid-c86d7d16-7af6-4a4d-bc27-0aace5fb8074/tubesync-downloads /downloads/video  rw true rprivate} 
{bind  /srv/dev-disk-by-uuid-c86d7d16-7af6-4a4d-bc27-0aace5fb8074/Media /downloads   true rprivate}]`

Yeah, I have considered just adding a new library to Plex. That would ultimately probably be an easier solution. It would be nice to keep things organized with the same structure I have though. I just don't know if this is something I am doing wrong or a limitation with tubesync. Thanks!

**Comment by meeb** [comment]
Ah I think your issue may be the nested mount? I've not tried that with Docker previously but having a mount in the container at `/downloads` and another one at `/downloads/video` may require something weird like specific mount orders or other fine controls `docker-compose.yml` doesn't provide. Do you need both `/tubesync-downloads` AND `/Media` outside of the container BOTH containing TubeSync media? I'd try removing the `/srv/dev-disk-by-uuid-c86d7d16-7af6-4a4d-bc27-0aace5fb8074/Media` volume and restarting it to see if that helps.

**Comment by mckayc** [comment]
Thanks again @meeb I removed all orphaned volumes but` /srv/dev-disk-by-uuid-c86d7d16-7af6-4a4d-bc27-0aace5fb8074/Media /downloads` keeps showing up as a volume when I run `docker inspect -f '{{ .Mounts }}' tubesync`

I am not really sure why I have that volume but I think you are right that it is the issue! I will keep poking around and hopefully can figure out how to get that volume to stop binding.

**Comment by mckayc** [comment]
Hey @meeb Thanks again for pointing me in the right direction. What I ended up doing was just completely removed the tubesync container then re-added it. That seemed to do the trick!

**Comment by meeb** [comment]
This isn't likely to be removed given it's pretty critical for how tubesync operates as an PVR and mixed libraries break a lot of media servers. I'll close this for now as a wont-fix. Anyone who wants to mount libraries differently should use container mount paths to work around this for their setup.
