### ISSUE TITLE
NFO Support

### ISSUE THREAD

**Issue by aaronflorey** [meeb/tubesync#11]
To help media players to index these videos, it might be cool to allow TubeSync to write NFO files for each piece of media

The Kodi standard is probably best: https://kodi.wiki/view/NFO_files/TV_shows

**Comment by meeb** [comment]
Yep should be possible. I'll look into it.

**Comment by meeb** [comment]
This will be bundled into the upcoming 0.6 release.

**Comment by meeb** [comment]
The NFO files tubesync writes are compatible with Kodi. They might need tweaking for Jellyfin.

https://jellyfin.org/docs/general/server/metadata/nfo/ seems to the the reference for what Jellyfin supports, I expect the file that tubesync writes needs tweaking.
