### ISSUE TITLE
Db error

### ISSUE THREAD

**Issue by Code-Slave** [meeb/tubesync#115]
Not sure if mariadb related

  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/connections.py", line 259, in query

    _mysql.connection.query(self, query)

django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x8F\\x86 T...' for column `tubesync`.`background_task`.`verbose_name` at row 1")

**Comment by Code-Slave** [comment]
this is the the value in verbose_name

Downloading metadata for "dfe84980-ea3c-4187-84a2-d5a223f578b9"

**Comment by Code-Slave** [comment]
another one


Rescheduling Downloading media for "2 Easy DIY Projects For Beginners and 1 With a Twist"


Traceback (most recent call last):


  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute


    return self.cursor.execute(sql, params)


  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/mysql/base.py", line 73, in execute


    return self.cursor.execute(query, args)


  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 206, in execute


    res = self._query(query)


  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 319, in _query


    db.query(q)


  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/connections.py", line 259, in query


    _mysql.connection.query(self, query)


MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')

**Comment by Code-Slave** [comment]
on startup:


System check identified some issues:

background_task.CompletedTask: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.


	HINT: Configure the DEFAULT_AUTO_FIELD setting or the BackgroundTasksAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.


background_task.Task: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.


	HINT: Configure the DEFAULT_AUTO_FIELD setting or the BackgroundTasksAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.


Operations to perform:


  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync


Running migrations:


  No migrations to apply.


  Your models in app(s): 'sync' have changes that are not yet reflected in a migration, and so won't be applied.


  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.


sync.MediaServer: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.


	HINT: Configure the DEFAULT_AUTO_FIELD setting or the SyncConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.


[cont-init.d] 10-tubesync: exited 0.

**Comment by meeb** [comment]
Thanks, the warning is just a warning from updated Django, it won't affect TubeSync working.

The actual database errors are all likely related to MySQL and derivatives being annoying with closing database connection when you don't want it to. I'll patch some timeout stuff to see if that helps.

The TubeSync background worker will likely sit running with an open database connection, which MySQL and derivatives will randomly kill, causing the "database server has gone away" error. It's actually a soft error, in that the task would just get retried, and when the task was tried again it would establish a new (working) database connection. However I can probably patch that as well. Cheers for the reports, most helpful.

**Comment by Code-Slave** [comment]
Was waiting for the new db stuff to start pounding on it again as the sqlite subsytem just cant handle my load

**Comment by meeb** [comment]
try `:latest` and see if that's resolved your "database gone away" errors.

**Comment by meeb** [comment]
That `verbose_name` issue might be something else with MySQL and type casting, so re-open this issue if that's not resolved either.

**Comment by Code-Slave** [comment]
Trying now. What I noticed last night is the gone away error cause the tasks to stop once that happens it wont move forward without rebooting the docker

**Comment by Code-Slave** [comment]
also this


Running migrations:


  No migrations to apply.


  Your models in app(s): 'sync' have changes that are not yet reflected in a migration, and so won't be applied.


  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.


[cont-init.d] 10-tubesync: exited 0.
