### ISSUE TITLE
MariaDB; gateway timeouts

### ISSUE THREAD

**Issue by Code-Slave** [meeb/tubesync#116]
Im trying to delete a decent size channel and atasks. i keep gett 502 gateway timeouts.

[2021-05-01 21:19:24 -0400] [435] [CRITICAL] WORKER TIMEOUT (pid:9430)

thats the error from docker log

**Comment by meeb** [comment]
This is due to having to process a bunch of nested checks for each video on a channel when you delete it, which is slower the larger the channel. It's a known issue being tracked in similar issues like #93. It'll generally get fixed when some other issues get updated as well.
