### ISSUE TITLE
Problem syncing some channels. "No metadata was returned by youtube-dl"

### ISSUE THREAD

**Issue by cv1000b** [meeb/tubesync#118]
Hi,

Thanks for a great tool. Love the UI and everything about it! :)

I'm using the Docker on an Unraid server, and having some trouble.
I have tested to add 6 channels, but only 3 are working. On the 3 that are not working I get the following message in the logs:

-------------------------------------------------------
2021-05-06 14:48:34,767 [tubesync/DEBUG] [youtube:tab] UCx4MHIcTdwdcmJ5accSDlPA: Downloading webpage
2021-05-06 14:48:34,941 [tubesync/ERROR] ERROR: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Rescheduling Index media from source "grainydays"
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
func(*args, **kwargs)
File "/app/sync/tasks.py", line 161, in index_source_task
videos = source.index_media()
File "/app/sync/models.py", line 465, in index_media
response = indexer(self.index_url)
File "/app/sync/youtube.py", line 50, in get_media_info
raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '

tube.YouTubeError: Failed to extract_info for "https://www.youtube.com/channel/UCx4MHIcTdwdcmJ5accSDlPA/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.

Rescheduling task Index media from source "grainydays" for 0:04:21 later at 2021-05-06 12:52:55.974470+00:00
-------------------------------------------------------

Any idea on how to fix this? Channels added in the exact same way as the other who are working just fine.

**Comment by cv1000b** [comment]
Sorry, seems to work not with the :latest tag.

**Comment by meeb** [comment]
Thanks for the kind words! Just to comment on this even though you've closed it, are you saying using `:latest` fixed it? Or using the versioned tag fixed it? Errors like this are down to one of three things:

1. `youtube-dl` being out of date (update `:latest` image)
2. The channel being added incorrectly, there are some "gotchas" with the channel naming conventions, however https://www.youtube.com/channel/UCx4MHIcTdwdcmJ5accSDlPA/videos does work fine for me in your example
3. YouTube have throttled your IP, increase the indexing frequency to as long a duration as possible and stop TubeSync for a couple of hours then start it again

If the URL in the logs works then it's not 2), updating the image is easy to solve 1), if both of those are done then it's likely throttling so do 3)

**Comment by cv1000b** [comment]
Sorry, I saw now that i wrote "seems to work not" instead of "seems to work now".
It works great with the :latest tag! 👍

**Comment by meeb** [comment]
Ah nice, that would just be `youtube-dl` needing to be updated then, glad you got it resolved.
