### ISSUE TITLE
Separate {yyyy_mm_dd}

### ISSUE THREAD

**Issue by aaronflorey** [meeb/tubesync#12]
Can we get separation of the date? so instead of {yyyy_mm_dd} {yyyy} {mm} {dd}

**Comment by meeb** [comment]
Yep, there is {yyyy} already but if you want {mm} and {dd} that's easy enough to add.

**Comment by meeb** [comment]
This will be part of the future 0.6 release once a few other commits are bundled.

**Comment by aaronflorey** [comment]
Thank you <3
