### ISSUE TITLE
User channels

### ISSUE THREAD

**Issue by Code-Slave** [meeb/tubesync#127]
ex: https://www.youtube.com/user/crashcourse/videos

i cant figure how to add. All options reject it

**Comment by meeb** [comment]
Ah, another vanity alias format thing. I'll add an issue to add support for it - you are correct that won't work right now. Internally, that channel is actually catchily called "UCX6b17PVsYBQ0ip5gyeme-Q" so you should be able to add that channel with the following URL:

https://www.youtube.com/channel/UCX6b17PVsYBQ0ip5gyeme-Q

**Comment by Code-Slave** [comment]
Great Thanks
