### ISSUE TITLE
Is there a way to download videos that are flagged as "members-only"?

### ISSUE THREAD

**Issue by Jay2645** [meeb/tubesync#128]
For the purposes of this question, let's assume that I have "joined" a channel that has a playlist of content that has been flagged as "members-only." [Here's an example playlist.](https://www.youtube.com/watch?v=wZcyv12V5ME&list=PLuKg-WhduhkkbSIBhz0cPZ3uR3Vk6g10s)

It looks like youtube-dl can let you download this sort of stuff [by letting the user set an authentication method](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#authentication-options), but I don't see any way to set those within Tubesync itself. It's possible I'm just blind, however.

Note that to get youtube-dl to work with these sorts of videos, you need the Youtube username, password, and cookies (which can be saved to a cookie file). I'd imagine this sort of stuff could be included in the config directory or passed over the Docker command line? But I don't see any options for it.

**Comment by meeb** [comment]
It's a planned feature to allow the use of a custom `cookies.txt` which I assume would also solve this requirement. This should also work for login requirements with certain media like your example playlist. I'll create an issue for this separately.

**Comment by Jay2645** [comment]
Perfect! Works for me! Thank you so much. :)

**Comment by meeb** [comment]
I'll close this for now as it's basically made redundant by #129
