### ISSUE TITLE
Imported media dead links (500 error)

### ISSUE THREAD

**Issue by ExodusC** [meeb/tubesync#138]
I've followed the [docs for importing existing media](https://github.com/meeb/tubesync/blob/main/docs/import-existing-media.md), and the import-existing-media Django command functions fine, with TubeSync recognizing the imported media. One area that TubeSync doesn't seem to gracefully handle is the info page for media if it's been imported.

Upon clicking the thumbnail link for a piece of imported media on the Media page in TubeSync, it throws a 500 internal server error. This is for media that previously had an info page that was indexed, but wasn't downloaded due to failed codec matching.

I think having bare minimum a static page displaying a message that this media was imported externally would be helpful and more graceful than the current behavior. Being able to view the indexed information like the description would be ideal.

I'm unsure if this is a bug or an oversight. If this is a configuration specific bug, I can provide more information. The only real config changes in my environment from stock are using is an external database server (MariaDB) and TUBESYNC_WORKERS set to 1.

**Comment by meeb** [comment]
That is most certainly a bug! It's probably something I added after writing the `import-existing-media` command where the media detail view assumes it has some metadata from YouTube that doesn't exist or something. There should be a Python error trace in your container logs, can you trigger the 500 error again and paste the error log if one exists please?

**Comment by ExodusC** [comment]
Is there a specific output verbosity I need to be on? I've seen other python errors for other issues documented here, but in this instance when clicking the link and getting hit with the 500 error, the only output I'm seeing in the container stdout is:

"GET /favicon.ico HTTP/1.1" 499 0 "(Page's URL here)"

I also could simply be not looking in the right place.

**Comment by meeb** [comment]
No pretty much all Python errors should be being written to the container output log. You can also set the ENV var `TUBESYNC_DEBUG` to `True` and restart the container, that should show the full Python error in the browser when a 500 error is triggered as well.

**Comment by ExodusC** [comment]
Here's the info from the top, if you end up needing the full trace or anything let me know and I can provide a copy:

<html><body>
<h1>AttributeError
       at /media/mediaurlhere</h1>
  <pre class="exception_value">'NoneType' object has no attribute 'lower'</pre>
  

Request Method: | GET
-- | --
http://localhost/media/mediaurlhere
3.2.6
AttributeError
'NoneType' object has no attribute 'lower'
/app/sync/models.py, line 823, in get_display_format
/usr/bin/python3
3.7.3
['/usr/local/bin',  '/app',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/dist-packages',  '/usr/lib/python3/dist-packages']
Fri, 06 Aug 2021 12:24:22 -0400


</body>
</html>

**Comment by meeb** [comment]
Cheers, should be an easy fix when I get a moment.

**Comment by meeb** [comment]
Pull `:latest` down and give that a go once it's finished building.

**Comment by ExodusC** [comment]
Confirming that the issue is resolved after I pulled the latest image. Thanks for all the hard work!

**Comment by meeb** [comment]
No problem, also just noticed you're a sponsor too so thanks back at you :)
