### ISSUE TITLE
Error: Failed to extract_info for ...

### ISSUE THREAD

**Issue by Doublemyst** [meeb/tubesync#143]
Hello, I am receiving following error for any channel I am trying to download:
Error: "Failed to extract_info for "https://www.youtube.com/c/AsKitchen/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff."

I have "freshly" installed the docker on Unraid.

As for the information showed in Tubesync, here is what it uses:
 TubeSync version 0.9.1 with youtube-dl version 2021.03.03 and FFmpeg version 4.3.1-static.

**Comment by meeb** [comment]
Please install the `:latest` image and see if this fixes it for you.

**Comment by Doublemyst** [comment]
Yes, it solved the problem, thanks!

**Comment by meeb** [comment]
No problem. I really need to switch release formats from semver to probably just dates, but in the mean time `:latest` should usually work.
