### ISSUE TITLE
Possibly switch to youtube-dlp

### ISSUE THREAD

**Issue by Code-Slave** [meeb/tubesync#145]
https://github.com/yt-dlp/yt-dlp

since ytdl is really inactive and not merging pull requests etc, it might be time to switch to an active fork. So far dlp seems the most active. Many apps are starting to support it

**Comment by nifoc** [comment]
Any updates on this? I have a bunch of smaller issues with `youtube-dl`, so having `youtube-dlp` support would be really nice

If you haven't started working on it yet, would a PR be welcome?

**Comment by meeb** [comment]
It's a near drop-in replacement and it's already bundled into the last few TubeSync builds. I was attempting to get fancier stuff like sponsorblock integrated, but that seems to be more of a pain than I first thought. If people have a legitimate use for yt-dlp now I'll push the change in the next release.

Out of curiosity what issues are you experiencing with it currently using youtube-dl?

**Comment by nifoc** [comment]
That's great to hear!

> Out of curiosity what issues are you experiencing with it currently using youtube-dl?

Mainly:

* Download throttling can get really bad from time to time. `-dlp` seems to handle it much better.
* Age-restricted videos (I know that `-dlp` just tries to work around the real issue)

**Comment by meeb** [comment]
Yep, fair enough. I'll push it when I next get a moment to work on it.

**Comment by HStep20** [comment]
I think the big use would be sponsorblock, however does youtube-dlp have a way to pull the playlist index of an item? That (and the folder watch) are the last two things I'd personally use to make it feature-complete for production :)

Thanks!

**Comment by meeb** [comment]
The issue with sponsorblock is there's no clear way currently I can see to call it programmatically over the `yt-dlp` API. I'd love to implement it, it doesn't seem trivial at the moment. `yt-dlp` does have `playlist_index`, but only in the same sense that `youtube-dl` has it. I'll check it again but I really don't see how technically `yt-dlp` would be any different to `youtube-dl` in terms of populating `playlist_index`, the data simply isn't returned by YouTube for single video metadata requests.

**Comment by meeb** [comment]
The switch to `yt-dlp` is complete and seems to be working OK, it'll be in `:latest` shortly. This doesn't implement `playlist_index` or sponsorblock (yet), both are still being worked on to see if they are possible.
