### ISSUE TITLE
Possible? Proper NFO file for Plex

### ISSUE THREAD

**Issue by MatthK** [meeb/tubesync#146]
While tubesync works perfectly fine and does an excellent job downloading YT videos, I end up with a big library of videos in Plex that is difficult to search for. For example I just have this as a title `2021-08-13_mentourpilotaviation_easyjet-a320-tells-united-boe...` without any other information associated.

I understand that tubesync is informing Plex about new videos. So I was wondering if it was possible to create also a NFO file that provides Plex with some more information, like a proper Title, the date of release, duration, etc. I'm not sure how complicated that would be, but I believe that would improve the functionality very much.

**Comment by meeb** [comment]
TubeSync can write NFO files already, just tick the "write NFO" tickbox on your source. Plex doesn't read them without a plug-in though so they're not amazingly useful at the moment. The future plan is to embed metadata directly into the MKV container itself which should help this issue, that's pending using `yt-dlp` though so is on the future roadmap for now.

**Comment by MatthK** [comment]
I just noticed that option, and I did have it checked for at least one channel. But somehow it doesn't seem to make a difference, so it seems, as you say, Plex is not reading them. What a shame.

**Comment by meeb** [comment]
Yes it is most irritating that Plex now neither reads NFO files nor allows plugins to be easily installed.
