### ISSUE TITLE
Thumbnail issues using Pillow: `UnidentifiedImageError`

### ISSUE THREAD

**Issue by scottwallacesh** [meeb/tubesync#150]
```plain
Rescheduling task Downloading thumbnail for "Why Humans Are Supposed to Sleep in Two 4-Hour Phases" for 0:00:06 later at 2021-09-04 07:52:53.868028+00:00
Rescheduling Downloading thumbnail for "The Tiny Boat With Its Own Postal Code"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 281, in download_media_thumbnail
    i = get_remote_image(url)
  File "/app/sync/utils.py", line 66, in get_remote_image
    return Image.open(r.raw)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f1c289e77d8>
```

**Comment by meeb** [comment]
Have you pulled the `:latest` image from about 30 minutes ago?

**Comment by scottwallacesh** [comment]
I have the image containing [your latest commit](https://github.com/meeb/tubesync/commit/7f4b9aff141530841e35b746c8b3541b2f9b90c7), with `libjpeg62-turbo` included, yes.

**Comment by meeb** [comment]
Thanks, I'll take a peak at what image support is now missing. Is this the video the above log is failing on?

https://www.youtube.com/watch?v=DKBXFfEPJyg

**Comment by scottwallacesh** [comment]
I've got 768 of those errors.  That's one example, yes.

**Comment by meeb** [comment]
Ah, that channel is using webp thumbnails and none of my test ones are. I'll add in webp support.

**Comment by meeb** [comment]
Wait for the container to build then give `:latest` a go see if that fixes it for you.

**Comment by scottwallacesh** [comment]
Yep. You've nailed it.  Good work.
