### ISSUE TITLE
Fix for Plex Thumbnails on Samsung TV

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [meeb/tubesync#154]
On Samsung TVs (and possibly other TV platforms), using an Other Videos library type, the Plex App doesn't actually display thumbnails on the list view. The thumbnail is only seen when you actually click on a specific video, and at that point it's using the thumbnail as the poster image.

Instead, it looks for the Background image. Easy enough fix, I have a script that creates a symlink to the thumbnail and adds `-fanart` at the end of the name. And now thumbnails are working on the TV and I don't have duplicated data everywhere.

Great - except this doesn't completely solve the problem. The background image doesn't actually get fixed until I manually tell plex to refresh all metadata on that library. In order for it to work from the start, that symlink would need to be created when the thumbnail gets created.

So it would be great if there was an option to create this fanart symlink in tubesync.

Edit:
I was thinking I could circumvent this issue entirely by using a TV Shows library, turning off seasons, and changing my agent to be Personal Media Shows. I'll have to play around with that to see if it'll work for my situation, because I know that option had it's own set of problems

Edit2:
I tried the TV Shows library, and it's way worse. Plex doesn't understand how to read the episode names. So Other Videos is the way to go

**Comment by meeb** [comment]
Thanks for the feedback. Yes "other videos" is the only way I've found that works as well. I didn't actually know about the `-fanart` magic extension so I'll test that and look at adding it as an option if it works. Cheers!

**Comment by Tntdruid** [comment]
Why not use the same as other plex apps?  filename.jpg for Thumbnails

**Comment by ngInit** [comment]
Well this isn't really an issue for me anymore, because I created that script to automatically symlink the thumbnails.

You don't use filename.jpg because Plex didn't program the Samsung TV app correctly and it looks at filename-fanart.jpg for the thumbnails.

**Comment by Tntdruid** [comment]
Can you share the script?

**Comment by ngInit** [comment]
```
#!/bin/sh
symlinkSuccess(){
  echo "$(basename $1) linked"
}
symlink(){
  srcPath=$1
  shift
  for destPath in "$@"; do
    ln -rsfn "$srcPath" "$destPath" 2> /dev/null && symlinkSuccess $srcPath
    shift
  done
}
symlinkThumbnailFix(){
  find $1 -type f -regex ".*\.\(jpg\|png\)" | while read filename; do
    base=${filename%.*}
    ext=${filename##*.}
    symlink "$filename" "$base-fanart.$ext"
  done
}
```
And then call it like this, I just have mine running every few hours with cron

```
symlinkThumbnailFix "filepath/YouTube/video"
```

**Comment by meeb** [comment]
I believe this was fix in the Plex client for smart TVs so I'll close this for now. If anyone tests this and thumbnails aren't working for them on their Plex client for their smart TV please create a new issue.
