### ISSUE TITLE
Tasks failing: Error 1406 'Data too long for column'

### ISSUE THREAD

**Issue by ExodusC** [meeb/tubesync#158]
I'm running `tubesync:latest` (minus the commits from 24 hours ago for postgres), and I've encountered an issue where both download tasks are failing, and `manage.py import-existing-media` fail with the same error:

`Error: "(1406, "Data too long for column 'media_file' at row 1")" `

The above is from the Tasks section in the GUI; Attempting to import provides the full error trace which I can provide if needed.

**Comment by meeb** [comment]
`media_file` stores the actual full file path on disk. Are you somehow downloading videos to an extremely long directory path? Or have you created an extremely long `media_format`? What's the length of the full file path for a video you're trying to import with `import-existing-media` when it fails? The default in Django for a `FileField` is 200 characters.

**Comment by ROMzombie** [comment]
I'm hitting this too using MariaDB
![image](https://user-images.githubusercontent.com/2767055/134621433-8293b9ff-1c5b-4b0b-b4b2-aebcb00cfaca.png)
I have the filename style defaulted, which should make the file location (from the docker container mount) 166 characters:
```/downloads/Super Easy, Barely An Inconvenience [PL--PgETgAz5FGoatB9KQzbnpv0bgZqU2l]/2018-11-03_the-nightmare-before-christmas-pitch-meeting_-h6O6zZt6OM_720p-vp9-opus```

**Comment by meeb** [comment]
Wait for a new image to build and give `:latest` a go. I've increased the maximum allowed file path length for `media_file` to 255 characters. This is about the maximum you can sensibly set it to without encountering database issues. If this doesn't resolve it for you re-open this ticket and I'll see what else is going on.
