### ISSUE TITLE
No Downloads in almost a week

### ISSUE THREAD

**Issue by jaded33** [meeb/tubesync#159]
Was working okay last week but just stopped downloading anything new.  Had set 4 worker threads.  Tasks shows 4 active tasks that have been frozen there for 6 days 13 hours.  45 errors that failed 1 time.  I have restarted the container a few times.  The docker has updated 2-3 times during this period of time using "latest" tag but none of the updates have gotten things going again.  Using Unraid server to run the docker. Attached is my docker log.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-tubesync: executing...
Operations to perform:
Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
No migrations to apply.
Your models in app(s): 'sync' have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
[cont-init.d] 10-tubesync: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-09-24 16:44:15 -0400] [444] [INFO] Starting gunicorn 20.1.0
[2021-09-24 16:44:15 -0400] [444] [INFO] Listening at: http://127.0.0.1:8080 (444)
[2021-09-24 16:44:15 -0400] [444] [INFO] Using worker: sync
[2021-09-24 16:44:15 -0400] [471] [INFO] Booting worker with pid: 471
[2021-09-24 16:44:15 -0400] [472] [INFO] Booting worker with pid: 472
[2021-09-24 16:44:15 -0400] [473] [INFO] Booting worker with pid: 473
192.168.1.70 - bb8 [24/Sep/2021:16:44:37 -0400] "GET / HTTP/1.1" 200 3599 "http://192.168.1.50:4848/tasks" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0"
192.168.1.70 - bb8 [24/Sep/2021:16:44:37 -0400] "GET /static/styles/tubesync.css HTTP/1.1" 200 34505 "http://192.168.1.50:4848/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0"
192.168.1.70 - bb8 [24/Sep/2021:16:44:37 -0400] "GET /static/images/favicon.ico HTTP/1.1" 304 0 "http://192.168.1.50:4848/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0"
192.168.1.70 - bb8 [24/Sep/2021:16:44:48 -0400] "GET /tasks HTTP/1.1" 200 248161 "http://192.168.1.50:4848/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0"
192.168.1.70 - bb8 [24/Sep/2021:16:44:48 -0400] "GET /static/styles/tubesync.css HTTP/1.1" 200 34505 "http://192.168.1.50:4848/tasks" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0"
192.168.1.70 - bb8 [24/Sep/2021:16:44:48 -0400] "GET /static/images/favicon.ico HTTP/1.1" 304 0 "http://192.168.1.50:4848/tasks" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0"

**Comment by meeb** [comment]
Can you try the "reset tasks" button at the end of the tasks page please and see if that fixes it?

**Comment by Code-Slave** [comment]
every once in a while ill get a locked task that i have to delete from the db

**Comment by meeb** [comment]
@Code-Slave you'll be happy to know the work to move to a more sensible task system is almost complete. The effort is making it a smooth automatic switch-over between systems so I don't break anyone's installations. In retrospect I wouldn't have used this task system if I was doing it again given the annoyances it's caused.

**Comment by jaded33** [comment]
Okay I just reset and will report back if downloads start again.  I never saw that option because my task queue was so long I never got to the bottom of the page haha.

**Comment by jaded33** [comment]
Yes working again!  Tasks are re-indexing and new downloads flooding in.  Thank you so much!

**Comment by Code-Slave** [comment]
@meeb  awesome to hear. need testing just hollar
