### ISSUE TITLE
Logon Screen

### ISSUE THREAD

**Issue by EZarnosky** [meeb/tubesync#17]
Not sure if I missed it, but TubeSync seems to be missing an authentication option. Any chance of getting a logon option for security?

**Comment by meeb** [comment]
As the FAQ in the README says, no, there is no authentication options at the moment. It's not meant to be public. It's not too much effort to add, but probably not something I want to spend time on myself right now. In the interim you can just put it behind a reverse proxy (nginx, caddy etc.) and implement HTTP authentication that way if you want to put it somewhere where authentication is required.

**Comment by EZarnosky** [comment]
ok, guess it will. work on securing is behind traefik then, thanks

**Comment by meeb** [comment]
I'll make a note of this for a future roadmap and close it for now.
