### ISSUE TITLE
Lots of Duplicate Scheduled Tasks - Need a Way to Delete

### ISSUE THREAD

**Issue by ngInit** [meeb/tubesync#170]
I have lots of duplicated scheduled tasks currently with no way of deleting them. The duplicated tasks keep rescheduling themselves the next day, so it isn't something that solves itself with time.

The biggest example of this in my setup would be a channel that's set for once every 24 hrs, currently has 4 tasks scheduled in a 24 hour period.

And while I'm here talking about task scheduling, I might as well mention another issue I've been having - there needs to be a way to set a start time for the scheduler in your sources. Currently it just assumes whatever time you save changes to the source should be used for the start time.

This causes problems in lots of areas, but the main one for me being a channel that uploads content 3-4 hours earlier than I wake up. The video is never downloaded in time because I don't want to wake up 2 hours earlier than necessary to tell tubesync to schedule the task while I'm normally asleep - especially knowing that exact time I scheduled it for will just be thrown out the next time the task scheduler runs into problems and needs to be reset.

**Comment by ngInit** [comment]
Well last time I reset my tasks it didn't reschedule all the sources properly. So I've had to go in and edit the frequency to reschedule them again, which might be related to why I'm getting duplicates for some a couple sources.

**Comment by ngInit** [comment]
> The scheduled tasks system is already being rebuilt, it's just a big job.
> 
> As for your duplicate tasks unless something has gone very weird multiple tasks for the same task shouldn't be possible. Can you post a screenshot?
> 
> As for clearing the tasks, there's a "reset tasks" button at the bottom of the tasks page which will fix that. If that times out because you have a lot of sources or similar reason you can use:
> 
> ```shell
> $ docker exec -ti tubesync python3 /app/manage.py reset-tasks
> ```
> 
> On the command line as well.

![image](https://user-images.githubusercontent.com/38122413/136494349-ae47d49a-19b6-429a-990b-70f668643f41.png)

**Comment by ngInit** [comment]
> Interesting, I'm not entirely sure how that might occur that should probably violate some database constraints as well.
> 
> The task-reset command quite literally just deletes all the current tasks and recreates them from scratch. It doesn't change the scheduling of the tasks in any way. I suppose you could just run task-reset when you want your tasks to run for now as a hack so they're scheduled at the time you want.

Yeah, I just tried a task reset again and it only scheduled 1 out of 23 sources. So if I want them rescheduled I need to manually go in and edit the frequency of each one

**Comment by meeb** [comment]
That doesn't make much logical sense unless something else is going on here. The `reset-tasks` command does exactly the same thing as re-saving each source so the effect is identical. Given you're also getting weird things like duplicate tasks which should be impossible I'd say something is weird with your installation in general. Anything unusual with your setup? `config` share on NFS or SMB etc?

**Comment by ngInit** [comment]
Everything is local on the computer and mounted in through docker the same way the rest of my containers are setup.

**Comment by Code-Slave** [comment]
I had same type of issues with sqlite for large amount of channels. moved to postgres and been working pretty well since
