### ISSUE TITLE
Allow save of default media format

### ISSUE THREAD

**Issue by psyciknz** [meeb/tubesync#173]
I've found one that seems to work ok for plex (with zeroq youtube agent as per #45 ), so have to add it each time, it'd be handy if I could set it somehow as a default (maybe environment var settible via docker?

```
{source_full} - s{yyyy}e{mm}{dd} - {title_full} [{key}].{ext}
```

**Comment by meeb** [comment]
Yep sounds fine. I'll bundle this as a dupe of #172 for now though as that covers this. Cheers for the issue.
