### ISSUE TITLE
Can't add Plex server

### ISSUE THREAD

**Issue by UndarkAido** [meeb/tubesync#177]
> Your Plex Media Server returned unexpected data, the XML it returned could not be parsed and the error was "'xml.etree.ElementTree.Element' object has no attribute 'getiterator'"

I can't figure out what's causing this? I have `192.168.1.34` inserted for the IP and `32400` for the port. When I navigate to that in the browser it shows me some XML. It gives a different error if I mess up the token, so that's valid. What's up?

**Comment by meeb** [comment]
Have you tried the HTTPS checkbox?
