### ISSUE TITLE
Subfolder support

### ISSUE THREAD

**Issue by EZarnosky** [meeb/tubesync#18]
Is there planned support for subfolders?

ex: http://<domain>/tubesync/

**Comment by meeb** [comment]
Sorry I don't get the example here, what do you mean?

**Comment by EZarnosky** [comment]
Opps it clipped it out...

http: //domainname/tubesync/

**Comment by meeb** [comment]
Yeah that's possible. You would do something like pass `-e SUBDIR=/whatever` as an env var then have to put it behind a nginx/caddy that forwards example.com/whatever internally to the TubeSync container. I'll add it to the list.

**Comment by meeb** [comment]
This will be bundled into the 0.6 release. You can use `-e DJANGO_FORCE_SCRIPT_NAME=/whatever` to set Django's FORCE_SCRIPT_NAME which probably does enough to do what you need.

https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-FORCE_SCRIPT_NAME

That's about as much support as you get by default from Django so probably about the extent I'll add. It should modify the static paths and URLs though to support subdirs.
