### ISSUE TITLE
Picking av01 over vp9

### ISSUE THREAD

**Issue by Horuyuki** [meeb/tubesync#184]
I have added a source with this media selection available for the video:
```
 ID: 136 , 720p (1280x720), fps:30, video:avc1.4d401f @945.577k
ID: 22 , 720p (1280x720), fps:30, video:avc1.64001F @2089.314k , audio:mp4a.40.2 @0.0k / 44100Hz
ID: 247 , 720p (1280x720), fps:30, video:vp9 @1161.221k
ID: 398 , 720p60 (1280x720), fps:60, video:av01.0.08M.08 @1352.389k
ID: 298 , 720p60 (1280x720), fps:60, video:avc1.4d4020 @1818.401k
ID: 302 , 720p60 (1280x720), fps:60, video:vp9 @1814.878k
ID: 399 , 1080p60 (1920x1080), fps:60, video:av01.0.09M.08 @2649.579k
ID: 299 , 1080p60 (1920x1080), fps:60, video:avc1.64002a @4028.966k
ID: 303 , 1080p60 (1920x1080), fps:60, video:vp9 @3832.979k
ID: 400 , 1440p60 (2560x1440), fps:60, video:av01.0.12M.08 @12516.992k
ID: 308 , 1440p60 (2560x1440), fps:60, video:vp9 @12503.388k
ID: 401 , 2160p60 (3840x2160), fps:60, video:av01.0.13M.08 @26815.767k
ID: 315 , 2160p60 (3840x2160), fps:60, video:vp9 @26318.577k (matched) 
```
In the source menu I set things to prefer `AVC1 (H.264)`, but still it matched the vp9 when `401` is AVC1/H264

What can I do to always force/prefer H264?

EDIT1:
I chose the target to be 1080P Full HD and it defaulted to avc1, `299`
So that means avc1 is different from av01, it is my lack of knowledge.
In this case, is there a way for me to pick av01 still or is that not possible? Since my ipad can only sw decode VP9. 
I understand there is no need to go for anything higher for this application, but I just want to see how the ipad performs with 4K av01. Unless it is also another one of my understandings here with av01 codec, like it is not meant to be downloaded or whatever.

Many thanks for looking at my issue!

**Comment by meeb** [comment]
Yep that looks like a new codec I'll need to add, thanks for the issue.

**Comment by Horuyuki** [comment]
> Yep that looks like a new codec I'll need to add, thanks for the issue.

Oh great thank you so much! Look forward to the docker pull.

**Comment by badrabbit** [comment]
I'm still getting VP9 all the time instead of preferred AVC1! 

Why is that? The correct AVC1 file is there:
`ID: 137 , 1080p (1920x1080), fps:25, video:avc1.640028 @4015.535k
ID: 248 , 1080p (1920x1080), fps:25, video:vp9 @1940.653k (matched)`

**Comment by meeb** [comment]
What YouTube URL / video is this not working for?

**Comment by badrabbit** [comment]
Every video i've tried so far. They all have a 1080p AVC1 stream available but VP9 is always picked instead.

OK - so if i set the SOURCE RESOLUTION to 1080p instead of something higher, the AVC1 stream is selected. I've set to 2160p before because i thought, that's the right setting to get the 4K video if available.

So changing the SOURCE RESOLUTION to 1080p fixes this. But why is VP9 always chosen when wanting a higher resolution?

**Comment by meeb** [comment]
Order of preference is a choice really, there are 4 factors to consider when selecting a video stream. Resolution, codec, HDR, FPS. Selecting the "best" video is a non-trivial task when there is no match. Currently, TubeSync prioritises resolution over codec when an exact match is not available. While this is not ideal, the alternative is likely worse (for example, downloading 1080p when you selected 2160p just to match the codec when a 2160p stream is available). Do your videos have an AVC1 option at the higher resolution? If not, and there's only a 1080p AVC1 videos stream, that would explain what your experience.

**Comment by badrabbit** [comment]
> Do your videos have an AVC1 option at the higher resolution? If not, and there's only a 1080p AVC1 videos stream, that would explain what your experience.

The playlist i've used to test things does not contain any higher resolution videos. Got it. Thanks for the quick reply!

**Comment by badrabbit** [comment]
Another thing i've noticed now - the downloaded container is still MKV instead of MP4. That's intended i guess? Could we have an option to select MP4 instead?

**Comment by meeb** [comment]
Yes it's intentional. MKV is the only container format available that supports all the possible combinations of video and audio codecs (and is widely play-able). MP4 is possible, but it would have to lock out some audio and video formats from being select-able and generally be complicated to have an interface for that was logical to use. It was easier to just default to MKV that supports everything.
