### ISSUE TITLE
502 Bad Gateway when trying to delete or update a source

### ISSUE THREAD

**Issue by csjoh** [meeb/tubesync#196]
I'm getting 502 Bad Gateway when trying to delete a specific source with only 153 items in it. When deleting much larger sources with nearly a thousand items, the deletion went through smoothly and quickly with no error messages. However, when deleting this specific source it consistently times out.

Log snippets:

```
(...)
2022-01-03 22:17:13,711 [tubesync/INFO] Deleting tasks for media: Why Beautiful Things Make us Happy – Beauty Explained
2022-01-03 22:17:13,831 [tubesync/INFO] Deleting tasks for media: The Beginning of Everything -- The Big Bang
[2022-01-03 22:17:19 +0100] [456] [CRITICAL] WORKER TIMEOUT (pid:1039)
2022/01/03 22:17:20 [error] 478#478: *91 upstream prematurely closed connection while reading response header from upstream, client: 192.168.2.2, server: _, request: "POST /source-delete/ac99d3d8-8d27-4576-a08d-1afa467e5e95 HTTP/1.1", upstream: "http://127.0.0.1:8080/source-delete/ac99d3d8-8d27-4576-a08d-1afa467e5e95", host: "192.168.2.8:48484", referrer: "http://192.168.2.8:48484/source-delete/ac99d3d8-8d27-4576-a08d-1afa467e5e95"
192.168.2.2 - user [03/Jan/2022:22:17:20 +0100] "POST /source-delete/ac99d3d8-8d27-4576-a08d-1afa467e5e95 HTTP/1.1" 502 150 "http://192.168.2.8:48484/source-delete/ac99d3d8-8d27-4576-a08d-1afa467e5e95" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"
[2022-01-03 22:17:20 +0100] [456] [WARNING] Worker with pid 1039 was terminated due to signal 9
[2022-01-03 22:17:20 +0100] [1057] [INFO] Booting worker with pid: 1057
2022-01-03 22:17:21,004 [tubesync/INFO] Using database connection: django.db.backends.mysql://username:[hidden]@host:3306/database
192.168.2.2 - user [03/Jan/2022:22:17:21 +0100] "GET /favicon.ico HTTP/1.1" 499 0 "http://192.168.2.8:48484/source-delete/ac99d3d8-8d27-4576-a08d-1afa467e5e95" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"
```

The channel/source is https://www.youtube.com/c/inanutshell

Trying to "trick" the system by editing the source to another channel dodesn't work either. is there a way to manually delete a source and all its related data from the database?

I'm using a mariaDB database as backend, and everything runs on unRAID 6.9.2.

**Comment by csjoh** [comment]
Okay, I managed to delete the source through the docker shell:

`python3 ./manage.py delete-source --source ac99d3d8-8d27-4576-a08d-1afa467e5e95`

I forgot to include flags to preserve downloaded media files, but that's fine.

I don't understand why this channel source should cause these kinds of problems.

**Comment by meeb** [comment]
It's because I never expected a delete operation to take over a minute when I smashed out the initial hacky code, which with very large channels it does. A delete operation in the UI is currently synchronous so it deletes the source, all media records with it and optionally the files on disk, as well as all tasks associated with the source or media linked to the source to clean itself up. This is intensive and takes a while. It's planned to move this to a background worker in issues like #94 - the CLI command you found exists as a hack to run the delete operation for longer than 59 seconds. It's on the list to fix.

**Comment by bigbeka** [comment]
> Okay, I managed to delete the source through the docker shell:
> 
> `python3 ./manage.py delete-source --source ac99d3d8-8d27-4576-a08d-1afa467e5e95`
> 
> I forgot to include flags to preserve downloaded media files, but that's fine.
> 
> I don't understand why this channel source should cause these kinds of problems.

Thank you, this helped. 👍
