### ISSUE TITLE
Request: add toggle to show/hide ONLY skipped media

### ISSUE THREAD

**Issue by csjoh** [meeb/tubesync#197]
As there's already a button to show skipped media, this is probably more of a filtering thing.

In short, I'd like to be able to see ONLY skipped media so that I won't have to wade through pages and pages of hundreds or thousands of completed downloads to find the 5 or 6 (or 20) that haven't succeeded. As such, a button/toggle to show only the media marked as skipped would be a welcome addition.

(In the same vein (of lazyness) it would be nice to have a way to bulk enable said skipped media, but I can see that one getting messy fast.)

**Comment by meeb** [comment]
Yep a reasonable feature request. I'll pop it on the list. Thanks.
