### ISSUE TITLE
Files aren't being named properly

### ISSUE THREAD

**Issue by DutchyOven** [meeb/tubesync#20]
Below is the list and how its setup. I'm getting the first file named properly but files after that are weird symbols and letters after that.

```
Pull Up - 2020-03-22 - Pull Up - The Best Of [1080p-avc1-mp4a],mkv
PENT0U~L.mkv
PAX7MC~I.mkv
```

```
Type | YouTube playlist
-- | --
Name | Pull Up
Media items | 0
Key | PLhKmHfWT5YmKh7oyYbW-tyDwS3_23Kw64
Directory | /downloads/Pull Up/
Media format | Pull Up - {yyyy_mm_dd} - {title_full} [{format}].{ext}
Example filename | Pull Up - 2020-12-19 - Some Media Title Name [1080p-avc1-mp4a-60fps-hdr].mkv
Index schedule | Every 6 hours
Created | 2020-12-19 10:57:56
Last crawl | Never
Source resolution | 1080p (Full HD)
Source video codec | AVC1 (H.264)
Source audio codec | MP4A
Prefer 60FPS? |  
Prefer HDR? |  
Output extension | mkv
Fallback | Get next best resolution but at least HD
Copy thumbnails? |  
Write NFO? |  
Delete old media | No, keep forever
```

**Comment by meeb** [comment]
What file system are you saving these downloads to? Is it Unraid or Windows or something like that?

**Comment by DutchyOven** [comment]
> What file system are you saving these downloads to? Is it Unraid or on a Windows system or something like that?

Unraid, sorry about that I’m saving it to an xfs file system in Unraid.

**Comment by meeb** [comment]
I believe this is the default behaviour in `youtube-dl` when it encounters a filename which is unsupported by the filesystem it's trying to write to. For example, writing some UTF8 filename chars to an Unraid volume. It just picks a random name so the file isn't lost. I don't think this is anything TubeSync itself is doing, but if your videos have extended UTF8 chars in their titles try using `{title}` not `{title_full}` and see if that works. {title} is "slugified" and has extended chars auto-removed for this exact reason.

**Comment by DutchyOven** [comment]
I took your advice then I randomly went into unraids filesytem to delete a file. The files are fine on unraid its only when I view them through a windows SMB share they look bad. Maybe its a title length thing? 

![63F05B11-2ECA-4B3E-8941-EF0AB5AB8E47](https://user-images.githubusercontent.com/14810042/102695027-dcf70780-41f2-11eb-97cb-8966fe391334.jpeg)

**Comment by DutchyOven** [comment]
Im going to close this since its not tubesync. Thanks for the quick response!

**Comment by meeb** [comment]
Yes, could well be. SMB does have shorter file length limits than the bare filesystems. Cheers.

**Comment by DutchyOven** [comment]
> 
> 
> Yes, could well be. SMB does have shorter file length limits than the bare filesystems. Cheers.

Side note in case anyone brings this up, your method words fine with SMB. Title shows up like normal.
