### ISSUE TITLE
Support passing YT credentials for age-restricted videos

### ISSUE THREAD

**Issue by craysiii** [meeb/tubesync#200]
I just set up TubeSync in docker and set a source, but I have a single video that will not download. I can see in my error logs that an error is being thrown:

```
2022-01-13 11:07:44,212 [tubesync/ERROR] ERROR: [youtube] p2tGTBhD_8U: Sign in to confirm your age. This video may be inappropriate for some users.
``` 
Would it be possible to add a space to pass credentials so we can access these videos?

**Comment by meeb** [comment]
This has been discussed quite a few times in issues like #129 - I've not implemented this to date specifically because I don't want to be responsible for anyone getting their Google account impacted.

**Comment by craysiii** [comment]
My apologies, I looked through the issues but didn't realize that the cookies.txt issue currently open was related.

I will track that issue. Thank you for your response.

**Comment by meeb** [comment]
No problem, thanks for the issue.
