### ISSUE TITLE
Generate metadata as json

### ISSUE THREAD

**Issue by bullyrooks** [meeb/tubesync#202]
Hi,  I'm trying to integrate tubesync with plex.  As you are probably aware, indexing youtube data in plex is pretty awful.  I was planning on using this tool:
https://github.com/JordyAlkema/Youtube-DL-Agent.bundle
which uses the json file generated (via flag) by youtube-dl as the input into the scanner/agent for indexing.  I _think_ youtube-dlp has similar functionality (their docs say they do)
https://github.com/yt-dlp/yt-dlp#filesystem-options

would it be possible to update the store functionality to include an option to emit the metadata json file, similar to the .nfo function?  This would really help me out.  Otherwise, if there's a better or alternate solution, I would love to hear it. 

I'm willing to write up some docs on my blog (https://bullyrooks.com/index.php/category/technology/home-networking/media/) which (hopefully) could help others get this working as well.

Appreciate your work.  Thanks!

**Comment by meeb** [comment]
There appears to be an embedded API call to write the metadata as a `.info.json` file. I'll give it a test to see if it does what you suggest. I have no issue with adding this feature.

**Comment by bullyrooks** [comment]
awesome.   I'm very interested in that.  If you get a chance to implement it, let me know and I'll pull down, redeploy, test and write up some docs.  Appreciate it!

**Comment by mcinj** [comment]
Just to see if it was possible, [I added parsing of Tubesync's .nfo xml](https://github.com/mcinj/Youtube-DL-Agent.bundle/tree/tubesync_xml) to Youtube-DL-Agent.bundle. It does work as long as the media, nfo, and image file have the same name. #204 will have to get resolved for it to work automatically for either .json or .nfo file as https://github.com/JordyAlkema/Youtube-DL-Agent.bundle also currently looks for a matching .json and image file with the same name, just different extension.

**Comment by ThibaultNocchi** [comment]
Hello,

I am too interested in this feature as the YT metadata plugin for Jellyfin supports reading them from the JSON generated by yt-dl. https://github.com/ankenyr/jellyfin-youtube-metadata-plugin

Thanks!

**Comment by meeb** [comment]
This issue should be resolved thanks to the lovely work by @ThibaultNocchi

**Comment by go2tom42** [comment]
The JSON is missing the `playlist_title` field which is pretty important for [Youtube-DL-Agent.bundle](https://github.com/JordyAlkema/Youtube-DL-Agent.bundle).  If I add `--write-info-json` to yt-dlp that JSON has the `playlist_title` field

example  
`yt-dlp https://www.youtube.com/playlist?list=PLiyWrKfkixib9x1PvdavEXvG82yhs-fws --add-metadata --write-info-json -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' -o "/youtube/%(uploader)s [%(uploader_id)s]/%(title)s[%(id)s].%(ext)s"  --skip-download`

Without that field you can't separate different playlists from the same creator in plex using [Youtube-DL-Agent.bundle](https://github.com/JordyAlkema/Youtube-DL-Agent.bundle)

**Comment by go2tom42** [comment]
It's in the nfo files under the field `showtitle`

**Comment by go2tom42** [comment]
> `showtitle` in the nfo is just the `title` field from the source, it's not the playlist title from YouTube.

Thank you, I was able to hack together a solution using NFO files  
https://github.com/go2tom42/TubeSync-NFO-Agent.bundle

**Comment by meeb** [comment]
Nice, thanks @go2tom42 I'll make a note of your plugin.
