### ISSUE TITLE
Thumbnail/NFO and Video file name mismatch

### ISSUE THREAD

**Issue by AberrantWolf** [meeb/tubesync#204]
When copying the thumnbail or NFO files into the `/downloads/videos` directory using the default template, the video files' names have an extra resolution argument (e.g., `2160p`) in their file name which the NFO and thumbnail images don't have. This made my Plex refuse to find them (as Plex apparently ignores NFO files?).

My workaround was to add the resolution chunk to all the metadata files -- I wasn't sure if removing it on the media files might mess up the database; and then for all future downloads I removed the `{format}` token from the filename, and now my Plex library seems happy.

**Comment by meeb** [comment]
Thanks for the issue. That could well be a bug you've identified. As for deleting files, currently there is no "does the file still exist on disk" check so feel free to delete or rename media in your download directory. The worst mess you'll get into is TubeSync has some media marked as downloaded, but it isn't on disk so nothing too terrible.

**Comment by mcinj** [comment]
I've noticed this too.
![Screen Shot 2022-01-31 at 8 12 15 PM](https://user-images.githubusercontent.com/98779161/151899753-54cb7061-44ab-41e0-8325-06c2d437530c.png)

The default media format for this source was not modified.

**Comment by ajquick** [comment]
I just started using this program and I about abandoned it until I realized this was an issue I was having as well. None of the thumbnails, NFO or title data was appearing correctly. Now that I have made the change on the filename things are starting to work somewhat as expected in Plex.
