### ISSUE TITLE
Question - Port 8080

### ISSUE THREAD

**Issue by samcro1967** [meeb/tubesync#205]
I have it up and running as a standalone container, but when I connect it to my VPN container's network and go to port 4848, I get another service that is listening on port 8080.  I see in the Dockerfile that port 8080 is exposed.  A little confused between port 4848 and 8080 for this container.  Is there a way to change the config for the 8080 port so it does not conflict with another service?

**Comment by meeb** [comment]
That `expose` line in the `Dockerfile` looks like a bug, I'll patch that shortly. I don't think that would cause what you're experiencing though. The TubeSync container should only listen on `4848`, or whatever port you specify with your `-p` flag or `ports` section in your compose yaml.

**Comment by samcro1967** [comment]
I am seeing listening on port 8080 in the container logs (5th line up from the bottom) when it starts.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-tubesync: executing...
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
  No migrations to apply.
  Your models in app(s): 'sync' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
[cont-init.d] 10-tubesync: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
458:C 17 Jan 2022 07:35:03.140 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
458:C 17 Jan 2022 07:35:03.140 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=458, just started
458:C 17 Jan 2022 07:35:03.140 # Configuration loaded
458:M 17 Jan 2022 07:35:03.185 * Running mode=standalone, port=6379.
458:M 17 Jan 2022 07:35:03.185 # Server initialized
458:M 17 Jan 2022 07:35:03.185 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
458:M 17 Jan 2022 07:35:03.189 * Ready to accept connections
[2022-01-17 07:35:03 -0600] [456] [INFO] Starting gunicorn 20.1.0
[2022-01-17 07:35:03 -0600] [456] [INFO] Listening at: http://127.0.0.1:8080 (456)
[2022-01-17 07:35:03 -0600] [456] [INFO] Using worker: sync
[2022-01-17 07:35:03 -0600] [489] [INFO] Booting worker with pid: 489
[2022-01-17 07:35:03 -0600] [490] [INFO] Booting worker with pid: 490
[2022-01-17 07:35:03 -0600] [491] [INFO] Booting worker with pid: 491
```

**Comment by meeb** [comment]
Yes, that's gunicorn, the application server that runs the Python code. It binds to 127.0.0.1 by default though. You interact with nginx as a reverse proxy in front of gunicorn, and nginx listens on 4848. In short, this is normal and will not affect anything.

**Comment by samcro1967** [comment]
Is there a way to change that port?  8080 is common port used by many other apps.  Can I redirect it to say port 4849 and then configure tubecast to look for gunicorn on port 4849 instead of 8080?

**Comment by meeb** [comment]
It won't interfere with any other container or apps unless you are using "host" mode networking. If for some reason you are using "host" mode networking for tubesync, the fix is to use bridge mode in which case the bind to 127.0.0.1 won't affect any other container or app.

**Comment by samcro1967** [comment]
I am not using host or bridge mode for the tubecast container.  I am attaching it to the network for a VPN container with the docker-compose below.  The VPN container has port 8080 bound to another service.  The VPN container is in bridge mode.

```
    network_mode: "service:VPN"
    depends_on:
      - VPN
      - ```

**Comment by meeb** [comment]
From your original description you are saying that when you connect to host-ip:4848 you see a different service and not tubesync? If so that's an issue with your port forwards. You can't even bind multiple services to the same port so the container wouldn't start of there was a conflict.

**Comment by samcro1967** [comment]
I have multiple apps attached to the VPN container that leverage port 8080 by default.  I only have one app currently connected to the VPN container that is configured to use port 8080.  For other apps that default to port 8080 and are attached to the VPN container, I have configured the app itself to use a different port so there are no conflicts.

My question is can tubesync be reconfigured to use a different port other than 8080 for gunicorn?  Right now when I go to port 4848 I am seeing the app mapped to port 8080 in the VPN container, not tubesync.  I am not getting a conflict when I start the VPN container as I am not specifying a second port mapping for port 8080.  The tubesync docker-compose example does not have a second port mapping for port 8080.  If I were to add say port 4849:8080 as a second mapping to the VPN container, it would fail like you mentioned.  If tubesync is set by default to look for gunicorn on port 8080 it is going to see the app mapped to port 8080 in the VPN container.

Looking for the ability to be able to configure gunicorn to say port 4849, maybe an environment variable GUNICORN_PORT.  I could then add a port mapping to the VPN container for port 4849:4849.  Then when I go to port 4848 I will see tubesync as it then knows gunicorn is on port 4849 and not on port 8080.

**Comment by samcro1967** [comment]
I enabled debug logging on the tubesync container.  gunicorn fails to connect to port 8080 as another app is already bound to that port in the VPN container.  The VPN container is running as there are no port conflicts since there is only one mapping for port 8080 to the other app.

```
[2022-01-17 08:36:28 -0600] [460] [INFO] Starting gunicorn 20.1.0
[2022-01-17 08:36:28 -0600] [460] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2022-01-17 08:36:28 -0600] [460] [ERROR] Retrying in 1 second.
[2022-01-17 08:36:29 -0600] [460] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2022-01-17 08:36:29 -0600] [460] [ERROR] Retrying in 1 second.
```

**Comment by meeb** [comment]
Technically, yes you can reconfigure the port. The existing LISTEN_HOST and LISTEN_PORT env vars will change the listening IP and port of gunicorn. These are meant for people who might want to use their own, different reverse proxy and not the bundled nginx server (like you have your own nginx ingress with SSL termination or something).

Changing this port will cause the nginx server on port 4848 to stop working as nginx is hard coded to forward to 127.0.0.1:8080. Honestly I have no idea what your setup is doing with this VPN container to have all your services run in the same network namespace such that they all share the same localhost, but whatever it is you're doing it sounds like a bad idea. Your container should not "share" a localhost nor should your containers run somehow inside the VPN container, you should be able to have any number of containers all binding to 127.0.0.1:8080 without conflicts. If you insist in having this setup though sure by all means set LISTEN_PORT to something else and it'll probably work. It's entirely untested though.

**Comment by samcro1967** [comment]
I had tried listen_port only yesterday and it did not work.  Today I added both listen_host and listen_port and it works for any others who stumble across this even though the container logs still show "[2022-01-17 09:34:00 -0600] [455] [INFO] Listening at: http://127.0.0.1:8080 (455)".  I had stopped as just listen_port yesterday as the logs seem to indicate that the listen_port variable was not working.

Appreciate your help and the project.  Amazing work.

**Comment by samcro1967** [comment]
Ok, so adding the environment variables does not work.  Not sure it it works for a few seconds initially or it was a browser cache issue.

Running the below commands post docker-compose up has it working.  The logs also show gunicorn is listening on port 4849.  A restart of the container is required for the settings to take effect.
```
docker exec -it tubesync bash -c "sed -i -e 's/8080/4849/g' /app/tubesync/gunicorn.py"
docker exec -it tubesync bash -c "sed -i -e 's/8080/4849/g' /etc/nginx/nginx.conf"
```

**Comment by meeb** [comment]
The environment variables work fine if set properly. Your suggestion is not a sensible idea long term and those ports will reset if you restart the container. I maintain that this is not an issue with TubeSync or a port conflict, this is an issue with your VPN and docker compose stack where multiple containers share the same internal address space.

**Comment by samcro1967** [comment]
The changes will only be lost if the container is removed and readded.  They persist across container restarts.

Below is what I tried with the container on its own network (docker default bridge) with all other containers stopped.  Am I missing something in my docker-compose?  I get 502 Bad Gateway from nginx.

**docker-compose**
```
  tubesync:
    hostname: tubesync
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: always
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - TUBESYNC_DEBUG=True
      - LISTEN_HOST=127.0.0.1
      - LISTEN_PORT=4849
    ports:
     - "4848:4848"
    volumes:
      - "${docker}/tubesync:/config"
      - "${media}/Youtube:/downloads"
```

**Container logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-tubesync: executing...
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
  No migrations to apply.
  Your models in app(s): 'sync' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
[cont-init.d] 10-tubesync: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
456:C 18 Jan 2022 06:40:39.112 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
456:C 18 Jan 2022 06:40:39.112 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=456, just started
456:C 18 Jan 2022 06:40:39.112 # Configuration loaded
456:M 18 Jan 2022 06:40:39.116 * Running mode=standalone, port=6379.
456:M 18 Jan 2022 06:40:39.116 # Server initialized
456:M 18 Jan 2022 06:40:39.116 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
456:M 18 Jan 2022 06:40:39.116 * Ready to accept connections
[2022-01-18 06:40:39 -0600] [455] [INFO] Starting gunicorn 20.1.0
[2022-01-18 06:40:39 -0600] [455] [INFO] Listening at: http://127.0.0.1:4849 (455)
[2022-01-18 06:40:39 -0600] [455] [INFO] Using worker: sync
[2022-01-18 06:40:39 -0600] [488] [INFO] Booting worker with pid: 488
[2022-01-18 06:40:39 -0600] [489] [INFO] Booting worker with pid: 489
[2022-01-18 06:40:39 -0600] [490] [INFO] Booting worker with pid: 490
```
![Untitled](https://user-images.githubusercontent.com/2319445/149939995-32763a96-ea3d-4f1e-b3c2-4b2af8fcaf89.jpg)

**Comment by meeb** [comment]
Yeah because nginx forwards to 127.0.0.1:8080 so the upstream gateway is now broken because you changed the port for the application server to listen on. As I said earlier the LISTEN_HOST and LISTEN_PORT are specifically for if you want to use your own, different, reverse proxy to replace nginx bundled with TubeSync. You REALLY don't need to change these unless you specifically want to put a different reverse proxy in front of TubeSync. Try your barebones compose stack without changing LISTEN_PORT or LISTEN_HOST first.

**Comment by McGriddle** [comment]
I have a similar setup as @samcro1967. The idea is to have a dedicated vpn container where other containers would use its network stack to get the VPN connection for free. Something like: https://github.com/dperson/openvpn-client . I was able to everything up and running by running the two sed commands on the running tubesync container and restarting. Obviously that is not ideal long term. 

I second having the option to change that default port 8080 to something else.

LOVING TUBESYNC. Thank you! :)

**Comment by meeb** [comment]
I'll look into making the nginx upstream port update when you change the `LISTEN_PORT` ENV for gunicorn which will stop nginx breaking when you change the application server port internally. I've seen container setups like the one you linked, but surely having all containers share the same internal IP address and network space is a really bad idea? Would it not be neater to run the containers in a network namespace (`ip netns add ...`) and let the containers keep their own dedicated IPs per container or some similar setup?

Given you have no way to trivially adjust the internals of containers you're going to repeatedly get really annoying conflicts like the one reported here. I'll add a way to change the port without nginx breaking, but really I have to maintain that this is the wrong hack to resolve this issue. The solution is to not have containers share the same internal IP address which is just asking for trouble both operationally (conflicts) and with security (containers potentially able to access each others internal services).

**Comment by timothymiller** [comment]
Specifying LISTEN_POST does not change anything. This issue is still not resolved.

Since 8080 is used by Searx, and it is common to want to run multiple containers on the same VPN network, why not change the Gunicorn default port to 8081?

Better yet, why not the maintainer or an adventurous dev put in a PR to make the LISTEN_PORT environment variable work as outlined in the documentation?

**Comment by meeb** [comment]
8080 is going to be commonly used by hundreds of services with an HTTP interface. Setting `LISTEN_PORT` does change the port gunicorn listens on, at least in my own testing it works fine. Have you set `LISTEN_PORT` correctly? The logic for setting the port is not complicated:

https://github.com/meeb/tubesync/blob/main/tubesync/tubesync/gunicorn.py#L20

I still maintain that attempting to move the internal ports that are not meant to be exposed by default around other services is a relatively futile fix. No doubt someone will create an issue that port 8081 is in use by some other process with this setup. Having the internals of containers share a network so their binds to localhost conflict with each other is the core of the problem here, not listening on a particular port. For example, using wireguard and give each container its own IP would avoid this issue entirely.
