### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by CapricaTix** [meeb/tubesync#207]
I checked the Issues history and couldn't see this subject addressed.

I have an UnRaid setup. Trying to get this to download channels with Age-restricted content. Is there a way to pre add auth within the setup?

**Comment by meeb** [comment]
You can export cookies from your browser and use those. See:

https://github.com/meeb/tubesync/blob/main/docs/using-cookies.md

**Comment by meeb** [comment]
I'll close this for now, but feel free to comment back if the above suggestion doesn't solve your issue.
