### ISSUE TITLE
How to Disable IPV6?

### ISSUE THREAD

**Issue by ngInit** [meeb/tubesync#209]
I need to disable IPV6 in nginx, and I noticed that the necessary configs for that stuff aren't mounted by default in the config folder. What's the best way to access that stuff for your project?

Error message
```
nginx: [emerg] socket() [::]:4848 failed (97: Address family not supported by protocol)
```

There's probably a file somewhere that says something like this that I need to comment out, as that's been the fix for every other project that had this issue
nginx > site-conf > default
```
server {
    listen 4848;
    # listen [::]:4848;
    ...
}
...
```

**Comment by meeb** [comment]
Honestly I don't think anyone has mentioned this before. Do you entirely disable IPv6?

**Comment by ngInit** [comment]
Yeah, It's entirely disabled on my system now due to a Linux issue causing my browser to constantly throw a "Network Change Detected" error. After I disabled this I've found a few of my docker containers using nginx weren't loading properly, and the fix for that has been to comment out the lines related to IPV6, like the example in my post.

I figured I'd find that stuff in tubesync's Config mount, but didn't.

I'm assuming the solution could be as easy as me mounting tubesync's nginx folder, or the parent folder, and overwriting one of the config files in there.

**Comment by meeb** [comment]
Yeah you can overwrite the nginx config if you like, I'll see if I can add an ENV flag for it as well which would be neater.

**Comment by ngInit** [comment]
Do you know what folder path I should be mounting for that?

**Comment by meeb** [comment]
Usual place, `/etc/nginx/nginx.conf`.

**Comment by ngInit** [comment]
Awesome!

For anybody else that stumbled onto this:

```
docker exec -it tubesync bash
cp -r /etc/nginx. /config/nginx
```

Mount /config/nginx to /etc/nginx in your docker-compose and comment out line 57 in nginx.conf

From what I can tell this solved the issue on my end, I'll know for sure if it's fixed when I notice things being downloaded again.

**Comment by meeb** [comment]
You OK if I close this issue? Having a tidy-up.

**Comment by meeb** [comment]
Cheers!

**Comment by hafx** [comment]
> Awesome!
> 
> For anybody else that stumbled onto this:
> 
> ```
> docker exec -it tubesync bash
> cp -R /etc/nginx. /config/nginx
> ```
> 
> Mount /config/nginx to /etc/nginx in your docker-compose and comment out line 57 in nginx.conf
> 
> From what I can tell this solved the issue on my end, I'll know for sure if it's fixed when I notice things being downloaded again.

@ngInit 
I also had the same issue. IPv6 is disabled on my host. 
Nginx didn't start in the ct (same error) 

Thanks for the workaround.
