### ISSUE TITLE
Bug: Error when editing existing media server

### ISSUE THREAD

**Issue by STLawson** [meeb/tubesync#21]
Have plex media server added.
Go to media server information page.
Click on "Edit Media Server" button at bottom of page.
Get the following error:
> 500 - Internal Server Error
> Your request caused an internal server error. This has been logged and our developers will implement a fix shortly.

For reference: running TubeSync 0.6 in Docker on Ubuntu

**Comment by meeb** [comment]
Ah right, yep misnamed an attribute. Thanks, will be fixed in the next release on in :latest in a few mins.
