### ISSUE TITLE
Error adding a valid youtube channel.

### ISSUE THREAD

**Issue by ImIveooo** [meeb/tubesync#210]
It doesn't work when you add a youtube channel with an underscore in its url.

![image](https://user-images.githubusercontent.com/34312282/151950518-e0231757-b435-4eb6-bddd-66cdd7fb6415.png)

**Comment by meeb** [comment]
Use "add a YouTube channel by ID" instead, as you're trying to add a channel by ID.

**Comment by ImIveooo** [comment]
Oh, thank you! Indeed it works now. I didn't think of it. Sorry, if I opened an issue for that...

**Comment by meeb** [comment]
No problem, I'll be the first to admit that UI is clunky. It was added as a hack after some YouTube channels changed their URL format.
