### ISSUE TITLE
RAM if full after resetting tasks

### ISSUE THREAD

**Issue by dav354** [meeb/tubesync#215]
First of all I love this container. Great work! 
But I found a little issue. After I resetted the tasks from the command line the container eats all of my RAM. The container uses about 30 gigs of RAM and gets unresponsive. But I have round about 50 channels which I have to index, maybe it's too much? Is this behaviour normal? Is there anything what I can do? Thank you

![tubesync_reset](https://user-images.githubusercontent.com/98947769/152321142-ff6c133d-34e6-4488-be67-c382f0cd36b3.PNG)
![logs](https://user-images.githubusercontent.com/98947769/152327331-0d99bc4d-4558-40ea-ad01-d82cc02b7d5b.PNG)

**Comment by meeb** [comment]
Could you have a read of #103? You might well be experiencing an valid issue, it's just others might have reported it in another issue first.

**Comment by dav354** [comment]
Ok, thank you. I think this is it. Some of my youtube channels I download are pretty big (I think the biggest has over 20k videos). Now I splitted them up into two instances, one for the videos and one for the music. I hope this decreases the spike of the RAM usage when indexing the channels. I hope this will fix my issue.
