### ISSUE TITLE
Option to download file parts into a temporary directory for combination

### ISSUE THREAD

**Issue by dgomer** [meeb/tubesync#218]
When downloading files into a directory that's actively being monitored by a media server (I'm experiencing this with Jellyfin but I've seen this behavior with Plex as well), sometimes the media server will attempt to start indexing files before the video/audio combination has happened, which leads to the part files being locked so that they can't be renamed or deleted. This makes the downloader fail to finish the download even though it was actually successful - you usually end up with an audio.mkv, video.mkv, and combined.temp.mkv file.

If the audio and video file parts could be downloaded and combined in a temporary directory, and then moved into the monitored directory, this would no longer be a problem.

**Comment by meeb** [comment]
Nice suggestion, thanks. I'll see if you can easily get yt-dlp to download to a temp directory before merging streams.

**Comment by dgomer** [comment]
I believe if you use the `paths` argument for yt-dlp you can set a `temp:` location for the intermediate files.

https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L244-L245

**Comment by meeb** [comment]
Yes I had noticed that, I need to confirm that I can still specify an absolute output path along with just a `temp` entry for that config option works as expected. If it does I'll add this into the next release.

**Comment by dgomer** [comment]
Fantastic! Thank you so much for looking into this :)

**Comment by Yankees4life** [comment]
Any updates on this front?

**Comment by meeb** [comment]
This looks possible from the documentation, it's not been patched yet though and is on the list.

**Comment by tcely** [comment]
I'm experiencing this also. I was using gVisor/runsc and noticed more `*.temp.*` files showing up.

Part of debugging that was turning off Jellyfin monitoring of the tubesync directories.

I would really like to see the download happen in a subdirectory with a file `.ignore` created first then use rename to have the finished files put into place as atomically as possible.

(Jellyfin looks for the .ignore file to skip a directory when scanning a library.)

**Comment by meeb** [comment]
`*.temp.*` or `*.part.*` files persisting generally indicates that your downloads failed at least once, they only stick around after a request to download a media item has "completed" if it failed. Anything relating to download failures in your logs?

**Comment by tcely** [comment]
I'm currently blaming gVisor/runsc for that issue. It hasn't repeated since I launched the container without that. The logs showed errno 13 trying to rename the .temp. file to the final name.

**Comment by meeb** [comment]
Ah yeah that would do it. Obviously without permission to rename the temporary downloads you'd have temp files sticking around as well.

**Comment by meeb** [comment]
This feature has been added thanks to @tcely !
