### ISSUE TITLE
Media art have the wrong names

### ISSUE THREAD

**Issue by azukaar** [meeb/tubesync#219]
![image](https://user-images.githubusercontent.com/7872597/154734224-dc5dff82-f4ad-4c36-9f25-35d716a931d0.png)

The media art has been renamed with the wrong name, more specifically the [resolution] part is slightly different and only includes the fil format

**Comment by meeb** [comment]
Thanks for the report. Is this a dupe of #204 ?

**Comment by azukaar** [comment]
Yes sorry
