### ISSUE TITLE
Downloads Fail - Error: "local variable 'vformat' referenced before assignment"

### ISSUE THREAD

**Issue by c235tgfer** [meeb/tubesync#22]
Hello - having an issue with both v0.5 and 0.6. Indexing works fine but the downloads always fail with the error - 

Error: "local variable 'vformat' referenced before assignment"

I have manually selected the video & audio formats as mp4 - not sure if this is causing an issue?

Let me know what logs you need or anything else to look at.

**Comment by meeb** [comment]
Hi, yeah looks like I added a bug into combined stream format handling. Should be fixed in the `:latest` build and it'll be bundled into the next release. Just to confirm this was in `tasks.py` line 318?

**Comment by c235tgfer** [comment]
Perfect. Retested, all OK! Thanks for making a great little product.
