### ISSUE TITLE
Request: regex matching to filter automatic downloads

### ISSUE THREAD

**Issue by dRuEFFECT** [meeb/tubesync#220]
Would be great to have the option to filter what videos get automatically downloaded.

Many channels have different video types they put out, some channels organize them well into playlists so playlist specific sources work well there, but a lot don't manage playlists well. I'd really just like to put a filter on the whole channel for sorting specific videos into my own organized collections without having to download EVERYTHING or having to rely on playlists being maintained.

**Comment by meeb** [comment]
I may implement this with keywords (keyword is or is not in the video title matching) rather than regexes which are probably less user friendly. A reasonable idea. I may merge this with another similar issue at some point.

**Comment by dRuEFFECT** [comment]
bumping! would still love filtering, this way i can also have different folder destinations from a single channel or playlist

**Comment by meeb** [comment]
More than happy to accept a PR for this if you didn't want to wait for me to get around to it.

**Comment by dRuEFFECT** [comment]
i certainly would if i could, but don't know squat about developing applications. in any case i'm grateful for having this tool at all, so thank you

**Comment by meeb** [comment]
This should have been added as feature for some time, I'll close this issue for now.
