### ISSUE TITLE
DisallowedHost at /

### ISSUE THREAD

**Issue by Mrbob-l** [meeb/tubesync#224]
Since the last update, tubesync no longer works on 2 unraid machines. Tubesync starts but gives a DisallowedHost at / when I start the webui. There is then 5 pages of ? & at the very bottom it has this message:- You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

Another machine which was not updated is still working fine.

Bob

**Comment by meeb** [comment]
Thanks for the issue. Are you using a custom reverse proxy in front of TubeSync or anything else that would change the hostname you access TubeSync from? Likely, this is due to an update of Django, but this shouldn't have caused an issue unless you've got a slightly unusual setup.

**Comment by Mrbob-l** [comment]
All 3 machines access the net through the same firewall which hasn't changed in ages & were all working fine till the last update. The 2 non working machines regularly move house but did not work at the other address either.  The working one just downloaded a "Space Invaders look at Unraid 6.10 RC3 54 minutes ago. The other two are giving the error.

**Comment by meeb** [comment]
That error specifically relates to the HTTP host being not allowed. The TubeSync container ships with nginx bundled into it which sets the HTTP host for the upstream application server. The only way you can pass an invalid HTTP host is if you're bypassing the bundled nginx server, for example. There may have been a recent change with Django with regards to the HTTP host handling which is why it could be a new issue for you. Specifically, are you accessing gunicorn directly? Are you doing anything not in the standard Docker-style container installation instructions at all?

**Comment by Mrbob-l** [comment]
I don't know what gunicorn is but on 1 machine I just erased the docker image & all the containers & re-installed tubesync by itself & got the same result. I dare not upgrade the remaining working tubesync because that is when the other 2 stopped. The only things I touch on these servers is to update docker images & plugins. Could it be a plugin interfering with it?

**Comment by meeb** [comment]
Can you try setting the environment variable `TUBESYNC_HOSTS` to `*` and see if that helps?

**Comment by bawitdaba** [comment]
> Can you try setting the environment variable `TUBESYNC_HOSTS` to `*` and see if that helps?

I had this same issue on unRAID and this resolved it for me, thanks

**Comment by meeb** [comment]
Excellent, thanks for the feedback. I'll see if I can poke into why and how unRAID is changing the host in the first place.

**Comment by meeb** [comment]
I've just pushed a patch for this that defaults `TUBESYNC_HOSTS` to `*` so it'll work out of the box on unRAID again. There's no real security issues introduced by adding this given the application has basically no security anyway.

**Comment by Mrbob-l** [comment]
Setting the environment variable TUBESYNC_HOSTS to * worked for me too. Thanks so much for the patch also, the excellent program & the continual effort you put into it. Much appreciated.
