### ISSUE TITLE
DisallowedHost at / Invalid HTTP_HOST header

### ISSUE THREAD

**Issue by shreram** [meeb/tubesync#225]
I am running the latest version. I couldn't get to the UI. I am running on unRAID.

I read this issue #224. I verified that this TUBESYNC_HOSTS setting exists in the local_settings.py file.

Update2:  I am running the [SWAG](https://docs.linuxserver.io/general/swag) container.

Here is the error message.

DisallowedHost at /
Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
Request Method:	GET
Request URL:	http://localhost/
Django Version:	3.2.12
Exception Type:	DisallowedHost
Exception Value:	
Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
Exception Location:	/usr/local/lib/python3.9/dist-packages/django/http/request.py, line 149, in get_host
Python Executable:	/usr/bin/python3
Python Version:	3.9.2
Python Path:	
['/usr/local/bin',
 '/app',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/usr/local/lib/python3.9/dist-packages',
 '/usr/lib/python3/dist-packages']
Server time:	Thu, 24 Mar 2022 14:38:02 -0500

**Comment by shreram** [comment]
I figured out this issue. There is a 'Hosts' option in container settings (unRAID).  I changed the value from blank to * and restarted the container. Now, I can access UI.

![Screen Shot 2022-03-24 at 3 19 21 PM](https://user-images.githubusercontent.com/16169720/160003263-4eee7504-05fe-4579-b197-27df1c2be012.jpg)

**Comment by meeb** [comment]
Thanks for the update. The latest version of TubeSync has `ALLOWED_HOSTS` default to `*` so if you're running the latest version of TubeSync this shouldn't occur.
