### ISSUE TITLE
Issue with permissions when trying to resize thumbnails. 

### ISSUE THREAD

**Issue by Kirklnd** [meeb/tubesync#227]
The config and download directories are on a windows network drive that is mounted on the Linux machine running tubesync. Tubesync has been able to successfully create subdirectories and place files on the network drive but when it reaches the “resize thumbnail” phase, it encounters, “PermissionError: [Errno 1] Operation not permitted: '/config/media/thumbs/60/example.jpg'”
``

**Comment by meeb** [comment]
That error can only be a permission issue with your network drive. The container doesn't have permission to create that file, so just re-check your permissions on the network drive.

Also, it is not a good or supported idea to put the config volume on a network share. By default, TubeSync uses an SQLite database which really does not work well when saved to a network share. If you must use a network share for the config volume I would suggest you use Postgres or MySQL backends to replace SQLite. There's guides in the advanced docs in the README for steps.

**Comment by meeb** [comment]
As I don't think this is directly an issue with TubeSync other than known limitations I'm going to close the issue. Feel free to comment back or open a new issue if you continue to experience problems.
