### ISSUE TITLE
Request: add toggle to hide skipped/deleted media

### ISSUE THREAD

**Issue by STLawson** [meeb/tubesync#23]
A thought that might be good from a usability standpoint: add a toggle/option to be able to hide media items that have been deleted/marked as skipped.

I could see a situation where a youtube channel has some videos that are worth keeping, but a bunch of short ones in between that aren't. Hiding those that have been removed so that you can only see the ones that have been "kept" could be helpful. Setting it as an option that you can turn on or off as needed would probably work best in case someone wants to go back and re-enable certain videos that have been deleted and skipped.

**Comment by meeb** [comment]
I can see the use case. I'll think about if it's sensible to integrate into the UI.

Generally, the goal was to have as few options on the interface as possible which is already getting a little busier than I'd like with some of the new requested features added. The source management form is getting a bit silly for example.

It's not meant to by a media manager, just sync a channel and that's about it. If lots of requests come in I might end up adding a generic "advanced stuff" form and hide it away for the couple of power users who want to better manage lots of media. Either way, thanks for the suggestion and I'll put it in the idea bucket for the next time I plan the roadmap.

**Comment by STLawson** [comment]
I understand. Either way, thanks for the great application.

**Comment by meeb** [comment]
Cheers, and thanks for making suggestions.
