### ISSUE TITLE
Feature request: Add video number as a file name variable

### ISSUE THREAD

**Issue by michalmiddleton** [meeb/tubesync#239]
Hi, 
For Playlist downloads, it would be great to have the option to construct video names based on its index number.
eg. `{idx} - {title_full}.{ext}` , where `idx` Is the video index number.

Thank you!

**Comment by HStep20** [comment]
This has been asked many times, but unfortunately it's not possible to grab individual playlist indexes with the youtube api.

I know, because I'd asked about it in #142, but #126 and I believe #45 mention it as well

**Comment by michalmiddleton** [comment]
I was going to comment more on it but then I found answers to my suggestions in the issues you linked. Thanks, closing this request then..
