### ISSUE TITLE
Request: Skip/Import existing files

### ISSUE THREAD

**Issue by Cycor** [meeb/tubesync#24]
I have done a lot of downloading with youtube-dl already, most with different filenames that what tubesync allows so I can't match the new filename, but all with the [videoid] in the name ( for plex integration ), would it be possible to match on the videoid in the filename and mark the file as downloaded (Maybe set the image/xml data to that filename if at all possible)?

**Comment by meeb** [comment]
This has been mentioned by a few other people. One issue here is the fuzzy matching of files to YouTube IDs and then creating a valid database entry in TubeSync to mark it as downloaded. I'm thinking, maybe, of an import style command run on the CLI, but this would require a CSV-style reference file to map existing files to their YouTube IDs as building some catch-all ID extractor that matches all possible combinations of how people have saved filenames is probably an uphill struggle. It's on the roadmap anyway.

There's no way for TubeSync to know what formats your existing file was downloaded it (e.g. YouTube formats 299+160) so the downloaded media metadata would be blank.

The downloading task would need to be reworked a bit as currently the tasks are queued as soon as they are indexed from the source and detected as not downloaded so they would need an additional check to abort the download if the file was detected as imported manually after the indexing but before the download commenced.

Lastly, I built TubeSync initially for my own uses which weren't extremely large numbers of videos. I likely need to do some testing to make sure it doesn't go mental with 100k videos added to the DB or similar issue. While SQLite is fine with lots of records things like pagination of media in the UI in a sensible way might become a problem and there's no front end search or the "number of pages" reaches over the width of the page etc.

As a short term work-around until I get some time to test possible tools to help with this I'd suggest you just use the download cap feature to not download older videos that overlap with what you've already downloaded.

**Comment by meeb** [comment]
This feature now in `:latest` should do what you want. A full guide on how to use it is available here:

https://github.com/meeb/tubesync/blob/main/docs/import-existing-media.md

I'll close the issue for now, if you encounter any issues feel free to re-open this issue with a comment or create a new issue.
