### ISSUE TITLE
Skip media is not working and task trying to download again

### ISSUE THREAD

**Issue by shreram** [meeb/tubesync#241]
I have a few videos downloaded and some failed to download with this error message. 

Downloading media for "abcdef", attempted 13 times
Error: "Failed to download media: aaaaaaa (UUID: 12345) to disk, expected outfile does not exist: /downloads/video/NWorld/2022-01-06_aaaaaaa_1080p-vp9-opus.mkv"
Task will be retried at 2022-05-19 01:06:04

When I browse this link it shows, the following info.

Can download? check 

Matched formats 
Combined: no match
Audio: 251 (exact match)
Video: 248 (fallback)

I tried 'skip media' but this error comes back up again.

When the fallback video format (in this case 248) is not a valid format to download this video? 
How do I reset to skip this media? I tried multiple times but this task comes back again.

**Comment by meeb** [comment]
That error effectively just means the video didn't download. I know that's not especially helpful. All TubeSync does is call `yt-dlp` to download the video, then wait until the task completes, then checks if the expected output video file exists in the download directory.

This could be, for example, the disk is full, the download failed, the audio and video stream merge with ffmpeg failed, etc. If you have other downloads that are working and it's just a few specific videos that are failing it's probably the stream merge issue.

There's a known issue around some formats and recombining streams which currently requires a manual patch to ffmpeg which TubeSync doesn't have at the moment. This isn't specifically a TubeSync issue. You could try dropping into the container and seeing if `yt-dlp` on the command line using those exact formats downloads properly as a test.

**Comment by shreram** [comment]
> You could try dropping into the container and seeing if yt-dlp on the command line using those exact formats downloads properly as a test.

Where do I find yt-dlp command in the logs? I noticed a bunch of GET calls. I verified 'TubeSync Debugging' flag is already set to 'true'.

**Comment by meeb** [comment]
TubeSync doesn't call a yt-dlp command in a shell, it uses the embedded Python API so there isn't one in the lots. You'll need to translate it to the command line flags. Only important things really though are the format (e.g -f 251:248) and the output path. Debug is just the Django debug.

**Comment by shreram** [comment]
I used the following command and the video was downloaded and ffmpeg merged it correctly.

```
yt-dlp -v -f 248+251 --merge-output-format mkv https://www.youtube.com/watch\?v\=abcdefg -o '%(id)s.mkv'

[debug] Command-line config: ['-v', '-f', '248+251', '--merge-output-format', 'mkv', 'https://www.youtube.com/watch?v=abcdefg', '-o', '%(id)s.mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.12 (CPython 64bit) - macOS-11.6.6-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=abcdefg
[youtube] abcdefg: Downloading webpage
[youtube] abcdefg: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] abcdefg: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "httpsLONG_URL"
[download] Destination: abcdefg.f248.webm
[download] 100% of 256.16MiB in 01:35
[debug] Invoking http downloader on "httpsLONG_URL"
[download] Destination: abcdefg.f251.webm
[download] 100% of 14.63MiB in 00:05
[Merger] Merging formats into "abcdefg.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:abcdefg.f248.webm -i file:abcdefg.f251.webm -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart file:abcdefg.temp.mkv
Deleting original file abcdefg.f248.webm (pass -k to keep)
Deleting original file abcdefg.f251.webm (pass -k to keep)
```

**Comment by shreram** [comment]
I think I found the issue. There are non-English characters in the title. Do you think that is causing this issue?

Couple of questions. 

1. If I manually download this video and copy it to the downloads folder, would the crawl task process verify this and ignore to download again 
(ex: Downloading media for "abcdef", attempted 13 times Task will be retried at 2022-05-19 01:06:04)
2. Though I marked this specific video to 'skip media' and why was this task tried again? Is there a global config list where ignore/skip media URL's stored?

**Comment by meeb** [comment]
Yeah the import function will mark it as downloaded if you download it manually. All it does is check that the video ID is present in the filename and it has a video extension, so providing it has the YouTube ID in the filename and an MKV or MP4 etc. extension it'll get marked as downloaded.

The skip function can currently be automatically reset (so to "unskip" a skipped video) by some automated tasks. There is an issue to split skip into "automated" skips and manual skips but that's not merged yet.

**Comment by shreram** [comment]
quick question.

How do you get the date in the filepath? 

```
        err = (f'Failed to download media: {media} (UUID: {media.pk}) to disk, '
               f'expected outfile does not exist: {media.**filepath**}')
```

From help document, it shows it's a publish date

{yyyy_mm_dd} | Media publish date in YYYY-MM-DD | 2021-01-31
-- | -- | --


I ran yt-dlp manually to get the dates (release_date, date, publish_date,upload_date) but all of them are coming up as NA.

Ex: 
yt-dlp -o "%(published_date>)s/%(title)s.%(ext)s" https://www.youtube.com/watch\?v\=-abcde --print filename

But in the errors section, there is a date in the output filename. What is this date? I bet it came from yt-dlp via YouTube.

Error: "Failed to download media: abcdef (UUID) to disk, expected outfile does not exist: /downloads/video/NWorld/**2022-01-06**_nw_title_abcdef_1080p-vp9-opus.mkv"

**Comment by meeb** [comment]
According to https://github.com/yt-dlp/yt-dlp#output-template the output template paramater you're looking for is "release_date".

As said above to get TubeSync to detect the video as already downloaded and mark it as downloaded you need to put the YouTube ID of the video in the filename, this is the "id" parameter for yt-dlp's output template format. E.g.

```bash
$ yt-dlp -o "%(release_date)s_%(id)s_%(title)s.%(ext)s" https://www.youtube.com/watch\?v\=abcde
```

Once your video is downloaded to a directory TubeSync can see, you need to run the `import-existing-media` TubeSync CLI command. This command just lists all the files in a directory and attempts to match the YouTube ID to any not downloaded files, if it finds a file with has the YouTube ID in it which is not downloaded it'll mark it as downloaded so it stops attempting to download it. 

See here for more details:

https://github.com/meeb/tubesync/blob/main/docs/import-existing-media.md

As your source is already set up and your media indexed you can skip straight to step 3 / 4.

**Comment by shreram** [comment]
> $ yt-dlp -o "%(release_date)s_%(id)s_%(title)s.%(ext)s" https://www.youtube.com/watch\?v\=abcde

I tried a number of times. It always gets NA for all dates. 

> https://github.com/meeb/tubesync/blob/main/docs/import-existing-media.md

Cool. I didn't know about this stuff.
