### ISSUE TITLE
No matching formats, even though it appears there are

### ISSUE THREAD

**Issue by smshapiro85** [meeb/tubesync#247]
I have the source set to 1080 preferred, and the fallback "Get next best resolution or codec instead" set, however videos still indicate that there is no match despite seeing a number of available formats, including 1080... any suggestions?

<img width="984" alt="image" src="https://user-images.githubusercontent.com/41717535/174398452-a86fd094-0740-4f9f-97a2-9816c742ae22.png">

**Comment by meeb** [comment]
What video is this failing on? URL or YouTube video ID is fine.

**Comment by smshapiro85** [comment]
Here are two examples:
1. https://www.youtube.com/watch?v=gogEJyoSB9s
2. https://www.youtube.com/watch?v=S4kQ21swmr4

**Comment by meeb** [comment]
I'm not entirely sure what's going on here. The metadata I get for the above videos contains significantly more available formats than you have shown in your screenshot. The format matcher probably does need a tweak to work with those as clearly format 96 in your screenshot should be an exact combined match, however I don't get the same metadata to be able to write a test for it.

Can you run something like this? Assuming you're running TubeSync in a container:

```bash
$ docker exec -ti tubesync python3 /app/manage.py youtube-dl-info https://www.youtube.com/watch\?v\=S4kQ21swmr4
```

This should output the videos raw metadata in JSON into the terminal and attach it to this issue? It will be big, so attached as a plain text file rather than a copy/paste would be easier.

**Comment by smshapiro85** [comment]
Yes thank you meeb, running it in docker on a Mac. Here is the output.
[Terminal Saved Output.txt](https://github.com/meeb/tubesync/files/8942424/Terminal.Saved.Output.txt)

two other item to note that may or may not be related or helpful
1. I am able to save some videos, but for some reason this source playlist has been giving me trouble, as originally reported.
2. When I save down a source or update a source, I get a 502 error, but if i go back to the root url the source was updated successfully. This seems to happen for any save/update i do.

**Comment by meeb** [comment]
The saved output text file you uploaded contains significantly more available formats than your original screenshot shows. Can you try going to one of the failed to download videos in TubeSync and clicking the "delete and skip media" button at the bottom. Once done, wait a few seconds then click "unskip". This will make TubeSync go off to YouTube and refresh the metadata which should contain more available formats.

If this resolves it I'd put this down as a "YouTube being strange" issue, where it only returned a very limited number of available formats during your original metadata indexing.

**Comment by smshapiro85** [comment]
Apologies for the delay, was moving this week-

That worked! I will try this out with any others in the future and if I gather any new information, will report back. Thank you Meeb!

**Comment by smshapiro85** [comment]
@meeb just wanted you to know that this continues to be an issue on this playlist, and it works right after i click the "delete and skip media" button on a media item.

I don't think it makes sense for Tubesync to automatically refresh metadata every time no matching formats can be found, even though it solves it for this issue, and I am always against adding more settings (e.g., "Refresh metadata if no format can be found") unless this is a bonafide YouTube quirk that everyone will run into.

I will first try to re-add the source and then if that does not work, I will try a fresh install of TubeSync and report back.

**Comment by meeb** [comment]
Thanks @smshapiro85 - to me this does very much look like a YouTube quirk where some formats are made available later or possibly on demand. I'll look into an automated metadata refreshing timer, even if it just retries once a day later it might be sufficient.

**Comment by smshapiro85** [comment]
Thank you @meeb! That sounds good, and agree this will be helpful as this does appear to be a YouTube quirk. Appreciate everything you do for this project!

**Comment by smshapiro85** [comment]
@meeb I realized something about this playlist that may be helpful- the videos in this playlist are streamed live first, and then made available in the playlist like a normal YouTube video, so it is possible that TubeSync is picking up the "live stream" version of the video when it is streaming live (I have the playlist set to check the playlist every 2 hours), and therefore finding those quirky first set of formats. Then, after the live stream is completed and the video is made available like a "normal" YouTube video, a simple refresh of course finds the right formats.

So it may make sense to create some sort of live stream playlist mode/setting that rechecks a playlist after a few hours if it gets this quirky set of formats, or it may just make sense to automatically refresh as you mentioned. I think it would be nice to have it refresh sooner than 1 day because one of the things I am trying to do is get these videos on Friday afternoons (I always look forward to them then) but it is by no means a big deal. Just wanted to share this realization as it could potentially help strengthen the apps handling of videos with a lot of people doing live streams these days.

**Comment by meeb** [comment]
Ah, yes live streams are likely to cause this. YouTube makes them instantly available with a limited set of formats then creates additional formats in the background which are made available later. Some sort of retry mechanism would handle this as well. You could probably hack it for now my just setting the re-index time to 24 hours not 2 hours to give YouTube time to transcode more formats.
