### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by hogcycle** [meeb/tubesync#248]
Hi, I'm migrating my tubesync install to a new server. I copied the db.sqlite3 file over and deployed the same docker compose file. The container starts and the webserver is running, but I only get 500 errors. There are no errors in the logs, but I'll attach them anyway.
https://pastebin.com/dFYk88w2

**Comment by meeb** [comment]
Can you run the container with `TUBESYNC_DEBUG=True` as an env var for the container, then reload the page? It should tell you a more descriptive error message.

**Comment by scintillate** [comment]
I get similar issues when accessing certain videos.

Here is an example of the error log after setting debug to true.

TypeError at /media/86f4403c-4494-4ebd-8d91-5cd7f2b2aea8

int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Request Method: 	GET
Request URL: 	http://localhost/media/86f4403c-4494-4ebd-8d91-5cd7f2b2aea8
Django Version: 	3.2.18
Exception Type: 	TypeError
Exception Value: 	

int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Exception Location: 	/app/sync/models.py, line 1061, in duration
Python Executable: 	/usr/bin/python3
Python Version: 	3.9.2
Python Path: 	

['/usr/local/bin',
 '/app',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/usr/local/lib/python3.9/dist-packages',
 '/usr/lib/python3/dist-packages']

Server time: 	Fri, 10 Mar 2023 00:34:25 -0500

**Comment by meeb** [comment]
I've just pushed a fix to catch that error. However, this fix will just stop the 500 error. There is an issue with the media item you're trying to access where its metadata is invalid (it has no duration). I would try skipping then unskipping this media item (after you've updated to `:latest` with this fix in it) to refresh the metadata.
