### ISSUE TITLE
Support for mp3 audio only

### ISSUE THREAD

**Issue by averon420** [meeb/tubesync#249]
Is there any support for *.mp3 or could it be added?

**Comment by meeb** [comment]
There isn't at the moment, TubeSync just downloads the available streams from YouTube and MP3 is not an available format option. It's possible to convert it post-download with ffmpeg and a filter, but it might end up being more hassle than its worth. Are you unable to play MP4 or OGG audio files for some reason?

**Comment by averon420** [comment]
Honestly I don't know, I am just used to mp3. Never used anything else and though its probably good to keep everything in one format. Thats why my question. - BTW which software do you use to organize your audio library

**Comment by meeb** [comment]
Lidarr. I don't specifically use TubeSync to download audio much myself, I added it as a feature for others who might want to use it. I would try OGG downloads, you can likely play them on any modern device without converting them to MP3 first.

**Comment by averon420** [comment]
Thanks a lot, ill try that. Well the thing I don't like with lidarr, is that its not good for single songs. I don't like the principle of albums.

**Comment by meeb** [comment]
No problem. Yes I would agree Lidarr isn't great for single tracks. I'm going to close this issue for now as I probably won't be adding MP3 conversion any time soon, but feel free to open another issue if you have any more questions.
