### ISSUE TITLE
Delete channel via CLI?

### ISSUE THREAD

**Issue by SmartPhoneLover** [meeb/tubesync#250]
Hello, I'm having troubles while trying to delete a source using the GUI. It fails as when we press the reset-tasks button: 502 error.

Is there a way by which I can perform the same action, but using CLI?

**Comment by meeb** [comment]
Yep! Use:

```bash
docker exec -ti tubesync python3 /app/manage.py delete-source [uuid of source here]
```

**Comment by amuilyas** [comment]
For any other beginners like me...

Update the CLI command needs to have "--source" added, and XXX is channel UUID. 
To get database UUID, In GUI hover (or click) over a source
I used PUTTY to SSH into my NAS to execute the below command

docker exec -ti tubesync python3 /app/manage.py delete-source --source XXX
