### ISSUE TITLE
What's the 'max_allowed_packet' value for TubeSync?

### ISSUE THREAD

**Issue by SmartPhoneLover** [meeb/tubesync#251]
I'm facing a lot of errors in the MYSQL connection (TubeSync terminal log) when TubeSync tries to write to the database, showing the **Got a packet bigger than 'max_allowed_packet' bytes** error. My database (MariaDB) is configured to accept up to 16MB currently.

Log: https://pastebin.com/Z7Rm5mbN

**Comment by SmartPhoneLover** [comment]
Seems that setting it to a bigger value (100MB in my case) temporarily, fixes it.

**Comment by meeb** [comment]
`max_allowed_packet` is a MySQL server-side only config option so it's not something I can adjust from TubeSync's database connection parameters. What operation were you attempting to perform where you received the exceeding `max_allowed_packet` related error? The only thing I can do from the application side is reduce the complexity or data over the wire of a query, if it's possible. However, increasing `max_allowed_packet` should be a permanent fix.

**Comment by meeb** [comment]
This was a MySQL configuration issue so I'll close this issue for now.
