### ISSUE TITLE
Dracula Theme for TubeSync

### ISSUE THREAD

**Issue by Hypertoken** [meeb/tubesync#254]
> Hi! Sorry this is more of a feature request than an issue.  Maybe this could be incorporated into the code somehow, or not. Either way, I didn't know where else to put it. So here ya go! 😃

# Dracula Theme for Tube Sync

This is my first attempt at making a theme for **TubeSync** and **Dracula**.  I'm sure my theme could be "optimized", but for now its great!

## Dracula Theme
 
This is currently my favorite them for all things! Check it out “[Dracula — Dark theme for 271+ apps](https://draculatheme.com/)”

**Get my Theme for TubeSync [here!](https://userstyles.world/style/5761/dracula-theme-for-tubesync)**
# Requirements

You'll need to install an extension in your browser; like the open source [Stylus](https://add0n.com/stylus.html). 

Stylus browser extension is available for [Chrome](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne), [Firefox](https://addons.mozilla.org/firefox/addon/styl-us/) and [Opera](https://addons.opera.com/extensions/details/stylus/) browsers.

## Preview
# ![tubesync](https://user-images.githubusercontent.com/6494401/180365582-460e66e9-e8f6-447a-b25c-701012756d2c.png)

**Comment by meeb** [comment]
Thanks! I've not personally heard of Dracula before, but I can see why some people might want a goth dark mode. I'll close the issue but leave it discoverable for others.
