### ISSUE TITLE
Change amount of download retrys

### ISSUE THREAD

**Issue by Mrpuppyz** [meeb/tubesync#258]
I have spoty internet witch will lead to the download being stoped how can I make tubesync keep trying?

**Comment by meeb** [comment]
You can't edit the amount of retries at the moment, but there are quite a lot (5-7 over several days I think). You can also "skip" then "unskip" any media that failed to download to retry its download.

**Comment by Mrpuppyz** [comment]
Ok good to know. Would also like to add more workers but don't understand what command to use to do that. I am currently running in a docker container.

**Comment by meeb** [comment]
I would advise against adding more workers. More workers doesn't increase the number of retries, it just downloads more media or performs other tasks in parallel. This used to be set to more than one, however this quickly resulted in everyone's IP getting throttled by YouTube so it was reduced to 1 by default to prevent this. You can increase the worker number by setting an ENV var for your container (see README), however as said this is generally not a good idea and will likely make things worse.

**Comment by Mrpuppyz** [comment]
Oh ok I see it has to be added to the docker run with -e that's what I was confused about
