### ISSUE TITLE
To many thumbnails

### ISSUE THREAD

**Issue by Mrpuppyz** [meeb/tubesync#260]
Is there a way to have tubesync only download thumbnails for videos I am actually downloading? I have it set to only download videos from the last week however it still downloads every single thumbnail which I do not need. I only wanted to download the thumbnails for the videos from the last 7 days or videos actually downloading. If this cannot be done is there a way to completely disable downloading the thumbnails all together? I really only need the videos thumbnails are not that big of a deal for me.

**Comment by meeb** [comment]
There isn't currently, but that's certainly a sensible idea. I'll add it to the wishlist.

**Comment by MattTheEmp** [comment]
Meeb first off love the project but this issue really needs to be addressed. It will remove much overhead processing from your application and save data.

**Comment by keithcroshaw** [comment]
Trying this all again as I've been playing with ytdl-sub-gui and missed the nice UI. It takes so long to get all the metadata before it can even get started. Is it getting metadata for every video on the channel? That hurts... 🤣

**Comment by meeb** [comment]
Yeah, the full metadata for each media item is needed (even if it's just for the upload date to use as the download cutoff). There isn't a better way to handle it unfortunately. It's only once though on first adding a channel, it's not refreshed every crawl or anything.

**Comment by Mrpuppyz** [comment]
After I added an external database to my set up. It doesn't seem to take as long for the first index. I am pretty much content with the way it works now. Thank you for building this awesome project.

**Comment by meeb** [comment]
Thanks! And yeah, if you want to index big channels an external database is certainly advisable. For anyone else stumbling over this issue:

https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md
