### ISSUE TITLE
Allow variable for using your own Google/YouTube API Key

### ISSUE THREAD

**Issue by turtle2472** [meeb/tubesync#262]
Pretty simple, would like a variable to be able to use my own API key for indexing/searching/downloading YouTube.

I've searched and have found nothing showing this as an option.

**Comment by meeb** [comment]
`yt-dlp` (which is the library that does most of the work that TubeSync is a wrapper for) scrapes the public interface to YouTube and doesn't use the YouTube APIs at all. This is likely to be impossible to implement unless there's some hidden feature of `yt-dlp` I've not seen that switches to using the official APIs.

**Comment by turtle2472** [comment]
Oh, I did not realize that.  I was digging through yt-dlp and there is mention of APIs but "intertube" and other unrelated.  I wasn't sure.  Thanks.
