### ISSUE TITLE
Support downloading multiple sources to the same directory

### ISSUE THREAD

**Issue by blackwind** [meeb/tubesync#265]
I subscribe to one particular YouTube channel that insists on posting tons and tons of short "clip" videos from their full-form shows. I don't want these clips polluting my library; instead, I want TubeSync to download only two of their playlists, both to the same directory, but I'm getting the error "Source with this Directory already exists". Could you add support for this use case?

**Comment by meeb** [comment]
Currently having a unique directory per source is an enforced requirement. It is possible, but it would be quite a lot of work to modify to allow this. Is there a specific issue with just having one directory per playlist? Probably what might be a more sensible feature to add is a per-source "ignore videos under a specific length" filter.

**Comment by blackwind** [comment]
It's strictly a sorting issue on my media server. They have a primary show and a secondary show on the channel, and the shows often reference each other so you need to watch them in order to get all the jokes. I'd like to queue up an episode and have Jellyfin run through the rest in chronological order instead of having to jump back and forth, back and forth between folders.

**Comment by meeb** [comment]
I can see your use case for this, however the internal rejigging required to support it is going to make it unlikely to be added any time soon. It's relatively trivial to remove the fixed requirement on the model, however doing it in such a way that doesn't retroactively break everyone's installs when they edit a source is a far more complicated issue.

**Comment by blackwind** [comment]
In the meantime, then, keyword and length blacklisting would solve many (most?) of my issues. Hopefully that's an easier target to hit.

**Comment by meeb** [comment]
Yep seems a reasonable feature to add. As this is a very different feature to this issue I've added #266 to track it and I'll close this one.
