### ISSUE TITLE
Add keyword and duration filters for sources

### ISSUE THREAD

**Issue by meeb** [meeb/tubesync#266]
Allow exclusion of media on a source by keyword or by length (to not download media under a certain length).

**Comment by meeb** [comment]
Discussed in #265

**Comment by timwhite** [comment]
Would also be good to exclude media over a certain length. One of my channels posts "marathons" which are a collection of previous videos all together. I really don't want those extra ones, especially as they are large!

**Comment by timwhite** [comment]
@meeb Just letting you know that I'm working on this, and at the same time doing a cleanup up all the filtering into a single unified place. From my experience, it's best to express the filtering as "if any of these match, we skip it", which makes the logic easier to follow. I hope to have a branch for testing in the next few days, assuming I can get it to build for testing.

**Comment by meeb** [comment]
Note regex title filtering was added by https://github.com/meeb/tubesync/pull/425

**Comment by timwhite** [comment]
> Note regex title filtering was added by #425

Yep. I need duration filters. I'm also tempted to see if I can implement the last part of #425 that was discussed, so we can easily have the regex flip to an exclusion match instead of an inclusion match. That makes it much easier to write an exclusion list than a list of negative look aheads.

**Comment by meeb** [comment]
Yep all sounds fine. I was linking that just PR on the off-chance you hadn't seen it so you weren't duplicating anything. Thanks for the effort!
