### ISSUE TITLE
Invalid HTTP_HOST header: '127.0.0.1:8080'. You may need to add '127.0.0.1' to ALLOWED_HOSTS

### ISSUE THREAD

**Issue by Spectre988** [meeb/tubesync#269]
Getting this error in the log.  Where do I need to specify the allowed_hosts?

**Comment by meeb** [comment]
Are you manually setting the `TUBESYNC_HOSTS` env var?

**Comment by Spectre988** [comment]
No I am not. 
![image](https://user-images.githubusercontent.com/105654139/192404597-67083369-2b93-45aa-bb9e-ec51b9d24fc4.png)

**Comment by meeb** [comment]
I've no idea where those defaults came from, but they are incorrect. Please put `1` for `TUBESYNC_WORKERS` and put `*` (an asterisk) for `TUBESYNC_HOSTS`. What platform are you installing this on?

**Comment by Spectre988** [comment]
Pfsense

**Comment by Spectre988** [comment]
![image](https://user-images.githubusercontent.com/105654139/192411246-e9c08d77-4cec-4bf5-b6f9-fa0bae94b93d.png)

**Comment by meeb** [comment]
Yep that looks more sensible.

**Comment by Spectre988** [comment]
Working now!  TY

**Comment by meeb** [comment]
No problem. If you need it in the future the list of env vars are always up to date on the readme here:

https://github.com/meeb/tubesync#advanced-configuration
