### ISSUE TITLE
How to pay you?

### ISSUE THREAD

**Issue by BerndErnst** [meeb/tubesync#27]
Hey there,

you really scratch an itch with your project!
Installation and Usage has worked without any problems.
Since you are providing value to my life, I want that I can rely on a stable development.
Do you want to enable Github Sponsorship or an alternative to pay you?

**Comment by meeb** [comment]
Sounds awesome, thanks for the offer! I'll apply for the sponsor program.

**Comment by meeb** [comment]
All done, here you go, I think: https://github.com/sponsors/meeb

I've not signed up to the sponsorship stuff previously so hopefully that's all working correctly. Given you're likely the only sponsor feel free to message me if you want to sponsor any other amount as I just used the default examples.

Thanks again!

**Comment by BerndErnst** [comment]
Glad that you could enable the sponsorship program.
Although your prices are rather high for such a young project. I would recommend you put your prices down by factor 10, so you will have more early supporter and can grow it more easily.
Better get a couple of 1 USD supporter than none 50 USD supporters 😛

**Comment by meeb** [comment]
Sure, sounds reasonable, I did think the suggestions were a bit overly optimistic when I was setting it up. I've added a $1 tier, which is the lowest it will let me add.

**Comment by BerndErnst** [comment]
You got your first sponsor!
You may also enable the sponsor button on the tubesync repo. Then people see that it's possible to support you.
Without your previous link here I wouldn't have been able to find it.

**Comment by meeb** [comment]
Thanks! Good suggestion, I'll add links and stuff to the readme when I next get a day off to do the outstanding issues for the next release. Cheers for your support. I'll close this issue now but re-open it if there's anything sponsorship related you want to suggest in the future.
