### ISSUE TITLE
Failed to download media with videos that have titles with ampersands &

### ISSUE THREAD

**Issue by bawitdaba** [meeb/tubesync#274]
Any media that has an ampersands '&' fails to download as it is not an allowed char by the file system.

 Downloading media for "Intel Arc A770 & A750 Reviews, 13th-Gen Announced, Q&A | The Full Nerd ep. 232", attempted 4 times
Error: "Failed to download media: ZOe8HbFGB7I (UUID: 28410e37-25f9-42eb-acbd-2a064839a34a) to disk, expected outfile does not exist: /downloads/Watch Later [PLqk337G1EjgQewTSDjmxrtlZRfbbqmxhK]/2022-10-05 - intel-arc-a770-and-a750-reviews-13th-gen-announced-qanda-the-full-nerd-ep-232 [ZOe8HbFGB7I].mkv"
 Task will be retried at 2022-10-08 23:34:28

 Downloading media for "Nine Inch Nails Live Q&A from the Rock & Roll Hall of Fame", attempted 4 times
Error: "Failed to download media: 2knEQPDdiek (UUID: 295ae6c9-4343-4f10-8863-3e7c5a215278) to disk, expected outfile does not exist: /downloads/Watch Later [PLqk337G1EjgQewTSDjmxrtlZRfbbqmxhK]/2022-09-23 - nine-inch-nails-live-qanda-from-the-rock-and-roll-hall-of-fame [2knEQPDdiek].mkv"
 Task will be retried at 2022-10-08 23:34:30
 
Downloading media for "What NVIDIA DIDN'T Say about the RTX 4090 & 4080", attempted 4 times
Error: "Failed to download media: umeLP2cz8ks (UUID: a4660242-f79f-439c-a300-66b051cad90f) to disk, expected outfile does not exist: /downloads/Watch Later [PLqk337G1EjgQewTSDjmxrtlZRfbbqmxhK]/2022-09-21 - what-nvidia-didnt-say-about-the-rtx-4090-and-4080 [umeLP2cz8ks].mkv"
 Task will be retried at 2022-10-08 23:34:53

 Downloading media for "Cooking With Mikey Musumeci: Pizza Masterclass", attempted 5 times
Error: "Failed to download media: TEplaCPYHuc (UUID: ec0d3468-0036-4031-8212-f454fb06c3c6) to disk, expected outfile does not exist: /downloads/Favorites [PLqk337G1EjgSizWcrSYiBqikXDMJnlDXp]/2021-06-12 - cooking-with-mikey-musumeci-pizza-masterclass [TEplaCPYHuc].mkv"
 Task will be retried at 2022-10-08 23:42:32

 Downloading media for "What NVIDIA DIDN'T Say about the RTX 4090 & 4080", attempted 5 times
Error: "Failed to download media: umeLP2cz8ks (UUID: a4660242-f79f-439c-a300-66b051cad90f) to disk, expected outfile does not exist: /downloads/Watch Later [PLqk337G1EjgQewTSDjmxrtlZRfbbqmxhK]/2022-09-21 - what-nvidia-didnt-say-about-the-rtx-4090-and-4080 [umeLP2cz8ks].mkv"
 Task will be retried at 2022-10-08 23:42:54

**Comment by meeb** [comment]
Are you saving the downloads to a network share? `&` is perfectly valid char in file names on most modern file systems.

**Comment by bawitdaba** [comment]
> Are you saving the downloads to a network share? `&` is perfectly valid char in file names on most modern file systems.

hmm you are right it is a valid char, it is an unraid share and it does let me manually make files with &. However all of these failed files have & so I would assume there is an issue somewhere. Maybe it strips out &, but the code is looking for a file with &?

**Comment by bawitdaba** [comment]
I found out how to access the docker logs on unRAID, here is a snippet of the logs for one of these tasks failing.

It seems to fail with an 'ERROR: Conversion failed!', but I still believe the underlying cause is the & in the name as they all have this in common except for one that has a colon ":" in the name which also failed.

TubeSync Docker Log:
> 2022-10-10 18:05:21,632 [tubesync/INFO] Downloading media: umeLP2cz8ks (UUID: a4660242-f79f-439c-a300-66b051cad90f) to: "/downloads/Watch Later [PLqk337G1EjgQewTSDjmxrtlZRfbbqmxhK]/2022-09-21 - what-nvidia-didnt-say-about-the-rtx-4090-and-4080 [umeLP2cz8ks].mkv"
> 2022-10-10 18:05:22,678 [tubesync/INFO] [youtube-dl] finished downloading: 2022-09-21 - what-nvidia-didnt-say-about-the-rtx-4090-and-4080 [umeLP2cz8ks].f313.webm - 536.45MiB in Unknown
> 2022-10-10 18:05:22,679 [tubesync/INFO] [youtube-dl] finished downloading: 2022-09-21 - what-nvidia-didnt-say-about-the-rtx-4090-and-4080 [umeLP2cz8ks].f140.m4a - 10.29MiB in Unknown
> ERROR: Conversion failed!
> 2022-10-10 18:05:24,937 [tubesync/ERROR] Failed to download media: umeLP2cz8ks (UUID: a4660242-f79f-439c-a300-66b051cad90f) to disk, expected outfile does not exist: /downloads/Watch Later [PLqk337G1EjgQewTSDjmxrtlZRfbbqmxhK]/2022-09-21 - what-nvidia-didnt-say-about-the-rtx-4090-and-4080 [umeLP2cz8ks].mkv
> Rescheduling Downloading media for "What NVIDIA DIDN'T Say about the RTX 4090 & 4080"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
>     func(*args, **kwargs)
>   File "/app/sync/tasks.py", line 404, in download_media
>     raise DownloadFailedException(err)
> common.errors.DownloadFailedException: Failed to download media: umeLP2cz8ks (UUID: a4660242-f79f-439c-a300-66b051cad90f) to disk, expected outfile does not exist: /downloads/Watch Later [PLqk337G1EjgQewTSDjmxrtlZRfbbqmxhK]/2022-09-21 - what-nvidia-didnt-say-about-the-rtx-4090-and-4080 [umeLP2cz8ks].mkv
> Rescheduling task Downloading media for "What NVIDIA DIDN'T Say about the RTX 4090 & 4080" for 0:01:26 later at 2022-10-11 01:06:50.974234+00:00

**Comment by meeb** [comment]
The `&` and `:` is already being stripped if you look at the expected output filename of `what-nvidia-didnt-say-about-the-rtx-4090-and-4080 [umeLP2cz8ks].mkv`. That error just means that after `yt-dlp` was called to download the video the expected output file didn't exist. Can you try dropping a shell into the container and seeing if `yt-dlp` can download `https://www/youtube.com/watch?v=umeLP2cz8ks` directly? Typically, these sorts of issues are common with media which was (for example) a live stream and the stock Debian version of ffmpeg is erroring combining a DASH encoded stream or similar kind of issue.

**Comment by bawitdaba** [comment]
> The `&` and `:` is already being stripped if you look at the expected output filename of `what-nvidia-didnt-say-about-the-rtx-4090-and-4080 [umeLP2cz8ks].mkv`. That error just means that after `yt-dlp` was called to download the video the expected output file didn't exist. Can you try dropping a shell into the container and seeing if `yt-dlp` can download `https://www/youtube.com/watch?v=umeLP2cz8ks` directly? Typically, these sorts of issues are common with media which was (for example) a live stream and the stock Debian version of ffmpeg is erroring combining a DASH encoded stream or similar kind of issue.

I replaced my ffmpeg with this https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz and all of the issues/errors went away and those 5 videos downloaded without issue

**Comment by meeb** [comment]
Thanks for the confirmation. This will likely have been solved by the recently merged PR #275 which will be in the next release.

**Comment by Revan335** [comment]
> Thanks for the confirmation. This will likely have been solved by the recently merged PR #275 which will be in the next release.

Thats great!
I have the same Error and non stop waiting for the next release with the fix!

**Comment by meeb** [comment]
The above discussed versions of ffmpeg are now in the `:latest` image which should fix this.
