### ISSUE TITLE
Can't use escape characters in filenames

### ISSUE THREAD

**Issue by ngInit** [meeb/tubesync#278]
I'm trying to format my file name to include the {key} inside two {} brackets - so it would be something along the lines of "Title Name {SoMeUnIqUID}.mkv"

If I set the Media format to be "{title_full} {{key}}.{ext}" the result is "Title Name {{key}}.mkv"

If I try to do "{title_full} \\{{key}\\}.{ext}", I get an error "Invalid media format, the media format contains errors or is empty. Check the table at the end of this page for valid media name variables".

You should either be able to use escape characters to format your file names however you want, or using {{key}} should format the key with two {} surrounding it.

_________
https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/

Using {} brackets for movie IDs (albeit not the exact same scenario as a YouTube video), is the recommended standard for naming your files in Plex.

**Comment by meeb** [comment]
The filename format is just Python string formatting. For a `{` or `}` to actually represent you just need three of them:

```python
>>> '{{{key}}}'.format(key='test')
'{test}'
```

First set are for the value, second two represent a literal character.

**Comment by meeb** [comment]
Ah the `flag_hdr` flag looks like it might need some tweaks to work. Thanks for reporting it.

**Comment by tcely** [comment]
This looks like it can be closed.
