### ISSUE TITLE
Only Download Last N Videos

### ISSUE THREAD

**Issue by maddox** [meeb/tubesync#282]
Am I missing something, or is there no way to add a new source and limit the number of videos to download. I'd like to start pulling videos in from a channel, but only the last 5 or so, or the most recent ones. The last thing I want to do is download hundreds of videos.

Is there a way to set this?

**Comment by meeb** [comment]
You're not missing anything. There is a download cap, but this is implemented by time not by number of videos such as only download the last week/month/year of videos etc. rather than a specific number of videos.

**Comment by maddox** [comment]
OK great, where are these limits set for the source?

**Comment by meeb** [comment]
The "download cap" drop-down, set per source.

**Comment by maddox** [comment]
🤦‍♂️ My brain instantly went to bandwidth on that one. Thanks!
