### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by Mrpuppyz** [meeb/tubesync#284]
Is there a way for me to make a money donation to this project? With this project I've been able to kick my monthly bill to YouTube's premium subscription. I feel as though this project deserves at least some of the money I would have given to YouTube.

**Comment by meeb** [comment]
Thanks for the offer! You're welcome to go to https://github.com/meeb/tubesync and click "sponsor" on the right had side of the page to sponsor be through GitHub.

**Comment by meeb** [comment]
Awesome, thanks a lot!
