### ISSUE TITLE
Unreachable Database

### ISSUE THREAD

**Issue by Dvalin21** [meeb/tubesync#289]
As tubesync is going through the process I get the following error.

2022-11-23 17:25:02,011 [tubesync/INFO] Saved 40701 bytes of metadata for: Kingdom Muzic / 44ae536e-623f-4f02-937c-9af5adcf5622 Failed to retrieve tasks. Database unreachable.

Let me know if there is any other logs needed. Thanks.

**Comment by meeb** [comment]
What database are you using? "Database unreachable" is an actual database driver error.

**Comment by cdurepo** [comment]
I am getting this with a new install using the docker image. 
I start the container and when I browse to it I get a 400 error. 
When I follow the logs I get: 
"Failed to retrieve tasks. Database unreachable."

**Comment by meeb** [comment]
What database are you using? Just the default SQLite? Or did you set up MySQL, MariaDB, Postgres etc?

**Comment by cdurepo** [comment]
I am using the docker image, I have not made any changes to it.  It seems to be trying to use the django sqlite but it is getting lock issues.  I have set the TUBESYNC_WORKERS=1 but that does not seem to help.

**Comment by Dvalin21** [comment]
> What database are you using? "Database unreachable" is an actual database driver error.

Mariadb

**Comment by meeb** [comment]
This was a setup issue with either MariaDB or the connection details passed to tubesync, feel free to create a new issue if you still experience problems. Closing for now.
