### ISSUE TITLE
Permanent failure with MariaDB

### ISSUE THREAD

**Issue by vmonichon** [meeb/tubesync#290]
Hi,

I'm receiving multiple channels with this type of errors:

"This source has encountered permanent failures listed at the bottom of this page, check its settings"

My source is defined with the Channel ID:

Type	YouTube channel by ID
Name	Taskmaster
Media items	661
Key	UCT5C7yaO3RVuOgwP8JVAujQ

The error at the bottom is the following:

 Index media from source "Taskmaster"
Error: "(1366, "Incorrect string value: '\\xF0\\x9F\\x8D\\x86\\xF0\\x9F...' for column `tubesync_db`.`background_task`.`verbose_name` at row 1")"
 Occured at 2022-11-28 11:09:52

This what I get in the logs:

django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x8D\\x86\\xF0\\x9F...' for column `tubesync_db`.`background_task`.`verbose_name` at row 1")
Marking task Index media from source "Taskmaster" as failed
2022-11-28 11:09:52,689 [tubesync/ERROR] Permanent failure for source: Taskmaster task: Index media from source "Taskmaster" - 2022-11-28 16:09:52.682876+00:00

Looking into it, it seems it's an issue with how the table DB/Collation would be setup. Mine was setup by TubeSync to : utf8mb3_general_ci

Not sure if this apply but this is what I found about this specific string:

https://stackoverflow.com/questions/20411440/incorrect-string-value-xf0-x9f-x8e-xb6-xf0-x9f-mysql

Let me know if you need anything from me, I'd be glad to help.

Thank you, great work with the app!

**Comment by meeb** [comment]
This is indeed an encoding issue. You need to create your MySQL / MariaDB databases as `utf8mb4`, for example with:

`CREATE DATABASE tubesync CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;`

This is described in the docs here:

https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md

This isn't a TubeSync issue, it's a Django issue as Django requires 4 byte UTF8 columns in the database.
