### ISSUE TITLE
Why am i getting these metadata issues?

### ISSUE THREAD

**Issue by mjessa12** [meeb/tubesync#292]
![image](https://user-images.githubusercontent.com/72001246/205361781-6293ffaf-fb33-4f21-818d-26f353d1c92c.png)

Anyone know how to fix these errors/why i am getting them?

**Comment by meeb** [comment]
Try removing the @ symbols, so just https://www.youtube.com/channel/4AMBreaks for example.

**Comment by mjessa12** [comment]
I think the issue is that it is adding "/c" in the URL for the channel

this is from portainer log:
`sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/c/@MrSuicideSheep/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.`

when you take that link and paste it in chrome it gives an error but if you remove /c/ it works.

**Comment by meeb** [comment]
I've never seen the @ syntax previously. It looks like YouTube entirely ignores the @ as `https://www.youtube.com/MrSuicideSheep/videos` works. This is a vanity URL and not a channel name. The actual channel name internally in YouTube is `UC5nc_ZtjKW1htCVZVRxlQAQ`. You can add this channel in TubeSync as `https://www.youtube.com/channel/UC5nc_ZtjKW1htCVZVRxlQAQ`.

**Comment by mjessa12** [comment]
OK Thanks I will try that.  How did you get the internal youtube channel ID?

**Comment by meeb** [comment]
You can read this issue which is a duplicate, work-arounds and commands discussed:

https://github.com/meeb/tubesync/issues/243

**Comment by mjessa12** [comment]
thanks!!
