### ISSUE TITLE
NFO/jpg not saving to same folder as content/metadata.

### ISSUE THREAD

**Issue by NeuralMiner** [meeb/tubesync#294]
Hello.
Odd issue. When I set the media format to nest the files inside of a folder (I use the year), it doesn't place the extra nfo and jpg files in the same folder as the video and metadata files; it places them in the root folder.
The media format I'm using: Season {yyyy}/{title} {mm}{dd} [{key}].{ext}

Screenshot of directories:
![image](https://user-images.githubusercontent.com/20843698/207505709-76264753-fe38-458c-aee9-bb05f442cff0.png)

![image](https://user-images.githubusercontent.com/20843698/207506094-fb6c93d2-9a17-4c54-982c-9e143522d026.png)

**Comment by meeb** [comment]
No, when the media item is not downloaded the filename is effectively the "future filename" created from parameters set in the source (such as desired resolution etc.). This changes if the source is updated. Always using `self.filename` would cause the reference to the filename that's actually downloaded (and therefore a fixed name of a file on disk once downloaded) to break.
