### ISSUE TITLE
Unable to archive channel with vanity url

### ISSUE THREAD

**Issue by CJOS100** [meeb/tubesync#30]
Hello, firstly, thank you making this project, it has saved me a lot of time and effort!

I am facing an issue where I am unable to add the following channel as a source, I tried adding it with both options, channel id and url.
`https://www.youtube.com/user/SethEverman/videos`

The issue is when changing the url to the required format (`https://www.youtube.com/c/SethEverman`), it results in an error, the page doesn't exist when using the /c/ url. It appears to be a similar issue to #9 

![chrome_2020-12-30_22-05-47](https://user-images.githubusercontent.com/19960681/103383645-63f98900-4aeb-11eb-9734-d02b8417af34.png)
![chrome_2020-12-30_22-11-13](https://user-images.githubusercontent.com/19960681/103383790-fac64580-4aeb-11eb-9f40-ab3796a630e1.png)

**Comment by meeb** [comment]
Ah yes, another channel format I'd not noticed before. I'll add support for it in the next release. Cheers for reporting it.

**Comment by meeb** [comment]
This issue will be entirely resolved by ongoing work on issue #33 so I'll close this for now as it's redundant. Thanks for the report. Your issue should be resolved in the future `v1.0` release. Feel free to re-open an issue then if you find more bugs.
