### ISSUE TITLE
[Installation]: Native installation on server

### ISSUE THREAD

**Issue by HeadMountainRain** [meeb/tubesync#304]
I followed the mini guide https://github.com/meeb/tubesync#manual-non-containerized-installation for installation on my server without a docker. When using Gunicorn or Uwsgi, I get the following error. Please help me find out where I make a mistake?

> [2023-01-09 19:21:39 +0300] [3849] [INFO] Starting gunicorn 20.1.0
> [2023-01-09 19:21:39 +0300] [3849] [INFO] Listening at: http://127.0.0.1:8000 (3849)
> [2023-01-09 19:21:39 +0300] [3849] [INFO] Using worker: sync
> [2023-01-09 19:21:39 +0300] [3850] [INFO] Booting worker with pid: 3850
> [2023-01-09 19:21:39 +0300] [3850] [ERROR] Exception in worker process
> Traceback (most recent call last):
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
>     worker.init_process()
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
>     self.load_wsgi()
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
>     self.wsgi = self.app.wsgi()
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
>     self.callable = self.load()
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
>     return self.load_wsgiapp()
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
>     return util.import_app(self.app_uri)
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
>     mod = importlib.import_module(module)
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/home/XXX/tubesync/tubesync/tubesync/wsgi.py", line 9, in <module>
>     _application = get_wsgi_application()
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
>     django.setup(set_prefix=False)
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
>     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
>     self._setup(name)
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/home/XXX/.local/share/virtualenvs/tubesync-FMZQCIuA/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'tubesync'
> [2023-01-09 19:21:39 +0300] [3850] [INFO] Worker exiting (pid: 3850)
> [2023-01-09 19:21:39 +0300] [3849] [INFO] Shutting down: Master
> [2023-01-09 19:21:39 +0300] [3849] [INFO] Reason: Worker failed to boot.

**Comment by meeb** [comment]
This is a Python path issue, you'll need to have the `tubesync` module importable by the worker process. It really is easier to run in the container though there's a lot of moving parts that will increase in number in future.

**Comment by HeadMountainRain** [comment]
1. I used the command of the following type: gunicorn --chdir/Home/XXX/Tubesync/Tubesync/-B 192.168.10.2:8001 WSGI &
2. Edited in the settings.py file the line ALLOWED_HOSTS by adding its IP address.
3. Launched the command  ./manage.py process_tasks &
I did not use the reverse proxy. Everything worked on the i386 system.
