### ISSUE TITLE
Like to configure the full path of "Audio" and "Video" inside the container

### ISSUE THREAD

**Issue by frankhommers** [meeb/tubesync#308]
Hi there,

I would like to configure the full path of Audio and Video downloads inside the container.
But as far as I can see in the code this isn't possible? Is it?

Thanks

**Comment by meeb** [comment]
Can you given an example of what you would you like to set the path to?

**Comment by frankhommers** [comment]
I know how docker containers and volume mappings work. :)

My existing Audio directory is with a capital A.
So I'd like `/volume1/media/Audio/YouTube` as a path for my audio files (on the host).

But that isn't doable right now.

**Comment by meeb** [comment]
Can you just map `/volume1/media/Audio/YouTube` to `/downloads/audio` as a work-around? The `audio` and `video` prefixes are pretty hard-coded so making them fully configurable is likely to not be particularly high on my todo list at the moment.

**Comment by frankhommers** [comment]
Yeah OK. I'll do that.
