### ISSUE TITLE
Issue: unable to get exit status from server: Operation timed out

### ISSUE THREAD

**Issue by vger74656** [meeb/tubesync#310]
Hi,

Just ran the updated Docker version of the meeb/tubesync:latest and am getting the following on starting:-

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
  Applying sync.0013_fix_elative_media_file... OK
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: warning: unable to start service tubesync-init: command exited 111

Thoughts?

**Comment by meeb** [comment]
Update to `:latest`, more details in https://github.com/meeb/tubesync/issues/309

**Comment by meeb** [comment]
No problem. Note in `:latest` the timeout is entirely disabled so no-one should have any issues if they're running `:latest`.
