### ISSUE TITLE
Correct way to update with Docker Compose and WatchTower?

### ISSUE THREAD

**Issue by 2600box** [meeb/tubesync#313]
Hello, is there a special way to update monica with docker compose?

Normally I use [WatchTower](https://github.com/containrrr/watchtower) to do this automatically. However for tubesync I get the following error:

```
watchtower-watchtower-1  | time="2023-01-21T04:00:06+01:00" level=warning msg="Could not do a head request for \"ghcr.io/meeb/tubesync:latest\", falling back to regular pull." container=/tubesync image="ghcr.io/meeb/tubesync:latest"
watchtower-watchtower-1  | time="2023-01-21T04:00:06+01:00" level=warning msg="Reason: registry responded to head request with \"404 Not Found\", auth: \"not present\"" container=/tubesync image="ghcr.io/meeb/tubesync:latest"
```

If I try manually with `docker compose pull` it seems to work normally

```
~/tubesync$ docker compose pull
[+] Running 1/1
 ⠿ tubesync Pulled

```

Any idea how to make it play nice with WatchTower?

Thanks!

```
$ cat docker-compose.yml
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /home/docker_user/tubesync/tubesync-config:/config
      - /kohmics/tubesync-downloads:/downloads
    environment:
      - TZ=Europe/Paris
      - PUID=1002
      - PGID=1002
```

**Comment by meeb** [comment]
I use docker compose myself with no issues and `ghcr.io/meeb/tubesync:latest` is the correct image. I've had ghcr.io throw some weird temporary errors so perhaps it's just a temporary problem? There's no sensible reason I can think of why a `docker pull ghcr.io/meeb/tubesync:latest` would result in a 404. I've never used watchtower so I can't comment there. The only guess I would have is watchtower may be providing credentials to ghcr.io (if you supply any credentials public images will 403 or 404) or that ghcr.io is blocking watchtower as a client. Check to see if you have any saved credentials for ghcr.io in watchtower first though.

**Comment by meeb** [comment]
From a quick search of "ghcr.io and watchtower" there are a number of similar reports to yours with various images on Reddit and other forums. Perhaps watchtower and ghcr.io just don't play nicely? Either way, I don't think this is anything tubesync related. If this does turn out to be a weird issue with ghcr.io I'll put mirroring the image on some other registry on the list for when I get time.

**Comment by 2600box** [comment]
Thanks for looking into it. 

I have many other ghcr.io images that update through watchtower without issue.

I noted one observation from googling on this that there is perhaps something to do with pinning to hashes? But I could not figure out how to investigate that on ghcr.io

**Comment by 2600box** [comment]
Just saw that this was fixed here: https://github.com/containrrr/watchtower/issues/1528

**Comment by meeb** [comment]
Excellent, glad you solved it. Thanks for the reference link.
