### ISSUE TITLE
Simple Backup Incase DB Corruption

### ISSUE THREAD

**Issue by keithcroshaw** [meeb/tubesync#315]
I'm not sure how to tag this as wishlist but it'd be in that category, I have no scientific evidence or logs to back this up but every few months something happens and I TubeSync just says it's running but the webUI is dead, that's not really the request here.

It'd be nice if there was a way to export a text or csv file that just includes your sources and their settings that way if the DB becomes corrupt you can just rebuild the image and import the settings and you're back in business. 

I really like the project and use it most nights to enjoy some ad-free tubes, so I understand I should be reporting issues better, but history has taught me it's usually my fault or it's a known issue and I'm just bothering the dev lol.
Thanks for all the hard work, this thing's awesome!

**Comment by meeb** [comment]
This is already pretty much built in. You can back up the contents of the database in plain text via Django. For example:

```bash
$ docker exec -i tubesync python3 /app/manage.py dumpdata > my-backup.json
```

To restore:

```bash
$ cat my-backup.json | docker exec -i tubesync python3 /app/manage.py loaddata --format=json -
```

This is the same process used to migrate between different database backends as well, such as moving from SQLite to Postgres. Or, alternatively, you can do it via the SQLite console directly:

```bash
$ sqlite3 db.sqlite3
sqlite> .backup my-backup.sqlite3
```

**Comment by keithcroshaw** [comment]
Cool I’ll try it out, I’m using Unraid. If you add something on the gui it’d be greatly appreciated.

**Comment by keithcroshaw** [comment]
Can confirm this works. Thanks. Not sure why it keeps failing in the first place.
