### ISSUE TITLE
Permanent Failures: How to fix without re-adding channel?

### ISSUE THREAD

**Issue by tedg** [meeb/tubesync#316]
Hey there, I have a problem with my sources which started on 0.11, I have since upgraded to 0.12 (the original container has been deleted) but the problem is still there. I added 10 or so sources by youtube channel url about a month ago, and everything was running smoothly up until 1/13. At that point, my sources started encountering 'permanent failures' (the exact error is now missing but I believe it was something to do with failure to index).

I am just running from the basic docker instructions, not using a custom db backend.

To try and fix this, I went to reset tasks performed a reset. After that, two of my sources started to work again (a playlist id and a channel by name), but everything else remains in the 'permanent failure' mode, except now I can't see the error message. I don't see how to fix anything without re-adding each one of my sources.

Can I provide you with any log file to help diagnose what happened? It would be great to figure out how to unstuck these sources without re-adding them.

Much ❤️ for the great program!

**Comment by meeb** [comment]
I would really need to see what the failures actually were, so yes pop into the container logs and find an error or two then paste them in here.

**Comment by tedg** [comment]
Ah thanks for you reply, but I think when I removed the 0.11 container where the errors occurred I may have lost the origin of the errors. I don't see anything in my current container about the sources, I guess because they aren't retrying?

Any way to force them to start again or do I just have to re-add them?

**Comment by meeb** [comment]
Run a full task reset off the command line, that should trigger all the indexing tasks etc. to start again. See https://github.com/meeb/tubesync/blob/main/docs/reset-tasks.md - then check the container logs.

**Comment by tedg** [comment]
Thanks, so I ran that from the command line, first it reset tasks for my two working sources, and then when it attempted to reset the next one that has permanent failures, I get a database error
`sqlite3.OperationalError: database is locked`. I ran it again, and it got through a few more sources, but then failed with the same error.

That did seem to unstick the sources that it could get through. Any further advice?

**Comment by meeb** [comment]
Ah, that occurs when you've likely added a bunch of large channels with thousands of media items and the workers are quite busy updating the database. Your best bet is to use a different database back-end which supports multiple concurrent writes:

https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md

**Comment by tedg** [comment]
Ok interesting! I have about 11 sources with about ~120 items each on average I'd say, I'm surprised that is enough to overload things. I'll try to get on with the defaults for now but thanks for the help and being so responsive.

**Comment by meeb** [comment]
It's not really the number of sources or media, SQLite only supports a single writer at once so that "database locked" error means two threads tried to write to the database at once. It can happen with little media, but the probability increases with more media items. This is actually my fault not SQLite as I should have accounted for how long the workers might be active.
