### ISSUE TITLE
Audio-only Tagging

### ISSUE THREAD

**Issue by tamaskan** [meeb/tubesync#318]
I'm using it with navidrome and it would be nice if you could set tags like title or embedd the thumbnail in the file

**Comment by meeb** [comment]
If you select audio only and ogg as a format the downloaded files should just be straight ogg. Are you seeing something different? The next release will have automatically embedded metadata, to the extent supported by `yt-dlp`.

**Comment by meeb** [comment]
Ah right, I'll check but that may well be `yt-dlp` or `ffmpeg` and not something I can fix from the tubesync end, but I'll check to see if there's any additional parameters I can tweak to make it write actual `ogg` files.

**Comment by meeb** [comment]
Yes something like that should be possible. I'd need to find the appropriate API parameters though not command line flag, so the API version of `-x` and `--audio-format opus` in https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L180

**Comment by meeb** [comment]
Excellent, you OK if this issue is closed now?
