### ISSUE TITLE
Failed to Download Media - but it didn’t fail

### ISSUE THREAD

**Issue by striker833** [meeb/tubesync#319]
hello,

I am having an odd issue where TubeSync is reporting all downloads have failed but when I look in the directory all the files appear as expected with the correct names as per the screenshot attached. 

not sure if I am doing something wrong or if this is a some kind of bug.

This is my first time reporting an issue so please let me know if I can be of any further help.

Love the concept of TubeSync! 

![4B111814-31FE-405B-8FA4-A97DF5418270](https://user-images.githubusercontent.com/31484482/216276112-467cd3f0-37b7-4e9b-a2e7-db6f302ba81c.jpeg)

**Comment by meeb** [comment]
What's your `media_format` set to for this source? The `{yyyy_mm_dd}_{source}_{title}_{key}_{format}.{ext}` kind of thing on the edit source form.

**Comment by striker833** [comment]
> What's your `media_format` set to for this source? The `{yyyy_mm_dd}_{source}_{title}_{key}_{format}.{ext}` kind of thing on the edit source form.

{yyyy_mm_dd}_{source}_{title}_[{key}]

The reason for the [] was to try and get the jellyfin YouTube metadata plugin to read the JSON. I have tried without as well but still get the error

**Comment by meeb** [comment]
You're missing the `.{ext}` off the end. The pattern is attempting to write files with no extension, so no `.mp4` or whatever on the end. I believe these are automatically added by `yt-dlp` or `ffmpeg` somewhere along the line if missing, so TubeSync is downloading to `somefile`, the actual file being saved is going to be `somefile.mp4`, thus TubeSync thinks the file is missing on disk and fails the download.

Edit the `media_format` to have `.{ext}` on the end and it should fix it.

**Comment by striker833** [comment]
Of course! This makes complete sense and has fixed the issue.

Silly mistake from me. Thank you!
