### ISSUE TITLE
Media cannot be downloaded because it has no formats which match the source requirements

### ISSUE THREAD

**Issue by Jasonre** [meeb/tubesync#341]
I am a fellow programmer and found this project because I'm trying to pull free kids shows from youtube to my plex server.  This should help me ensure what my 3 year daugher is watching without accidentally browsing to something I don't want her to stumble upon.

Here's the logs from docker:

`2023-02-17 17:49:23 Rescheduling Downloading metadata for "7fde28e8-e529-4335-8bb3-fd3c812a1b91"`
`2023-02-17 17:49:23 Traceback (most recent call last):`
`2023-02-17 17:49:23   File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner`
`2023-02-17 17:49:23     func(*args, **kwargs)`
`2023-02-17 17:49:23   File "/app/sync/tasks.py", line 227, in download_media_metadata`
`2023-02-17 17:49:23     metadata = media.index_metadata()`
`2023-02-17 17:49:23   File "/app/sync/models.py", line 1285, in index_metadata`
`2023-02-17 17:49:23     return indexer(self.url)`
`2023-02-17 17:49:23   File "/app/sync/youtube.py", line 60, in get_media_info`
`2023-02-17 17:49:23     raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '`
`2023-02-17 17:49:23 sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=X21kr0d2c9w": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.`
`2023-02-17 17:49:23 Rescheduling task Downloading metadata for "7fde28e8-e529-4335-8bb3-fd3c812a1b91" for 0:00:06 later at 2023-02-17 22:49:29.013792+00:00`

This is just 1 example, but I added the source with this: https://www.youtube.com/channel/UCvMF0dbLxjQVg9xCxIx8E6g
the metadata that I'm seeing is: https://mattw.io/youtube-metadata/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DX21kr0d2c9w&submit=true

Obviously there is metadata there, but I'm not sure why it's skipping the video now.

**Comment by Jasonre** [comment]
I'm running the latest ghcr.io/meeb/tubesync:latest btw. and if you need me to post any other information let me know.  I'll be eye'ing this pretty closely over the next 2 days.

**Comment by meeb** [comment]
I think this is a change at YouTube requiring an `yt-dlp` update which will be bumped in the next release shortly.
