### ISSUE TITLE
"latest" tag not available for Docker image in registry

### ISSUE THREAD

**Issue by arionl** [meeb/tubesync#346]
I'm unable to pull `ghcr.io/meeb/tubesync:latest`:

```
$ docker pull ghcr.io/meeb/tubesync:latest
Error response from daemon: manifest for ghcr.io/meeb/tubesync:latest not found
```

Pulling the last release works though:

```
$ docker pull ghcr.io/meeb/tubesync:v0.12.0
v0.12.0: Pulling from meeb/tubesync
Digest: sha256:ade7c72f69ced46b58d1baad4b052552a9ddd70ad8d8dde535626378788ccb97
Status: Image is up to date for ghcr.io/meeb/tubesync:v0.12.0
```

I can build myself, but would prefer to use the standard image. Thanks!

**Comment by meeb** [comment]
No idea what's happening there. I can pull `ghcr.io/meeb/tubesync:latest` just fine from multiple servers. Do you have any credentials for `ghcr.io` in your local Docker `config.json` at all? If you do comment them out as a test and try again, that's the only thing I've seen interfere with pulls from `ghcr.io`.

`:latest` is currently more recent than `v0.12.0` so you really want to use the `:latest` (or build it yourself as you have done).

**Comment by arionl** [comment]
Looks like this was an error on my side - my docker was too old to be fully compatible with GitHub's registry (ghcr.io). Weird, this is the first time I came across this problem and the fact that it kinda worked was a little troubling. Anyway, I upgraded from `18.03.0~ce-0~ubuntu` to `5:23.0.1-1~ubuntu.20.04~focal` and all is well now. Sorry about opening the extraneous issue!

**Comment by meeb** [comment]
No problem, glad you solved it.
