### ISSUE TITLE
Howto - Telegram notification if new content arrived

### ISSUE THREAD

**Issue by alneven** [meeb/tubesync#348]
```
Placeholder
```

hi there,
today I was working on a telegram notification which could be easily integrated into Tubesync or added as a service in standalone mode.

The idea was if the /video or /audio folders are modified the system will send a notification via Telegram.

As I’m on ubuntu I have used the `inotifywait` monitoring tool, which is part of the `inotify-tools` and the `telegram-send` app.

telegram-send: [github](https://github.com/rahiel/telegram-send)

**Comment by alneven** [comment]
[source ](https://stackoverflow.com/questions/18901622/run-inotifywait-on-background/68724395#68724395)I got the inspiration

to run the notifier in the background as a service:
```
sudo nano /lib/systemd/system/tubesynctelegramnotification.service
```
and paste this AND change the user and group accordingly
```
[Unit]
Description = Run inotifywait in backgoround

[Service]
User=ubuntu
Group=ubuntu
ExecStart=/bin/bash /path_to/tubesynctelegramnotification.sh
RestartSec=10

[Install]
WantedBy=multi-user.target
```

now you can create the script:
```
nano tubesynctelegramnotification.sh
```
and paste
```
inotifywait -m -r /path_to/tubesync-downloads -e create -e moved_to |
    while read -r path action file; do
        telegram-send "New tubesync video file arrived: $file"
    done
```
the flag "-m" will move the `inotifywait` into the background, and the flag "-r" will check the `tubesync-downloads` folder for new content.

after that reload the damon and start the service
```
sudo systemctl daemon-reload
```

from now after you enable the service you can start / stop / and check the status of it
```
sudo systemctl enable tubesynctelegramnotification
sudo systemctl start tubesynctelegramnotification
sudo systemctl status tubesynctelegramnotification
sudo systemctl stop tubesynctelegramnotification
```

the script will go in the background in monitoring mode and will check your folder recursively

**Comment by alneven** [comment]
addon / tweak:
you can also monitor more than once location

```
#!/bin/sh
MONITORDIR1="/path/to/the/dir/to/monitor1/"
MONITORDIR2="/path/to/the/dir/to/monitor2/"
MONITORDIRX="/path/to/the/dir/to/monitorx/"    

monitor() {
inotifywait -m -r -e create --format "%f" "$1" | while read NEWFILE
do
        telegram-send "New tubesync video file arrived: ${NEWFILE}"
done
}
monitor "$MONITORDIR1" &
monitor "$MONITORDIR2" &
monitor "$MONITORDIRX" &
```


Idea from [here](https://superuser.com/a/959040)

**Comment by meeb** [comment]
Thanks for the write-up! The other typical way to do this if you use Plex is to have tubesync automatically refresh your Plex tubesync library when media is downloaded and then use Tautulli which has a Telegram (and many other) notification agents to trigger a notice when a new media item is added.

The above is an excellent example of manual directory change scanning using shell scripts if you're using tubesync as a stand-alone service or want something lighter weight than another full service like Tautulli.

I'll close the issue but obviously leave it up for anyone else to find. Thanks for your input.
