### ISSUE TITLE
Expected outfile does not exist?

### ISSUE THREAD

**Issue by Qel0droma** [meeb/tubesync#349]
Every time I try download videos I get get this error. What does it mean exactly?
 Downloading media for "Wolverine vs. The Vampires: Wolverine Vol 1 | Comics Explained"
Source: "467dd00a-cdf4-4868-b46b-c808e3e1f246"
Error: "Failed to download media: bfPApYchIX4 (UUID: 2b3f0ed9-fef7-45b5-97ac-b296aec417da) to disk, expected outfile does not exist: /downloads/video/comicsexplained/wolverine-vs-the-vampires-wolverine-vol-1-comics-explained.mkv"
 Task ran at 2023-02-26 17:59:26

**Comment by meeb** [comment]
That error means that tubesync called `yt-dlp` to download the media and when `yt-dlp` was complete the expected downloaded file doesn't exist on disk. This might be that `yt-dlp` failed to download the media item (for example the specified media format wasn't available from YouTube for some reason) or a local reason (for example the directory you're trying to download to is set read-only or is full). You'll need to check further in the logs to find the actual error reason.

**Comment by Qel0droma** [comment]
2023-02-27 16:47:41,841 [tubesync/DEBUG] [youtube] uMGjTYhDcxU: Downloading webpage
2023-02-27 16:47:42,664 [tubesync/DEBUG] [youtube] uMGjTYhDcxU: Downloading android player API JSON
2023-02-27 16:47:43,051 [tubesync/ERROR] ERROR: [youtube] uMGjTYhDcxU: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Rescheduling Downloading metadata for "67bd094d-160b-406f-af3f-c3fde64594bb"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=uMGjTYhDcxU": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "67bd094d-160b-406f-af3f-c3fde64594bb" for 0:00:06 later at 2023-02-27 06:47:49.061025+00:00
Looks like youtube-dl issue? anyone know the command to update youtube-dl?  yt-dlp -U does not work.

**Comment by meeb** [comment]
What version of tubesync and `yt-dlp` are you running?

**Comment by Qel0droma** [comment]
Sorry, already updated yt-dlp to the current version in the cli..will see if that fixes it.

**Comment by meeb** [comment]
Yes, I asked as this was might well be a YouTube issue which was fixed in the latest `yt-dlp` which was updated in the `:latest` tubesync release a few days ago so if you've updated the image if it was previously working it's likely this has now been fixed.

**Comment by Qel0droma** [comment]
Seems to be working now, thanks. guess when I tried to re-pull the image not long ago it was just before new update.
