### ISSUE TITLE
Clean file name of "dangerous" characters

### ISSUE THREAD

**Issue by DeftNerd** [meeb/tubesync#35]
I've been choosing a directory name, and then choosing this as my file name
`Season {yyyy}/{source_full} - {yyyy_mm_dd} - {title_full} ({key}).{ext}`

For the most part it works well, until the {title_full} includes characters such as `|` or `/` or `"` or `'` or `\`

Can you offer a toggle or option to strip characters not safe for the filesystem from the generated filenames, excluding characters actually specified in the Media Format option? Cleaning all the variables before being used in the generated file name should do the trick.

**Comment by meeb** [comment]
A sensible suggestion, thanks, I'll add this in the next release.

**Comment by Paul5656** [comment]
I'd like to add not only those mentioned above but also all illegal characters in windows as well.

**Comment by meeb** [comment]
Yep stripping all illegal chars from potential filenames on all common platforms will be added.

**Comment by ItsME6969** [comment]
@meeb could you please update to also filter out `tabs` too? Just came across a file that had a tab in the filename which is not allowed on windows. Thanks.

**Comment by meeb** [comment]
Tabs should already have been filtered out, unless it was some unusual whitespace tab. I've just pushed a small patch to really ensure any whitespace types are replaced with spaces though just in case, should help.

**Comment by ItsME6969** [comment]
Thanks for the quick patch I'll continue testing and report back if something pops up. Thanks.
