### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by shakil314** [meeb/tubesync#350]
TubeSync version 0.12.0, with yt-dlp version 2023.01.16, is unable to download.
"Unable to extract uploader id..."

yt-dlp version 2023.02.17 fixes this issue

**Comment by meeb** [comment]
Yes, this was a change at YouTube which was fixed in `yt-dlp` version `2023.02.17`. `2023.02.17` is already bundled with the `:latest` release of tubesync. If you are experiencing this issue please `docker pull` the `:latest` image.

**Comment by shakil314** [comment]
My mistake, I was not on the :latest. Confirmed that the latest image, 0.12.1, works fine.

**Comment by meeb** [comment]
Thanks for the confirmation!
