### ISSUE TITLE
"Video unavailable. This video is not available"

### ISSUE THREAD

**Issue by lorissimo** [meeb/tubesync#352]
I've set up TubeSync (through docker on my NAS), and it works as it should. I've only set it up with one YouTube playlist so far (https://www.youtube.com/playlist?list=PLKfpV2bmlzODRtAZJmEKsAm8DRXqRqvzY). This playlist is regionally blocked in my country (Canada), and only one video is available for download, and it downloaded successfully through TubeSync. I receive an error, however, on all of the others... "ERROR: [youtube] _YOUTUBEID_: Video unavailable. This video is not available". The other 66 videos are available when I access the playlist through my US VPN. How can I get around this? I tried to run TubeSync through a docker VPN tunnel (adding 'NET=container:vpn' to the environment variables), but that didn't change anything. Any suggestions or assistance would be greatly appreciated.

**Comment by meeb** [comment]
There's nothing fancy inside of tubesync other than calling `yt-dlp` in terms of networking. If you want to bypass a geoblock changing the outbound default route to use your VPN should work. I would try dropping into the tubesync shell and testing your VPN route is actually working. E.g.

```bash
$ docker exec -ti tubesync bash
# ... in container
$ apt update && apt install curl
$ curl https://httpbin.org/ip
```

which should return the public outbound IP of your VPN if the VPN route is working. If it's not this is a general docker and networking question rather than a tubesync question. If you do find anything that would help you get tubesync to run through a VPN easier feel free to let me know though, I'd be happy to add it.

**Comment by lorissimo** [comment]
Thanks for the prompt reply. I'm sure the VPN container is working properly as I can see the active session pulling the VPN IP address through my provider. I'm pretty new to this for the most part. How do I change the "outbound default route" in my TubeSync container?

**Comment by meeb** [comment]
That's a general container question, usually you'd create a docker network (assuming you're using docker) which uses the VPN then connect the container to the docker network. There's quite a lot of guides on the internet about it.

**Comment by lorissimo** [comment]
I'm aware it's generally out of the scope of your support. I did add the NET environment variable to the TubeSync container pointing to the VPN container but that doesn't seems to be doing anything.

**Comment by meeb** [comment]
I don't see what the `NET` environment variable is meant to do, it's not something the tubesync container would pick up and automatically do anything with so that's why it probably doesn't change anything. Where did setting an env var come from?

**Comment by lorissimo** [comment]
I found it on a Google search.

**Comment by meeb** [comment]
If you mean `--net=container:vpn` then that's not an environment variable, that's a parameter to docker which changes the network of the container as described above. You need to have a container called `vpn` connected to your VPN provider first (and a network for the special container to use) and then make sure the VPN container is working properly before you can connect other containers through it. `gluetun` is a popular container to run for the VPN side of things.

**Comment by lorissimo** [comment]
gluten is what I'm using and it's working. The issue I'm having is connecting that container to TubeSync.

**Comment by meeb** [comment]
Sorry, I misread above you already have a VPN container. I'd really just do some testing then to find out what isn't connected or set up properly. Can other containers use the VPN? Is it just tubesync that won't use it? Or do no containers use the VPN? Have you tried the above testing suggestion with dropping a shell into the tubesync container?

**Comment by lorissimo** [comment]
I'm only the gluten VPN container for TubeSync and again I know that container is working. I guess I'll just have to look into it further.

**Comment by meeb** [comment]
Your VPN container may be "working" in the sense that it is running and connecting to your VPN provider. Your issue seems to be with the networking in your docker / compose stack on your container host (probably) and not with the VPN container itself which is why I suggested testing this from inside the tubesync container that you're trying to link to the VPN container.

**Comment by lorissimo** [comment]
You are, in fact, correct. My bad. I tested using the bash commands you provided in the TubeSync container, and it's displaying my local public IP address, so I guess I'm back to square one. Trying to figure out how to connect the VPN container to the TubeSync container.

**Comment by lorissimo** [comment]
FYI... I just wanted to let you know that I FINALLY figured this out following this guide (https://youtu.be/xbSfaKwyfXE). TubeSync is now running through my VPN and downloading region-locked YouTube videos. I appreciate your time in inspiring me to look into it further.

**Comment by meeb** [comment]
Excellent, thanks for the update and link so others who find this too can fix it!
