### ISSUE TITLE
Request:  Can we avoid the chown/chmod of the /download directory?

### ISSUE THREAD

**Issue by garbled1** [meeb/tubesync#354]
I have a massive media set, and the chown -R/chmod -R takes eons and I just have to kill it to get the container to start, and then edit the run file to make it stop trying.  Additionally, I want my media 775, not 755.

Is it possible to have an ENV or something to make it not do this?  Or maybe even just not do this?

**Comment by meeb** [comment]
Yep this should probably be configurable. This was just a legacy default from when I built it for my own personal use. Thanks for the issue.

**Comment by mitchross** [comment]
Agree I need this also

**Comment by meeb** [comment]
In `:latest` you can now set `TUBESYNC_RESET_DOWNLOAD_DIR=False` which will disable the `chown`/`chmod` on `/downloads` on container start.
