### ISSUE TITLE
Portainer/Docker issue on Pi4 arm7

### ISSUE THREAD

**Issue by hippytyre** [meeb/tubesync#359]
Hello,

I'm running the following in a portainer stack, I had to add platform: linux/arm64 as it kept telling me the version was incorrect otherwise. It runs but with this error : exec /init: exec format error. No ports are open.

version: '3.7'
services:
  tubesync:
    platform: linux/arm64
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /mnt/USBHDD1/shares/Youtube/config:/config
      - /mnt/USBHDD1/shares/Youtube/downloads:/downloads
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000

**Comment by meeb** [comment]
Using `platform: linux/arm64` on ARM is pretty standard and this is about as expected. As tubesync doesn't build separate images for different architectures with `:arm64` tags etc. (it's a single combined image) you'll likely need to specify the platform in some situations. Thanks for documenting this for others!

**Comment by hippytyre** [comment]
Sorry, I probably didn't word that correctly. The container runs, but with the "exec /init: exec format" error. It doesn't open any ports and isn't accessible via port 4848. I'm new to docker so it could be something I'm doing wrong.

**Comment by meeb** [comment]
Ah, right. Can you run the container directly with docker? So `docker run -d --rm --name tubesync --platform linux/arm64 ghcr.io/meeb/tubesync:latest` or similar? Also have you installed the 32bit version of Raspberry Pi OS or the 64bit version?

The error you're getting means either you're attempting to run the amd64 image on your Pi somehow, or that you're running the arm64 image on a 32bit OS.

**Comment by hippytyre** [comment]
Ah, I'm running 64bit on my 32bit system. Well spottted. Like I said, I'm new to this. How would I run the container now? Thanks

**Comment by meeb** [comment]
The short answer is... you don't. Unless you're comfortable with a quite complicated process to build it for yourself. The "easiest" solution is to just run 64bit Raspberry Pi OS on your Pi which would be a re-install or at least a different install to a different SD card. The container builds for tubesync are amd64 and arm64. It is possible to run containers built for other architectures but that's effectively emulation and I wouldn't advise it on something as low powered as a Pi.

**Comment by hippytyre** [comment]
Thanks for the help meeb, I'll find something else to run it on, I have a few pi4's 😀
