### ISSUE TITLE
[Feature Request] Add subtitle download support 

### ISSUE THREAD

**Issue by mylogon341** [meeb/tubesync#367]
It would be great if there was another checkbox in the sources screen that asked if you want to download subtitles too. Not only would this be beneficial for accessibility, but, for example, the channel [Primitive Technology](https://www.youtube.com/@primitivetechnology9550) put's all his "narration" in the subtitles, so it makes channels like that usable.

As for the technical side, yt-dlp supports this quite well with its [subtitle docs](https://github.com/yt-dlp/yt-dlp#subtitle-options) mentioning options.

Thanks a lot

**Comment by meeb** [comment]
This is already an open issue. It's moderately complicated to add subtitles as a feature, it's not just as simple as passing in `--write-subtitles` as tubesync will need to keep track of the downloaded files, index available languages and support the post-processing filters for optional burn-in. See #7 which is the main issue to track this. It's only been recently sufficient features are available upstream to easily add and manage subtitles. I'll close the issue for now as a duplicate.

**Comment by meeb** [comment]
Also, thank you for the support, most appreciated!

**Comment by mylogon341** [comment]
Ah. Sorry. I was on sorting out a few things yesterday and must have thought I had searched for a duplicate of this but clearly didn't. 
Welcome for tip though - you're doing good work here and deserve that + more attention as you continue to improve.
