### ISSUE TITLE
Nothing working?

### ISSUE THREAD

**Issue by vwidmer** [meeb/tubesync#369]
I have tried all different things but can't get anything other than these messages? Any help would be appreciated. Thanks,

` Index media from source "Dinghy Content", attempted 1 time
Error: "Failed to extract_info for "https://www.youtube.com/playlist?list=PL7wkGUDoRLY5h-alcWi7d44DYtT8WyOav": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff."
 Task will be retried at 2023-04-12 15:25:57
 Index media from source "broncosguru", attempted 1 time
Error: "Failed to extract_info for "https://www.youtube.com/channel/UCztFrtFDiRl_f5gSSMxCJYA/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff."
 Task will be retried at 2023-04-12 15:28:37
 Index media from source "broncosguru" once, attempted 2 times
Error: "Failed to extract_info for "https://www.youtube.com/channel/UCztFrtFDiRl_f5gSSMxCJYA/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff."
 Task will be retried at 2023-04-12 15:30:12
`

**Comment by meeb** [comment]
What version of tubesync and ffmpeg are you running? In the footer of the web UI.

**Comment by vwidmer** [comment]
TubeSync version 0.12.1 
yt-dlp version 2023.03.04
FFmpeg version N-110065-g30cea1d39b-20230323.

**Comment by vwidmer** [comment]
Sorry, turns out the issue was on my side. I watched the log and noticed urls were not resolving, so had to make some changes on my network side DNS. All is working as it should now.

**Comment by meeb** [comment]
No problem, glad you got it fixed.
