### ISSUE TITLE
Textbox Misaligned

### ISSUE THREAD

**Issue by Paul5656** [meeb/tubesync#37]
Not sure how to explain this issue but I have to click higher up in the middle of the text box to the upper half of it even the upper outside in order to select and change the text options.

**Comment by meeb** [comment]
I think I kind of understand what you mean, but I'll probably need some screenshots or a gif or something to really follow it.

**Comment by Paul5656** [comment]
Sorry, I can't take screenshots with both the snip tool on windows since it requires moving the mouse and dropbox screenshot hides the cursor. But I'll reiterate that you have to click outside the textbox to be able to edit the text. When I click on the textbox the cursor doesn't change to the blinking one that you use to edit text until you click outside of the actual textbox.

**Comment by meeb** [comment]
What browser and OS are you using? I'll see if I can replicate it.

**Comment by Cycor** [comment]
I did a quick inspect because I had the same problem and it looks like the padding from the text below the textbox is overlapping the textbox and making it hard to click it

**Comment by Paul5656** [comment]
Yeah basically what @Cycor said. I'm using docker on Synology so I guess linux...Chrome browser

**Comment by meeb** [comment]
Thanks for the feedback, I'll dig out Chromium and see if I can spot it.

**Comment by Paul5656** [comment]
Working perfect now!!

**Comment by meeb** [comment]
Excellent! Thanks for testing.
