### ISSUE TITLE
Plex Library Ids

### ISSUE THREAD

**Issue by vwidmer** [meeb/tubesync#370]
I didn't have any luck following the instructions in the link for getting the library selection ID. However, I found this and hopefully maybe it can be implemented in the future to automatically get the IDs or if anyone else is having a issue can just do it in your browser, much easier than messing around in the terminal. 

https://www.plexopedia.com/plex-media-server/api/server/libraries/

**Comment by meeb** [comment]
Thanks! Added your link to the help text on the add a Plex server page.
