### ISSUE TITLE
"The playlist does not exist" error

### ISSUE THREAD

**Issue by shreram** [meeb/tubesync#373]
I am running the latest version. I created a new playlist (private) on YouTube and added that as a new source but no videos were downloaded.

Here is the error message from the logs. I am running this container on unraid. My other TubeSync sources are working fine. In the following log snippet, I substituted the long playlist id with the plastlist_id string.

At the end log, there is an error from youtube-dl. What's the metadata that youtube-dl was expecting? 

"No metadata was returned by youtube-dl"

```log
2023-04-26 21:29:27,730 [tubesync/WARNING] [youtube:tab] YouTube said: The playlist does not exist.
2023-04-26 21:29:27,776 [tubesync/ERROR] ERROR: [youtube:tab] <playlist_id> YouTube said: The playlist does not exist.
Rescheduling Index media from source "TS_New"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 161, in index_source_task
    videos = source.index_media()
  File "/app/sync/models.py", line 517, in index_media
    response = indexer(self.index_url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/playlist?list=<playlist_id>": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Index media from source "TS_New" for 0:00:06 later at 2023-04-27 02:29:33.946801+00:00
```

**Comment by meeb** [comment]
tubesync  won't be able to see your private playlist any more than any other person on the internet can. You'll need to effectively "log in" to YouTube to see the playlist. You can do that by exporting and using your cookies from an active browser session, see:

https://github.com/meeb/tubesync/blob/main/docs/using-cookies.md

Read the important note though, doing this is not without its risks to your Google account which is up to you to decide.

**Comment by shreram** [comment]
Thank you. 

Is this something new from youtube-dl? 

>Read the important note though, doing this is not without its risks to your Google account which is up to you to decide.

What are the risks of providing a cookies.txt file? Can they block my youtube id? 

The reason I created a new source was a couple of sources failed to download any from the last two weeks with this error message. I couldn't find any error messages in the log. 

```log
"This source has encountered permanent failures listed at the bottom of this page, check its settings"
```
I tried a couple of attempts via Chrome dev tools to get the cookies and none of them worked (not a valid format error message from the logs). Finally, I installed a Chrome extension and got the cookies in Netscape format. The moment I dropped the file, the Tubesync source started the download process.

```log
2023-04-27 11:13:05,153 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-04-27 11:13:05,283 [tubesync/DEBUG] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=playlist_id
2023-04-27 11:13:05,283 [tubesync/DEBUG] [youtube:tab] playlist_id: Downloading webpage
2023-04-27 11:13:05,668 [tubesync/DEBUG] [youtube:tab] playlist_id: Redownloading playlist API JSON with unavailable videos
2023-04-27 11:13:05,914 [tubesync/DEBUG] [download] Downloading playlist: TS_New
2023-04-27 11:13:05,961 [tubesync/DEBUG] [youtube:tab] Playlist TS_New: Downloading 6 items of 6
2023-04-27 11:13:05,962 [tubesync/DEBUG] [download] Downloading item 1 of 6

```

**Comment by meeb** [comment]
No, this has been in `yt-dlp` and previously `youtube-dl` for a long time. You have always had to log in some how to see private playlists and other pages behind auth walls. How did you expect `yt-dlp` to see this playlist without logging in?

The risks with using `cookies.txt` is that this links your `yt-dlp` downloads with YouTube and therefore Google account and using tools like `yt-dlp` is potentially something Google won't like. I don't know of anyone who's ever had any issues with this, however the warning is to highlight that Google may at some point take action against accounts using tools like `yt-dlp`. The risk is left up to you to decide.

**Comment by shreram** [comment]
Thank you. 

>How did you expect yt-dlp to see this playlist without logging in?

Now, I understood why other sources worked before without this file. Those YT playlists are either unlisted or public. This error (for this issue) is the first time I ran into it and for this playlist, I set the privacy as 'private'

Btw, after adding the cookies.txt file, other sources (public) started to work (the ones stuck with the "This source has encountered permanent failures" error)

**Comment by meeb** [comment]
No problem. As for your second point, it's likely the public sources were working OK after enough retries and just adding the cookies.txt and restarting this reset the task retry counter so they got indexed again (which then worked). If the playlists are really public the cookies.txt shouldn't do anything so it was likely more just timing and retrying the failure.
