### ISSUE TITLE
Sync tasks not running.

### ISSUE THREAD

**Issue by reefland** [meeb/tubesync#377]
I'm having an issue where scheduled tasks never kick off. I'm using the `latest` image tag.  I'm only getting progress when restart the container and click `Reset Tasks` to get a new index process and download of media to happen.

I show tasks scheduled to run:
![image](https://github.com/meeb/tubesync/assets/16230914/ba9431a2-ee9b-4436-b5e8-f1a93a8e308c)

If I click the first one it shows dates, last run was 3 days ago:
![image](https://github.com/meeb/tubesync/assets/16230914/847bc9e9-1420-463f-9eae-9e148276dcec)

---

When I review the logs, the last entries are from 3 days ago:
```
2023-05-08 10:47:58,335 [tubesync/INFO] Indexed media: trufflesontherocks / zNcRB5EX8-A
2023-05-08 10:47:58,353 [tubesync/INFO] Indexed media: trufflesontherocks / LUynQiTiSNU
2023-05-08 10:47:58,423 [tubesync/INFO] Indexed media: trufflesontherocks / gKNERThkavA
2023-05-08 10:47:58,424 [tubesync/INFO] Deleting completed tasks older than 7 days (run_at before 2023-05-01 14:47:58.424019+00:00)
2023-05-08 10:48:01,827 [tubesync/INFO] Using database connection: django.db.backends.postgresql://tubesync:[hidden]@postgres-rw.cloudnative-pg.svc.cluster.local:5432/tubesync
```

Last entry in the `[ View Completed Tasks] ` screen is from `Task ran at 2023-05-07 22:48:39` -- 4 days ago  when I manually reset tasks because the schedules were not running.

---

Not sure if a list of running processes would be helpful, this is the best I could figure out:

```
root@tubesync-0:/app# ls -l /proc/*/exe 2>/dev/null

lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/15/exe -> /package/admin/s6-2.11.1.2/command/s6-supervise
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/16/exe -> /package/admin/s6-linux-init-1.0.8.0/command/s6-linux-init-shutdownd
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/1/exe -> /package/admin/s6-2.11.1.2/command/s6-svscan
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/24/exe -> /package/admin/s6-2.11.1.2/command/s6-supervise
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/25/exe -> /package/admin/s6-2.11.1.2/command/s6-supervise
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/26/exe -> /package/admin/s6-2.11.1.2/command/s6-supervise
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/27/exe -> /package/admin/s6-2.11.1.2/command/s6-supervise
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/28/exe -> /package/admin/s6-2.11.1.2/command/s6-supervise
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/29/exe -> /package/admin/s6-2.11.1.2/command/s6-supervise
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/30/exe -> /package/admin/s6-2.11.1.2/command/s6-supervise
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/314/exe
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/31/exe -> /package/admin/s6-2.11.1.2/command/s6-supervise
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/323/exe -> /bin/bash
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/338/exe -> /usr/sbin/nginx
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/339/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/340/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/341/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/342/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/343/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/344/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/345/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/346/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/347/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/348/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/349/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/350/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/351/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/352/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/353/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/354/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/355/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/356/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/357/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/358/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/361/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/363/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/374/exe
lrwxrwxrwx 1 app  app  0 May 11 13:50 /proc/392/exe
lrwxrwxrwx 1 root root 0 May 11 13:50 /proc/39/exe -> /package/admin/s6-2.11.1.2/command/s6-ipcserverd
lrwxrwxrwx 1 root root 0 May 11 14:08 /proc/444/exe -> /bin/dash
lrwxrwxrwx 1 root root 0 May 11 14:08 /proc/451/exe -> /bin/dash
lrwxrwxrwx 1 root root 0 May 11 14:08 /proc/452/exe -> /bin/bash
lrwxrwxrwx 1 root root 0 May 11 14:11 /proc/self/exe -> /bin/ls
lrwxrwxrwx 1 root root 0 May 11 14:11 /proc/thread-self/exe -> /bin/ls
```

**Comment by meeb** [comment]
Thanks for the issue. This has been sporadically reported by some other people historically but I could never replicate it to debug it. Are there any issues on the host? Any OOM activity killing tasks?

**Comment by reefland** [comment]
Ah, thanks for the clue.

The Host has 64GB of RAM and the container was given 1.25GiB of RAM, but sure enough I found an OOM kill to the `python3` process in the kernel logs.
```
May 08 14:48:00 k3s06 kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=cri-containerd-bb4fb58f97c7a652be0b42965e596c5f0a984f0a88a48de92f>
May 08 14:48:00 k3s06 kernel: Memory cgroup out of memory: Killed process 559437 (python3) total-vm:928840kB, anon-rss:589244kB, file-rss:23424kB, shmem-rs>
```

As my initial post shows, there was no `python3` process running.

But in the kernel logs, It shows the process before it was killed...
```
May 08 14:48:00 k3s06 kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
May 08 14:48:00 k3s06 kernel: [ 558685] 65535 558685      243        1    28672        0          -998 pause
May 08 14:48:00 k3s06 kernel: [ 558774]     0 558774       52       15    32768        0           989 s6-svscan
May 08 14:48:00 k3s06 kernel: [ 558854]     0 558854       53       16    32768        0           989 s6-supervise
May 08 14:48:00 k3s06 kernel: [ 558855]     0 558855       50        1    28672        0           989 s6-linux-init-s
May 08 14:48:00 k3s06 kernel: [ 558863]     0 558863       53       16    32768        0           989 s6-supervise
May 08 14:48:00 k3s06 kernel: [ 558864]     0 558864       53       16    32768        0           989 s6-supervise
May 08 14:48:00 k3s06 kernel: [ 558865]     0 558865       53       16    32768        0           989 s6-supervise
May 08 14:48:00 k3s06 kernel: [ 558866]     0 558866       53       16    32768        0           989 s6-supervise
May 08 14:48:00 k3s06 kernel: [ 558867]     0 558867       53       16    32768        0           989 s6-supervise
May 08 14:48:00 k3s06 kernel: [ 558868]     0 558868       53       16    32768        0           989 s6-supervise
May 08 14:48:00 k3s06 kernel: [ 558869]     0 558869       53       17    32768        0           989 s6-supervise
May 08 14:48:00 k3s06 kernel: [ 558870]     0 558870       53       16    32768        0           989 s6-supervise
May 08 14:48:00 k3s06 kernel: [ 558878]     0 558878       47        1    28672        0           989 s6-ipcserverd
May 08 14:48:00 k3s06 kernel: [ 559429]  1002 559429     7364     5527    98304        0           989 gunicorn
May 08 14:48:00 k3s06 kernel: [ 559437]  1002 559437   232210   153168  1372160        0           989 python3
...
```
(See last line)

The timestamp of the OOM Kill lines up to the date of last crawl as well.

Do you have anyway to detect the `python3` process is gone, to allow the container to exit and let the restart policy kick in?

**Comment by meeb** [comment]
The tasks should restart but the current task runner is a bit rough and occasionally doesn't. The core issue really is that when channels get indexed all of their metadata is temporarily stored in RAM, and it's a lot, all as JSON which needs to be parsed which can be many megabytes for very large channels which in turn becomes significant amounts of memory usage in Python.

There currently isn't a more sensible way to interface with `yt-dlp` to obtain this information that also allows regular, low effort re-indexing of channels. You could try allocating the container more RAM or pausing indexing on all but one small channel as a test to see if it stabilises. You can likely use container monitoring to see what RAM allocation is being requested before the process gets killed.

**Comment by reefland** [comment]
I bumped the container to 2GiB of RAM and restarted it.  I waited about 10 minutes for the tasks to start since they stated they would start immediately.   Nothing happened .  I then did a task reset which worked.   All tasks ran successfully without an OOM kill.  I'll keep an eye on things to see if they tasks will run on their own.

I noticed that when you use every 24 hours and reset tasks it resets them to all run at the same time which is a problem.  I'll probably have to change each one to be a different numbers of hours so they will not overlap even after a task reset.

**Comment by reefland** [comment]
My description of them "run at the same time" above is probably not correct.  They are set to run about 5 seconds from each other.  I don't know if that means they will overlap or not or if the queue is processed one at a time.

**Comment by meeb** [comment]
Yes while all the tasks are scheduled to run as soon as possible after a reset they are still executed one at a time by the worker. There's no dogpiling or other issues, tasks are still run in a sensible order with a delay to avoid annoying YouTube.

**Comment by reefland** [comment]
Been stable since the RAM limit increase.  Closing issue.
