### ISSUE TITLE
[Request] Ability to set schedule time

### ISSUE THREAD

**Issue by mylogon341** [meeb/tubesync#378]
Currently it just runs from the time a source is setup (+ interval time), but I'd rather they run at a scheduled time in the night to not eat up all my bandwidth during the day.
It wouldn't be compatible with the current "interval" system, but maybe there could be a multi time picker of sorts 🤷‍♂️? 
Something like this 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
with a + button to add another time. Ideally, there'd be an option to "copy to all sources", but I don't know if I'm asking for the world now 😅

**Comment by meeb** [comment]
Thanks for the issue. This looks like a duplicate of the long-running issue #152 - if you agree I'll close it as a dupe. Thanks for the suggestion about using the `time` input type.

**Comment by mylogon341** [comment]
yeah that looks about right. closing.
