### ISSUE TITLE
How can I just download audio?

### ISSUE THREAD

**Issue by savathuntechquestion** [meeb/tubesync#383]
I wanted to say thanks for making this, I was trying to figure out how to just download audio. From the description"All media which only has an audio stream (such as music) will download to the audio directory." but even when I add music to the playlist via YoutubeMusic it will download the static image as well. I really like the ability here to subscribe to channels or even playlists.

**Comment by meeb** [comment]
When you add a new source you can just select "audio only" in the resolution drop-down box.

**Comment by savathuntechquestion** [comment]
Ah thanks, I missed that.
