### ISSUE TITLE
[Feature request] Add Option to download past live streams

### ISSUE THREAD

**Issue by thecreativeone91** [meeb/tubesync#385]
Some channels don't convert their live streams to videos later and therefore never shows up to be indexed by TubeSync it would be awesome if it could have the option to download past live streams (/streams on a channel) in addition to videos. yt-dlp seems to support this. 

Thanks!

**Comment by meeb** [comment]
Thanks for the issue. Is this a dupe of #322 ?

**Comment by thecreativeone91** [comment]
> Thanks for the issue. Is this a dupe of #322 ?

Good catch, yes it is
