### ISSUE TITLE
TypeError -  '<' not supported between instances of 'NoneType' and 'int' when editing or adding source

### ISSUE THREAD

**Issue by dcteal** [meeb/tubesync#387]
Using on Unraid and just updated the application.  Now I'm receiving the below error, with any newly added sources, when clicking on skipped media or editing the source. 

TypeError at /source-update/edf74dc3-0645-4de1-80ac-c4ebe3b596bd
'<' not supported between instances of 'NoneType' and 'int'

[ TubeSync](https://github.com/meeb/tubesync) version 0.12.1
[ yt-dlp](https://github.com/yt-dlp/yt-dlp) version 2023.06.22
[ FFmpeg](https://ffmpeg.org/) version N-111281-g285c7f6f6b-20230627.

**Comment by meeb** [comment]
Please see #386 which this is a dupe of. This should be fixed as of an hour or two ago. Update your container image.

**Comment by dcteal** [comment]
Awesome, thanks!  Sorry for the duplication.
