### ISSUE TITLE
docker image uhealthy [Incorrect timezone setting]

### ISSUE THREAD

**Issue by Anas-glitch** [meeb/tubesync#388]
This is the log:
File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 206, in __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting:  Africa/Cairo
s6-rc: warning: unable to start service tubesync-init: command exited 1

I'm new to Linux so any help is appreciated .
Host system is Ubuntu server 22.04

This is the only docker container in my stack that's throwing me that error.

**Comment by meeb** [comment]
This doesn't make a great deal of sense as `Africa/Cairo` is a valid setting for `TZ`. Try setting `TZ` to just `UTC` to see if that works.

**Comment by Anas-glitch** [comment]
The same error:
  File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 206, in __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting:  UTC

**Comment by meeb** [comment]
What this error means is that the files at `/usr/share/zoneinfo/Africa/Cairo` and `/usr/share/zoneinfo/UTC` don't exist inside the container. They do exist in the container as published in `:latest` so I've no idea what's going on here. Are you running this on a strange architecture? Have you built the container yourself or changed the base image or made any modifications to your install? You could also try pulling down the `:latest` image again.

Also what's the output of this command run on the host:

```bash
docker exec -ti tubesync ls -lat /usr/share/zoneinfo/
```

**Comment by Anas-glitch** [comment]
This is my docker compose block for TubeSync before changing time zone to UTC
  # tube sync - YouTube pvr
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
    ports:
      - "$TUBESYNC_PORT:4848"
    volumes:
      - $DOCKERDIR/tubesync:/config
      - $DATADIR:/downloads
    environment:
      - TZ= $TZ
      - PUID= $PUID
      - PGID= $PGID
      - TUBESYNC_WORKERS= 2
      - TUBESYNC_USER= $TUBESYNC_USER
      - TUBESYNC_PASS= $TUBESYNC_PASS`

**Comment by Anas-glitch** [comment]
here is the output of the command:
drwxr-xr-x  1 root root   4096 Jun 29 13:50 ..
drwxr-xr-x 20 root root   4096 Jun 12 00:00 .
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Africa
drwxr-xr-x  6 root root   4096 Jun 12 00:00 America
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Antarctica
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Arctic
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Asia
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Atlantic
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Australia
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Brazil
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Canada
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Chile
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Etc
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Europe
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Indian
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Mexico
drwxr-xr-x  2 root root   4096 Jun 12 00:00 Pacific
drwxr-xr-x  2 root root   4096 Jun 12 00:00 posix
drwxr-xr-x 18 root root   4096 Jun 12 00:00 right
drwxr-xr-x  2 root root   4096 Jun 12 00:00 US
-rw-r--r--  1 root root   2094 May 28 19:54 CET
-rw-r--r--  1 root root   2310 May 28 19:54 CST6CDT
lrwxrwxrwx  1 root root     14 May 28 19:54 Cuba -> America/Havana
-rw-r--r--  1 root root   1908 May 28 19:54 EET
lrwxrwxrwx  1 root root     12 May 28 19:54 Egypt -> Africa/Cairo
lrwxrwxrwx  1 root root     13 May 28 19:54 Eire -> Europe/Dublin
-rw-r--r--  1 root root    114 May 28 19:54 EST
-rw-r--r--  1 root root   2310 May 28 19:54 EST5EDT
-rw-r--r--  1 root root    116 May 28 19:54 Factory
lrwxrwxrwx  1 root root     13 May 28 19:54 GB -> Europe/London
lrwxrwxrwx  1 root root     13 May 28 19:54 GB-Eire -> Europe/London
lrwxrwxrwx  1 root root      7 May 28 19:54 GMT -> Etc/GMT
lrwxrwxrwx  1 root root      7 May 28 19:54 GMT+0 -> Etc/GMT
lrwxrwxrwx  1 root root      7 May 28 19:54 GMT-0 -> Etc/GMT
lrwxrwxrwx  1 root root      7 May 28 19:54 GMT0 -> Etc/GMT
lrwxrwxrwx  1 root root      7 May 28 19:54 Greenwich -> Etc/GMT
lrwxrwxrwx  1 root root     14 May 28 19:54 Hongkong -> Asia/Hong_Kong
-rw-r--r--  1 root root    115 May 28 19:54 HST
lrwxrwxrwx  1 root root     14 May 28 19:54 Iceland -> Africa/Abidjan
lrwxrwxrwx  1 root root     11 May 28 19:54 Iran -> Asia/Tehran
lrwxrwxrwx  1 root root     14 May 28 19:54 Israel -> Asia/Jerusalem
lrwxrwxrwx  1 root root     15 May 28 19:54 Jamaica -> America/Jamaica
lrwxrwxrwx  1 root root     10 May 28 19:54 Japan -> Asia/Tokyo
lrwxrwxrwx  1 root root     17 May 28 19:54 Kwajalein -> Pacific/Kwajalein
lrwxrwxrwx  1 root root     14 May 28 19:54 Libya -> Africa/Tripoli
lrwxrwxrwx  1 root root     14 May 28 19:54 localtime -> /etc/localtime
-rw-r--r--  1 root root   2094 May 28 19:54 MET
-rw-r--r--  1 root root    114 May 28 19:54 MST
-rw-r--r--  1 root root   2310 May 28 19:54 MST7MDT
lrwxrwxrwx  1 root root     14 May 28 19:54 Navajo -> America/Denver
lrwxrwxrwx  1 root root     16 May 28 19:54 NZ -> Pacific/Auckland
lrwxrwxrwx  1 root root     15 May 28 19:54 NZ-CHAT -> Pacific/Chatham
lrwxrwxrwx  1 root root     13 May 28 19:54 Poland -> Europe/Warsaw
lrwxrwxrwx  1 root root     13 May 28 19:54 Portugal -> Europe/Lisbon
lrwxrwxrwx  1 root root     16 May 28 19:54 posixrules -> America/New_York
lrwxrwxrwx  1 root root     13 May 28 19:54 PRC -> Asia/Shanghai
-rw-r--r--  1 root root   2310 May 28 19:54 PST8PDT
lrwxrwxrwx  1 root root     11 May 28 19:54 ROC -> Asia/Taipei
lrwxrwxrwx  1 root root     10 May 28 19:54 ROK -> Asia/Seoul
lrwxrwxrwx  1 root root     14 May 28 19:54 Singapore -> Asia/Singapore
lrwxrwxrwx  1 root root     15 May 28 19:54 Turkey -> Europe/Istanbul
-rw-r--r--  1 root root 116211 May 28 19:54 tzdata.zi
lrwxrwxrwx  1 root root      7 May 28 19:54 UCT -> Etc/UTC
lrwxrwxrwx  1 root root      7 May 28 19:54 Universal -> Etc/UTC
lrwxrwxrwx  1 root root      7 May 28 19:54 UTC -> Etc/UTC
-rw-r--r--  1 root root   1905 May 28 19:54 WET
lrwxrwxrwx  1 root root     13 May 28 19:54 W-SU -> Europe/Moscow
lrwxrwxrwx  1 root root      7 May 28 19:54 Zulu -> Etc/UTC
-rw-r--r--  1 root root  17551 Jan 23 20:46 zone1970.tab
-rw-r--r--  1 root root  18855 Jan 23 20:46 zone.tab
-rw-r--r--  1 root root   3392 Jan 20 22:45 leapseconds
-rw-r--r--  1 root root  10666 Jan 20 22:45 leap-seconds.list
-rw-r--r--  1 root root   4446 Jan  7 21:09 iso3166.tab

**Comment by meeb** [comment]
That looks fine. This is the code in Django that's raising the error:

```python
            zoneinfo_root = Path('/usr/share/zoneinfo')
            zone_info_file = zoneinfo_root.joinpath(*self.TIME_ZONE.split('/'))
            if zoneinfo_root.exists() and not zone_info_file.exists():
                raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
```

Effectively this isn't a tubesync issue, it's an issue with the Django framework and Python. Somehow a check of "does the file `/usr/share/zoneinfo/Africa/Cairo` exist" is returning a `False` with your deployment. I'm mostly out of ideas as to why this could occur.

What architecture are you running on and have you made any modifications to the container?

**Comment by Anas-glitch** [comment]
> Oh and what's `TZ` set to in your `.env`?

It was in the error!
**Africa/Cairo**

If what you mean by architecture is OS then I already mentioned it on OP
**Host system is Ubuntu server 22.04**

**Comment by Anas-glitch** [comment]
I removed the container and image the re-pulled again same problem.

**Comment by meeb** [comment]
Architecture is AMD64 or ARMHF etc.

**Comment by Anas-glitch** [comment]
Oh...
Its AMD64

**Comment by meeb** [comment]
Honestly then I have no idea, this is a completely new and weird error to me. If you've made no modifications inside the container and not built the container yourself this error makes basically zero sense. What does this command output?

```bash
docker exec -ti --user app tubesync ls -lat /usr/share/zoneinfo/Africa/Cairo
```

**Comment by Anas-glitch** [comment]
-rw-r--r-- 1 root root 2399 May 28 19:54 /usr/share/zoneinfo/Africa/Cairo

**Comment by meeb** [comment]
OK, last try, what does this command output:

```python
docker exec -ti --user app tubesync python3 -c "import pathlib; r = pathlib.Path('/usr/share/zoneinfo'); f = r / 'Africa' / 'Cairo'; print(f'root: {r.exists()}'); print(f'file: {f.exists()}')"
```

**Comment by Anas-glitch** [comment]
root: True
file: True

**Comment by meeb** [comment]
OK, so, the exact same Python code that Django uses when run as the same user account works fine, but not on container start-up? Still seems completely bizarre to me. What are your `PUID` and `PGID` set to?

**Comment by Anas-glitch** [comment]
1000
1000

**Comment by meeb** [comment]
I'm out of ideas, sorry. As I mentioned above this specifically isn't an issue with tubesync really. All the `init` command does thats failing is call `migrate` in Django, and the start-up settings checks for Django are what's failing and failing with a totally weird error that makes no sense and apparently can't be debugged as it all works perfectly later. I can only guess that there's something weird with the host filesystem or how something is installed on the host? But even that seems like a stretch. Sorry, I don't think I can assist further here.

**Comment by meeb** [comment]
Yeah you don't want to be doing that, run containers as your user. You're probably on the right path though it's going to be something weird with permissions, or at a push something crazy like your `/` in `Africa/Cairo` in your `.env` isn't actually a `/` but a unicode char that looks like a `/`.

**Comment by Anas-glitch** [comment]
I discovered the issue!!
It was the space between TZ= $TZ  🤣😢😒
the strange thing is that doesn't throw any errors except in django.

**Comment by meeb** [comment]
Yep that would do it.
