### ISSUE TITLE
[Feature Request] Native Windows Support

### ISSUE THREAD

**Issue by Yankees4life** [meeb/tubesync#390]
Hello there 

This app is pretty nice. I would like a native windows app for this tho as having to use docker/wsl2 for this would not be fun for my laptop. Right now, I'm just using ytdlg and ytdlnfo in tandem to grab YouTube videos on windows. Cheers

**Comment by meeb** [comment]
Hi, thanks for the issue. Unfortunately there's an almost zero percent chance I'm going to port this web app and container to be a native windows app. It would likely be easier to completely rebuild it from scratch than port it and even then it would be extremely complicated given the dependencies and operation.

**Comment by meeb** [comment]
I'll close this for now. It can be re-opened if by some miraculous occurrence there is ever any development on a native desktop version.
