### ISSUE TITLE
can not use soocks5 proxy

### ISSUE THREAD

**Issue by lkw199711** [meeb/tubesync#391]
I use docker-compose to deploy images. set proxy option.

all_proxy: socks5://192.168.2.2:7891

In other container, they can work. but in tubesync ,they can't.
![image](https://github.com/meeb/tubesync/assets/38646029/259f40a7-aeee-4a89-8211-80cdb7422828)

When i add a CHANNEL, task error "No metadata was returned by youtube-dl ..."
When i add a PLAYLIST, Can get video information, but cannot download. task error "Missing dependencies for SOCKS support."

tubesync is a good tool that perfectly meets my needs. but i cannot directly access YouTube. 
Need help, thank you.

**Comment by meeb** [comment]
`socks5://` support is not yet available in `yt-dlp`. It appears to will be at some point and is being actively worked on, upstream issues:

https://github.com/yt-dlp/yt-dlp/issues/6325
https://github.com/yt-dlp/yt-dlp/pull/2861

Once it gets added as a feature to `yt-dlp` it'll be available in tubesync. This isn't really a tubesync issue.

**Comment by lkw199711** [comment]
Ok, thanks, i know it

**Comment by coletdjnz** [comment]
that error isn't from yt-dlp (yt-dlp already has socks5 support built-in).

Somewhere something is making a request through a library such as requests and the socks dependency for that is not installed.

**Comment by meeb** [comment]
Ah so it is, thanks. I'll check what the upstream libraries are trying to load. Cheers.

**Comment by meeb** [comment]
Indeed it was, thanks for the tip @coletdjnz I misread where the error was coming from. Adding `requests[socks]` as a package should fix this. @lkw199711 wait for `:latest` to build then try that.
