### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by alexissersh** [meeb/tubesync#392]
After the update, docker fell down Errors.

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 286, in download_media_thumbnail
    i = resize_image_to_height(i, width, height)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/utils.py", line 81, in resize_image_to_height
    image = image.resize((scaled_width, height), Image.ANTIALIAS)
                                                 ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by wallsy1703** [comment]
The following worked for me....

locate the file app/sync/utils.py

change line 81 from

image = image.resize((scaled_width, height), Image.ANTIALIAS)

to

image = image.resize((scaled_width, height), Image.LANCZOS)


Solution was taken from the following (for reference and explanation of the cause of issue)

https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias

Hope this helps

**Comment by meeb** [comment]
Cheers, seems I didn't have test coverage for the thumbnail resizing. The latest commit will fix this, and thanks for the additional research and notes @wallsy1703.

**Comment by alexissersh** [comment]
Thank you for your help!
