### ISSUE TITLE
"Delete old media" ignored, media redownloaded after indexing source even though before it was deleted

### ISSUE THREAD

**Issue by DavidLJz** [meeb/tubesync#394]
Maybe I fail to understand how the "Delete old media" feature works, but when re-indexing media with the button in the Source listing, media is being downloaded again after it was automatically deleted.

I thought media older than N days should be ignored in future re-indexing and download of media.

**Comment by meeb** [comment]
When you re-index a source it'll use the download cap, you'll probably need to set both the delete old media flag and the download cap to cover your use case.

**Comment by DavidLJz** [comment]
So, as long as I set the DAYS TO KEEP flag to be more than or equal to the DOWNLOAD CAP in days I should be fine, and the media will not be downloaded again, is that correct?

I will try this soon

**Comment by DavidLJz** [comment]
Problem persists after changing the download cap to be 7 and days to keep as 8. Concretely, TubeSync downloads Media when it can't find files after indexing the source or modifying Source settings, **even if it is way older than the Download Cap**.

I checked the code and if I'm not mistaken here is where the actual flag checking takes place right before downloading media:

https://github.com/meeb/tubesync/blob/63d32a1e11403fb7bd0c41df5595bb347731dcc7/tubesync/sync/signals.py#L95-L194

In line 128 it sets the media to be skipped if its published date is too old, but it only does this when the media has not already been marked as `downloaded`, so its not very useful since it will just keep doing it again.

Hopefully I can come back to this later.

**Comment by meeb** [comment]
I'm not sure I entirely get your point, if the media item is already downloaded why would you want it checked against the download cap which is to check new downloads? There probably are gaps in the download checks and cap logic though.

**Comment by meeb** [comment]
This should have been fixed for a while. Feel free to create an new issue if you still experience this behavior.
