### ISSUE TITLE
Is it possible to update yt-dlp or do we have to wait for a new version of tubesync

### ISSUE THREAD

**Issue by jcvold** [meeb/tubesync#399]
I, like a a lot of folks (according to reddit), are having issues all of a sudden with downloads. The fix seems to be to update yt-dlp but I'm not sure if that can be done manually or do we need to wait for a new version of tubesync to incorporate that newer version?

**Comment by meeb** [comment]
It's particularly practical to update yt-dlp yourself as it's bundled into the container. I can push a new update release for you though.

**Comment by meeb** [comment]
Wait for `:latest` to build then pull that image, it will have the latest up to date `yt-dlp` and `ffmpeg` bundled into it.
