### ISSUE TITLE
Feature Request: Delete videos that have been removed from a list

### ISSUE THREAD

**Issue by frob** [meeb/tubesync#400]
It would be nice if I could delete the video from my playlist and have it be removed from my media library as well.

This would be an alternative to the Download Cap and the Delete after Days feature.

**Comment by tcely** [comment]
This currently exists with two options: 1) delete the video from tubesync and/or 2) delete the media file from the disk.

I think this issue can be closed now.

**Comment by meeb** [comment]
Yep seems resolved.
