### ISSUE TITLE
Watch Later playlist no longer accessible

### ISSUE THREAD

**Issue by ShadowfootNZ** [meeb/tubesync#413]
I've been able to use my Watch Later playlist to get individual videos downloaded until recently. I realised it's been failing for a few days now, so I've made sure to be up to date with everything I can. 

- TubeSync version 0.13.0 
- yt-dlp version 2023.09.24 
- FFmpeg version N-112171-g13a3e2a9b4-20230924 (I need to figure out where I verify this is the latest.) 

I recreated my cookies.txt and it looks like it's working correctly. It's been automatically updated and includes
```# This file is generated by yt-dlp.  Do not edit.```

I deleted and recreated the source. 

The error I get is the Watch Later playlist is not accessible anymore. 
```
2023-09-27 16:07:28,600 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-09-27 16:07:28,687 [tubesync/DEBUG] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=WL
2023-09-27 16:07:28,687 [tubesync/DEBUG] [youtube:tab] WL: Downloading webpage
2023-09-27 16:07:29,229 [tubesync/WARNING] [youtube:tab] YouTube said: The playlist does not exist.
2023-09-27 16:07:29,244 [tubesync/ERROR] ERROR: [youtube:tab] WL: YouTube said: The playlist does not exist.
Rescheduling Index media from source "Watch Later"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 159, in index_source_task
    videos = source.index_media()
             ^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/models.py", line 542, in index_media
    response = indexer(self.index_url)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/playlist?list=WL": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Index media from source "Watch Later" for 4:04:06 later at 2023-09-27 07:11:35.260689+00:00
```
I haven't made modifications to YouTube regarding permission, and I don't think I made any changes previously.  

I added a new playlist; it's downloading successfully, with no errors about cookies.txt, but this playlist is public and would download without cookies.txt.
```
2023-09-27 16:28:28,471 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-09-27 16:28:28,510 [tubesync/DEBUG] [youtube] Extracting URL: https://www.youtube.com/watch?v=GpRDVk4ALqI
2023-09-27 16:28:28,510 [tubesync/DEBUG] [youtube] GpRDVk4ALqI: Downloading webpage
```

What else can I check? Do I need to do something new for the Watch Later playlist (and other private playlists)?

**Comment by meeb** [comment]
That error is effectively `yt-dlp` failed to access your private playlist. Have you tried refreshing your cookies.txt file with new cookies?

**Comment by ShadowfootNZ** [comment]
Yep, I went through the process to export the cookies in Netscape format. 
I've just repeated that process. I see the contents have changed and it includes the line about being generated by yt_dlp. 
I used this plugin to get the cookies in the right format: https://addons.mozilla.org/en-US/firefox/addon/export-cookies-txt/
I suspect I used the same plugin previously when it worked.

**Comment by meeb** [comment]
You can test what `yt-dlp` is doing in the container shell, try something like:

```bash
$ docker exec -ti tubesync bash
```

Then in the container shell you can use `yt-dlp` with your cookies off the command line:

```bash
$ yt-dlp --flat-playlist --simulate --cookies /config/cookies.txt "https://www.youtube.com/playlist?list=WL"
```

See what that returns.

**Comment by ShadowfootNZ** [comment]
I get the following:
```
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=WL
[youtube:tab] WL: Downloading webpage
WARNING: [youtube:tab] YouTube said: The playlist does not exist.
ERROR: [youtube:tab] WL: YouTube said: The playlist does not exist.
```
This indicates to me that it's not a tubesync problem, but is a yt-dlp problem. This probably is to do with how the cookies file is used, which might be due to a change by YouTube.

**Comment by meeb** [comment]
Does `https://www.youtube.com/playlist?list=WL` work in your browser? And yes if this doesn't work in bare `yt-dlp` that's likely to be the issue rather than TubeSync. Get the above command to work and it'll start working again in TubeSync.

**Comment by ShadowfootNZ** [comment]
Yes, it's from the browser I grabbed it when recreating details. 
I'll try investigating if others in yt-dlp have encountered a similar problem. Thanks.

**Comment by IIIdefconIII** [comment]
im also fighting this error: No metadata was returned by youtube-dl

**Comment by meeb** [comment]
@IIIdefconIII This may have been `yt-dlp` needing an update. Try the latest v0.13.2 build.

**Comment by IIIdefconIII** [comment]
> @IIIdefconIII This may have been `yt-dlp` needing an update. Try the latest v0.13.2 build.

thanks, im on :latest so i should be ok

**Comment by ShadowfootNZ** [comment]
I'm adding this comment in case anyone else encounters this. I continued to have this problem. I once again downloaded a new cookies file, but this time, I used a different Firefox extension to do so.  After yt-dlp modified the file, I could see 19 cookies. The other extension resulted in only 8 cookies. 

27 items are now downloading. 

After downloading the current batch, the error occurred again, and cookies.txt has been updated to have only 10 items. The problem seems to be with what yt-dlp does updating cookies.txt. I refreshed cookies.txt but it's 2.5 hours before tubesync will attempt another check.

**Comment by meeb** [comment]
Thanks for the feedback @ShadowfootNZ - that sounds like it might be a yt-dlp issue as all tubesync does is pass the path to the cookies.txt file to yt-dlp and that's about it, so any rewriting / updating of the cookies is done inside of yt-dlp (and, from past checking, usually completely normal and required).

Obviously I'll update yt-dlp as and when they release new versions so if there's anything that gets patched it'll get updated in tubesync as well. yt-dlp does all the work, after all, given tubesync is basically a web UI wrapper and media manager around yt-dlp.
