### ISSUE TITLE
[Question/Request] Is there a way to set the time for the sync tasks?

### ISSUE THREAD

**Issue by TheWicklowWolf** [meeb/tubesync#419]
How can I specify a time for the sync tasks to start at? e.g. sync at 05:00 every day...

Also is there anyway to create/edit a source without triggering an immediate sync? Would like to create multiple sources and then have the scan/sync initiated later... 

Thanks, great app by the way.

**Comment by meeb** [comment]
Currently there isn't, sorry. This requires a rebuild of the tasks system.

**Comment by TheWicklowWolf** [comment]
> Currently there isn't, sorry. This requires a rebuild of the tasks system.

Is that for both questions?

Thanks anyway

**Comment by meeb** [comment]
Yes, no to both, sorry. They are both on the long term plan and have open issues from a while back though.

**Comment by TheWicklowWolf** [comment]
Thanks for update!
