### ISSUE TITLE
Skip videos whose titles don't match a regex string pattern

### ISSUE THREAD

**Issue by locke4** [meeb/tubesync#424]
This is a feature request for the skip flag to be set if a video title does not match a user-specified regex pattern.

I want to add a channel whose videos titles are prefixed with the topic. I'm only interested in downloading those specific videos. This feature would allow me to filter the downloaded videos. I'm working on a fork to add this support which seems to be working but I need to write tests for. Once it has a suitable test in tests.py, I'll submit a PR for review by a maintainer and reference this feature request.

**Comment by meeb** [comment]
Sounds like a reasonable addition, happy to review the PR once you're ready.

**Comment by perry-mitchell** [comment]
@meeb @locke4 Can this be closed? I can see it in the UI now.

**Comment by meeb** [comment]
Yep!
