### ISSUE TITLE
Tubesync does not support other video platforms (Odysse, rumble, Instagram...)

### ISSUE THREAD

**Issue by Roger7890** [meeb/tubesync#433]
Hello, thank you for this project, but tubesync only supports YouTube but not other platforms (Odysse, rumble, Instagram...).  While yt-dlp supports a lot of websites https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

 I know that tubesync uses yt-dlp, so it shouldn't be a problem to make it compatible with other platforms!

 Is this a working feature?  When do you plan to implement this feature?

**Comment by meeb** [comment]
It is not a working feature right now. It is indeed possible but not currently on my task list for the current version.

**Comment by Roger7890** [comment]
This is a very important feature, I hope you will work on a possibility to integrate all other video platforms soon!

**Comment by meeb** [comment]
Happy to accept feature pull requests if you want to contribute to the project.
