### ISSUE TITLE
Manual indexing works but task-indexing fails. Indexed channels create tasks for thumbnails to be downloaded but not videos. 

### ISSUE THREAD

**Issue by xusiai** [meeb/tubesync#436]
Hi,

Most of the sources I have specified either fail to index media (3/15 channels) or download video content (9/15 channels). The remaining 3 work as expected. 

I am using Docker for this and the container seem to be able to index channels that tubesync fail to e.g running: 

```
docker exec -ti tubesync python3 /app/manage.py youtube-dl-info "https://www.youtube.com/ChannelThatFailedIndexing"` 
```

return json data rather than an error. However the tubesync docker logs show 404 for the same channel: 

```
2023-11-20 14:42:12,227 [tubesync/DEBUG] [youtube:tab] @ChannelThatFailedIndexing/videos: Downloading API parameters API JSON
2023-11-20 14:42:12,256 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
```

Since I can index the channel with docker exec the IP should not be blocked but tubesync seem unable to reach it?

For the indexed channels that do not download videos there are no queued tasks - all related tasks are finished (thumbnails _are_ downloaded for these channels). I have tried running reset tasks but no new tasks are added - even after waiting several hours. 

What could be causing these issues? Any suggestions for further troubleshooting?

**Comment by meeb** [comment]
Likely you've found a channel that has an aliased URL. Try putting the channel into a tool like https://www.streamweasels.com/tools/youtube-channel-id-and-user-id-convertor/ then "add channel by ID" and use the channel ID from the tool.

**Comment by xusiai** [comment]
> Likely you've found a channel that has an aliased URL. Try putting the channel into a tool like https://www.streamweasels.com/tools/youtube-channel-id-and-user-id-convertor/ then "add channel by ID" and use the channel ID from the tool.

Looks like this could be it. Tried it on one of them so far and it started downloading. Thanks!
