### ISSUE TITLE
New items refuse to download because item 'has no published date'

### ISSUE THREAD

**Issue by StarrrLiteNL** [meeb/tubesync#442]
My setup has been working perfectly for months, but since a couple of days I am getting the following error for every single item in my download queue: 
`
Media: YouTube download playlist / AAAHBt40r3M has no published date, marking to be skipped
Media: YouTube download playlist / xrOO7ruBq-I has no published date, marking to be skipped
Media: YouTube download playlist / tBbbHXq6B-Q has no published date, marking to be skipped
`

I can go to the video on youtube and play these video's fine without issues.

I have tried removing them from the database and doing a task reset, but all the latest items added to the playlist are giving the same result.

I am running:
TubeSync version 0.13.2 
yt-dlpversion 2023.11.16  
FFmpeg version N-112750-g6d60cc7baf-20231114

Is this a known issue, and are there workarounds for it?

**Comment by meeb** [comment]
Please update to 0.13.3 released today, this should be resolved.

**Comment by StarrrLiteNL** [comment]
Thanks for the fast response.
I did check the changelog and found nothing that pointed to this being an issue, so I figured this would not have solved it. 

I will update and reset the tasks 👍

**Comment by meeb** [comment]
See https://github.com/meeb/tubesync/issues/440 for the dupe issue on this with related commits etc.

Auto-changelogs only have PRs in, not direct commits from project maintainers.

**Comment by StarrrLiteNL** [comment]
I see, I only searched on 'has no published date', and no on the 'Media skipped by system(1)' error, so it did not show up.

btw: Is there a way via the GUI to force a redownload of these items? I don't see any option, and since they are marked as 'skipped', tubesync won't try to redownload them.

I can remove them from the sqlite database, but that seems a bit of a user unfriendly hack

**Comment by StarrrLiteNL** [comment]
That seems to have done the trick. 👍😀
