### ISSUE TITLE
Delete removed media option not working

### ISSUE THREAD

**Issue by nlibby987** [meeb/tubesync#456]
I have a playlist added and set to sync to my library, I have enabled the delete removed media option checked under the assumption that if I delete a video file from my playlist it will remove it from the app and remove it from my library. 

It does not seem to be working as i expect it to, is there anything i need to do? or is this a bug?

**Comment by meeb** [comment]
It's a sort of bug, there's a PR under review to resolve this already.

**Comment by nlibby987** [comment]
Ahh I was reading that but I am not educated on how a lot of this works on the development side of things so I was not sure that was the same issue, thanks for letting me know, can't wait for it to be working as that is a feature that i have been looking for in youtube downloading software for sometime.

I maintain a playlist for my niece that has special needs and she loves music but sometimes gets board of some songs, being able to just add and remove music from a youtube playlist that will just add and remove in the background from my plex library is perfect for this, Can't wait for this to be working!! the rest of the software is pretty solid!

**Comment by meeb** [comment]
Closed by #450
