### ISSUE TITLE
All video downloads stalled

### ISSUE THREAD

**Issue by arionl** [meeb/tubesync#459]
TubeSync is getting stuck trying to download video files. This started happening right around the holidays. All indexing tasks and tasks related to metadata (downloading descriptions, thumbnails, etc.) seem to work fine. However, downloads of actual media files all get stuck.

My configuration:
* TubeSync version 0.13.3 with [ yt-dlp](https://github.com/yt-dlp/yt-dlp) version 2023.11.16 and [ FFmpeg](https://ffmpeg.org/) version N-112875-g47e214245b-20231129.
* Running via `docker compose`
* Using Postgres database backend (launched by the same docker compose file)
* `/config` and `/downloads` mapped into the container from the host filesystem

For example, here is a log entry showing that a video is attempting to be downloaded:
`tubesync       | 2024-01-13 05:05:27,844 [tubesync/INFO] Downloading media: YulgDAaHBKw (UUID: 0c5a714a-3b87-4d1a-b890-88abc21bbd17) to: "/downloads/video/art-of-the-problem-deep-learning/Art of the Problem: Deep Learning - 2019-05-17 - [YulgDAaHBKw] - 1080p.mkv"`

On my filesystem, I can see that the file was created, it just that no data is being downloaded and the file is 0 bytes:

<code>$ ls -al /downloads/video/art-of-the-problem-deep-learning/
total 381
drwxr-xr-x  2 1000 1000     10 Jan 13 00:05  .
drwxr-xr-x 19 1000 1000     19 Dec 28 20:41  ..
-rwxr-xr-x  1 1000 1000      0 Dec 30 22:49 'Art of the Problem: Deep Learning - 2019-05-17 - [YulgDAaHBKw] - 1080p.f137.mp4.part'
-rw-r--r--  1 1000 1000 402462 Jan 13 00:05 'Art of the Problem: Deep Learning - 2019-05-17 - [YulgDAaHBKw] - 1080p.info.json'
[ ... ]
</code>

TubeSync shows the task as "Downloading" and the state never changes. TubeSync has been working fine for more than a year or so prior to this issue. I can launch a shell inside of the Docker container and use `/usr/local/bin/yt-dlp` to download the same media manually without any issues.

I've tried all of the normal quick-fixes (`docker compose exec tubesync /usr/bin/python3 ./manage.py reset-tasks`, etc.) but it always returns to this state where downloading is stuck.

I'm not too familiar with Django. Any pointers on how I can troubleshoot this issue further? Thanks!

**Comment by meeb** [comment]
Anything else in the logs below the "Downloading media:" line? Looks like the download process is starting, but hanging. `.part` files are created by `yt-dlp` so the download process is starting. Anything in the logs on the host? OOM errors and the worker being killed or something?

**Comment by arionl** [comment]
> Anything else in the logs below the "Downloading media:" line? Looks like the download process is starting, but hanging. `.part` files are created by `yt-dlp` so the download process is starting. Anything in the logs on the host? OOM errors and the worker being killed or something?

That's the last log entry I see that has the YouTube video ID in it. I don't see any messages after that log event related to memory, workers, etc. In my `docker-compose.yml` I have `TUBESYNC_WORKERS=4` and `TUBESYNC_DEBUG=True`. Right now, there are 4 downloads which are all stuck. All of the downloads happen to be from the same channel, but I've `reset-tasks` a bunch of times and removed/added some channels to see if this is related to a specific channel/video/playlist. Doesn't seem to be. I also tried removing `config/cache` and `config/media` directories to see if that would have any effect.

From the logs events, it shows that this file is going to be created: `/downloads/video/art-of-the-problem-deep-learning/Art of the Problem: Deep Learning - 2019-05-17 - [YulgDAaHBKw] - 1080p.mkv`. However, the first file being downloaded is `Art of the Problem: Deep Learning - 2019-05-17 - [YulgDAaHBKw] - 1080p.f137.mp4.part`. I assume this is because `yt-dlp` is downloading the components and will remux them into the MKV file after they are all done? Or does TubeSync do that step? I don't see any `yt-dlp` processes actually running.. and from poking at the code, that's because you are using the library not the actual Linux binary I believe..

The only thing I haven't tried yet is completely blowing away my Postgres database and starting from scratch. I'm hoping it doesn't come to that because I have ~10 or so channels/playlists I'm tracking and it would kinda suck to recreate them all. Let me know if there's anything else I should poke at. Thanks for your help in troubleshooting!

**Comment by meeb** [comment]
Ah, that's probably multiple workers causing it. I should probably remove that option. Set `TUBESYNC_WORKERS` back to `1`, stop the container, change your external IP if you can and try again. If you can't change your IP you might need to wait a day or two before trying again.

What's likely happening here is you're trying multiple concurrent downloads from YouTube and they've heavily rate limited or blocked your IP. Historically it worked with multiple workers, however YouTube now just blocks you if you try and "watch" more than one video at once most of the time. The `TUBESYNC_WORKERS` his a legacy setting now and should generally always be `1`.

TubeSync doesn't do the remuxing into the MKV container, that's all `yt-dlp` (which in turn uses ffmpeg). Your logs show that `yt-dlp` is being called and then it's just hanging.

**Comment by arionl** [comment]
> Ah, that's probably multiple workers causing it. I should probably remove that option. Set `TUBESYNC_WORKERS` back to `1`, stop the container, change your external IP if you can and try again. If you can't change your IP you might need to wait a day or two before trying again.

I originally didn't have this environmental variable set -- I was using the default which I believe was just 1 worker. I changed it to 4 as part of all of this troubleshooting to see if it would help. 
 
> What's likely happening here is you're trying multiple concurrent downloads from YouTube and they've heavily rate limited or blocked your IP. Historically it worked with multiple workers, however YouTube now just blocks you if you try and "watch" more than one video at once most of the time. The `TUBESYNC_WORKERS` his a legacy setting now and should generally always be `1`.

Ok, I stopped the containers, deleted all of the `*.part` files, and explicitly set `TUBESYNC_WORKS=1`. When I started TubeSync back up, it showed 32 tasks scheduled, and 29 of them as "Downloading media" with "Task will run immediately".  None of them were actively running. I issued another `reset-tasks` and that kicked off a download for the first video in the queue, but it looks like it's stuck again with 0 bytes downloaded. Anything else you can think for me to try? Should I start putting some more debug stuff in [youtube.py](https://github.com/meeb/tubesync/blob/main/tubesync/sync/youtube.py) to try to catch that may be going on?

**Comment by meeb** [comment]
Sure, more debug stuff would help. As far as TubeSync is concerned it's just calling `yt-dlp` over the API which is then hanging so it'll likely be up to debugging why it's not downloading rather than anything in the TubeSync wrapper itself. I'm assume you've checked all the obvious stuff like disk space, inodes limits etc.

**Comment by arionl** [comment]
Any hints on what I should add to `sync/youtube.py` to troubleshoot? I'm a Django newbie and my Python skills are pretty rusty. I don't have a proper dev environment for this, so right now I'm just hacking on the code directly in the container to try to at least understand what may be happening. From the main `yt-dlp` project, I saw that you can [define a custom logger](https://github.com/yt-dlp/yt-dlp/tree/8e6e3651727b0b85764857fc6329fe5e0a3f00de#adding-logger-and-progress-hook). I tried that, but so far it isn't capturing/displaying any events..

**Comment by arionl** [comment]
Still troubleshooting. A couple of updates: I built a simple `test.py` script based on `sync/youtube.py` to manually download a video from within the container runtime and it seemed to work OK ([test.py.txt](https://github.com/meeb/tubesync/files/13958415/test.py.txt)). I then updated the `MyLogger()` in `sync/youtube.py` to output to a file like I did in my test script and when TubeSync tries to download a video, it looks like this now:

Main TubeSync log:
`tubesync  | 2024-01-17 03:52:38,284 [tubesync/INFO] Downloading media: 9C4ispSViPE (UUID: c96d2d56-8a27-4a4c-bc44-546bec063445) to: "/downloads/video/mcmlintockmashups/2024-01-12_mcclintockmashups_korn-in-a-can-still-coming-undone_9C4ispSViPE_720p-vp09-opus.mkv"`


MyLogger() log:
```
DEBUG:root:[youtube] Extracting URL: https://www.youtube.com/watch?v=9C4ispSViPE
DEBUG:root:[youtube] 9C4ispSViPE: Downloading webpage
DEBUG:root:[youtube] 9C4ispSViPE: Downloading ios player API JSON
DEBUG:root:[youtube] 9C4ispSViPE: Downloading android player API JSON
DEBUG:root:[youtube] 9C4ispSViPE: Downloading m3u8 information
DEBUG:root:[info] 9C4ispSViPE: Downloading 1 format(s): 247+251
DEBUG:background_task.management.commands.process_tasks:waiting for tasks
DEBUG:background_task.management.commands.process_tasks:waiting for tasks
DEBUG:background_task.management.commands.process_tasks:waiting for tasks
DEBUG:background_task.management.commands.process_tasks:waiting for tasks
```

The last line seems to repeat forever.. I'll keep poking at this I guess..

**Comment by arionl** [comment]
Quick update. I think I have isolated the problem. It seems to be related to the fact that I'm using a Docker volume mount for `/downloads` that is a NFS share on the host OS. I've had it set up this way since I started using TubeSync and everything ran fine. Also, as shown above, when things broke, TubeSync was still able to write some files (like the `.info.json` files) successfully. Anyway, something must have changed either in Docker, my host OS (Ubuntu version bumped to latest LTS), or the version of `yt-dlp`. I did some searching and there have been a few historical tickets in the `yt-dlp` project that mention NFS locking issues when downloading. If I can identify the exact issue, I'll update.. and regardless, I'll close this ticket soon.

**Comment by meeb** [comment]
Excellent, thanks for the update! I'll pull in any upstream `yt-dlp` fixes if there are any for this issue automatically so hopefully it'll eventually resolve itself for you.

**Comment by arionl** [comment]
I'm still not 100% sure what specific change broke things (Docker version? Ubuntu version? yt-dlp version?) that were working before, but I've got a solid work-around for now. Instead of using a host-mount NFS path, I'm now explicitly mounting my NFS server inside off the container.

So, instead of this in my `docker-compose.yml`:

```
[ ... snip ... ]
    volumes:
      - ./config:/config
      - /mnt/nfs-mounted-on-host:/downloads
[ ... snip ... ]
```
I'm doing this:
```
[ ... snip ... ]
    volumes:
      - ./config:/config
      - type: volume
        source: myvolume
        target: /downloads
        volume:
          nocopy: true
[ ... snip ... ]
volumes:
  myvolume:
    driver_opts:
      type: "nfs"
      o: "addr=my.home.nfs.server,nolock,soft,rw"
      device: ":/path/on/nfs/server/videos/YouTube"
[ ... snip ... ]
```

So far so good. Likely the addition of `nolock` is helping, since I don't have this option on my host mounted NFS volume (although everything else works fine). Anyway, I'll close this ticket out and hopefully anyone else that stumbles upon this problem can use the same work-around.

**Comment by meeb** [comment]
Thanks for the detailed write-up! I'm sure it'll be useful for others.
