### ISSUE TITLE
Incorrect Time

### ISSUE THREAD

**Issue by devanteweary** [meeb/tubesync#462]
Hey there. Loving the app!
Using it on Unraid as a Docker container.

So I read the documentation and as the container template doesn't have the TZ variable already added, I created it and set it to both "America/Los_Angeles" and "PST8PDT" when I was trying it out.

However, the task times show up as UTC time still.
Just in case, I checked the appdata folder for any .env files but there are none so I assume it's all set in the container template.

Should I be setting the timezone somewhere else?

Thank you!

**Comment by devanteweary** [comment]
> Hi. Thanks!
> 
> With your timezones, I would assume either that it's Django not setting the TZ correctly from the ENV var, or that the tasks always operate in UTC. Can you drop into the container and check Django please:
> 
> ```shell
> $ docker exec -ti tubesync python3 /app/manage.py shell
> ```
> 
> Then in the python shell enter this to get a datetime object hopefully with the timezone set correctly like this:
> 
> ```python
> >>> from django.utils import timezone
> >>> timezone.localtime()
> datetime.datetime(..., tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))
> ```

OK I tried and here's what I got!
(wasn't sure if that second line was a single or two commands so tried both)

```c++
# python3 /app/manage.py shell

Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)

>>> from django.utils import timezone

>>> timezone.localtime()
datetime.datetime(2024, 1, 30, 19, 35, 37, 838117, tzinfo=<UTC>)

>>> datetime.datetime(..., tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))

Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'datetime' is not defined

>>> timezone.localtime() datetime.datetime(..., tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))

  File "<console>", line 1
    timezone.localtime() datetime.datetime(..., tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))
                         ^^^^^^^^
SyntaxError: invalid syntax

>>> 
```

**Comment by meeb** [comment]
Excellent, thanks. So this line in your output:

```python
>>> timezone.localtime()
datetime.datetime(2024, 1, 30, 19, 35, 37, 838117, tzinfo=<UTC>)
```

Shows that your TubeSync install is still operating in the default UTC so whatever ENV var you're setting it's not working. Can you run this on your host please?

```bash
$ docker exec -ti tubesync echo $TZ
```

**Comment by devanteweary** [comment]
OK thanks again!

Here we go:

```html
# env | grep TZ
TZ=America/Los_Angeles
```

**Comment by meeb** [comment]
Weird, it's set correctly but looks like Django isn't picking it up correctly. Can you try `TZ=PST` as a test in your container config and restart it, see if that changes anything?

**Comment by meeb** [comment]
OK, thanks for testing. I'll check what the workers are doing. I've probably used a `.now()` not a `.localtime()` somewhere.

**Comment by btalanski** [comment]
This seems to have worked for me, pls note that my docker is running in a Linux host:

1 - When you start the container, map your local `etc/timezone` to a volume inside the container:
```
-v /etc/timezone:/etc/timezone:ro
```
2 - Attach to the running container and run `cat /etc/timezone` 
3 - Check if the result of the command matches your host's timezone.

**Comment by meeb** [comment]
Ah right, might just not have some timezones bundled into the container. Thanks for finding it. I'll see if I can stuff those in by default into the next release.

**Comment by meeb** [comment]
Turns out this wasn't anything to do with the container runtime, it's to do with Django actually forcibly setting the `TZ` env var for you on settings init which is set before the `local_settings.py` container overrides were executed. This replaced the env var with `UTC` which was set as the default in `settings.py`. This is apparently some 17-18 year old (!) hack for Windows:

https://code.djangoproject.com/ticket/2315

set here:

https://github.com/django/django/blob/f71bcc001bb3324020cfd756e84d4e9c6bb98cce/django/conf/__init__.py#L204

In testing this results in very weird events like this:

```bash
root@b151a57dc6fd:/app# python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getenv('TZ')
'America/Los_Angeles'
>>> os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'tubesync.settings') # initialise Django
'tubesync.settings'
>>> os.getenv('TZ')
'America/Los_Angeles'
>>> from django.conf import settings
>>> settings.TIME_ZONE
'UTC'
>>> os.getenv('TZ')
'UTC'
```

Moving the `os.getenv('TZ')` to `settings.py` resolves this as `TIME_ZONE` is no longer overridden later in `local_settings` and is set before `Settings.__init__(...)` is called.
