### ISSUE TITLE
Error: "Failed to extract_info for xxx

### ISSUE THREAD

**Issue by neuleo** [meeb/tubesync#465]
Hi, my Tube sync instance isn't working for quite some time now. But it seems that I'm the only User with that Problem. Any Idea why this isn't working

` Index media from source "whistlindiesel1000", attempted 2 times
Error: "Failed to extract_info for "https://www.youtube.com/c/@whistlindiesel1000/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff."
 Task will be retried at 2024-02-13 12:01:40`

![image](https://github.com/meeb/tubesync/assets/99101285/01b7bd63-e2c3-4689-8c13-99df16d87778)

That Error show for every YouTube Channel is out there.
tubesync  | 2024-02-13 12:07:39,799 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (1/3)...
tubesync  | 2024-02-13 12:07:39,910 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (2/3)...
tubesync  | 2024-02-13 12:07:40,022 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (3/3)...
tubesync  | 2024-02-13 12:07:40,130 [tubesync/WARNING] [youtube:tab] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
tubesync  | 2024-02-13 12:07:40,230 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
tubesync  | 2024-02-13 12:07:40,231 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (1/3)...
tubesync  | 2024-02-13 12:07:40,273 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
tubesync  | 2024-02-13 12:07:40,273 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (2/3)...
tubesync  | 2024-02-13 12:07:40,319 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
tubesync  | 2024-02-13 12:07:40,320 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (3/3)...
tubesync  | 2024-02-13 12:07:40,384 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
tubesync  | 2024-02-13 12:07:40,388 [tubesync/ERROR] ERROR: [youtube:tab] @whistlindiesel1000: Unable to download API page: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by meeb** [comment]
You need to convert your `@channelnames` into channel IDs and try adding channels by ID. This is a relatively common issue. See (for example): https://github.com/meeb/tubesync/issues/436
