### ISSUE TITLE
Processing when a downloaded video is changed to private

### ISSUE THREAD

**Issue by woozu-shin** [meeb/tubesync#468]
### Version
- 0.13.3

### Abstract
- Processing when a downloaded video is changed to private, will raise exception and hang whole background tasks.
- Add exception handling when retrieving media info if the original video is not accessible.

### Details
- traceback log
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 238, in download_media_metadata
    metadata = media.index_metadata()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/models.py", line 1422, in index_metadata
    return indexer(self.url)
           ^^^^^^^^^^^^^^^^^
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=REDACTED": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
```

### References
- n/a

**Comment by woozu-shin** [comment]
Is there any branches git-flow related?
In my opinion, it is a medium-sized project, and one that is receiving interest from many users.
If there is branch strategy, more active P/R may be possible. :)
thx for nice project.

**Comment by meeb** [comment]
Exceptions raised by the worker won't block tasks and they are designed to be informative traces in the container logs so raising exceptions on failures is working properly as designed. I'll close this for now.
