### ISSUE TITLE
Unable to download API page: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by zxarr** [meeb/tubesync#477]
Attempting to grab this channel produces an error:

2024-02-26 17:18:19,073 [tubesync/ERROR] ERROR: [youtube:tab] @forestyforest: Unable to download API page: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Full snippet of log:

[tubesync.log](https://github.com/meeb/tubesync/files/14412027/tubesync.log)

Looks like a yt-dlp issue?  Not sure I can extract the yt-dlp logs from the container, but thought I'd report it here.

**Comment by meeb** [comment]
`@forestyforest` will need to be converted to its real channel ID first. If you put `@forestyforest` into a tool like:

https://www.streamweasels.com/tools/youtube-channel-id-and-user-id-convertor/

The channel ID is actually `UCofJu853kJKpkg4y5a-9YXg`. In tubesync add a source by channel ID and enter `UCofJu853kJKpkg4y5a-9YXg` and it should work.

This is a long standing issue where some `@channels` are really sort of meta-pages with groups of playlists and not single channels or playlists. These translate under the hood to channel IDs.

**Comment by AirplanegoBrr** [comment]
Mr. Nightmare doesn't work. Might be a Youtube issue tho-
https://www.youtube.com/c/UCnM02drQP-dF7WMgtJHR4Xw - doesn't work
https://www.youtube.com/channel/UCnM02drQP-dF7WMgtJHR4Xw - Works

Tubesync should just be updated to support the @ usernames.

**Comment by meeb** [comment]
If you add a channel by channel ID it'll work as you describe. Adding @ username support isn't entirely trivial, you're welcome to submit a PR if you don't want to convert usernames to channel IDs first.

**Comment by meeb** [comment]
`/c/` URLs directly map to channel IDs. The @ handle URLs are occasionally, or used to last time I looked into it, more complex and can contain multiple playlists and other sources making them annoying to reliably index to obtain new media to download.

This is not a case of I've just not bothered to remove `/c/` from a string. As I said above, fully supporting @ handle URLs isn't entirely trivial.

Just removing the `/c/` would result in many people who use this suddenly having their clients try and download thousands of videos or other undesirable side-effects. It may be stable enough now to add @ handle support as an entirely new and different option and not modifying the existing `/c/` option.
