### ISSUE TITLE
Wrong naming format used

### ISSUE THREAD

**Issue by ntbritton** [meeb/tubesync#484]
I am playing with the naming format so plex can be better with what i grab.   Is there a way to rename items, or force items to redownload?

**Comment by meeb** [comment]
There currently isn't a way to bulk rename downloads, no. If you change the source file format, skip and then unskip a media item it should redownload.

**Comment by ntbritton** [comment]
Is there a way to do a bulk skip and unskip?

**Comment by ntbritton** [comment]
Thanks!!  That would be much appreciated!  For now I just removed and readded the channel
