### ISSUE TITLE
Regex has max length

### ISSUE THREAD

**Issue by jordanlambrecht** [meeb/tubesync#486]
I'm trying to normalize music video naming conventions. When adding a source, I have the following regex filter:
`(\(.*?\)|\[.*?\])|\|.*$|\b(animated\s+)?(official|music\s+)?(video|lyric\s+video)\b|[\u2013\u2014\u2015\u2212\u002D\uFE58\uFE63\uFF0D]+|['"]|\s{2,}`

However, the regex input field has a max character length on it, so it truncates to:
`(\(.*?\)|\[.*?\])|\|.*$|\b(animated\s+)?(official|music\s+)?(video|lyric\s+video)\b|[\u2013\u2014\u2`

**Comment by meeb** [comment]
It needs a max length, but I've bumped it from 100 to 200 chars.

**Comment by jordanlambrecht** [comment]
Sweet, thanks dude.
