### ISSUE TITLE
v0.13.5 docker doesn't exist

### ISSUE THREAD

**Issue by hadleyrich** [meeb/tubesync#489]
It looks like the release action might have failed. Latest seems to exist but not v0.13.5

https://github.com/meeb/tubesync/actions/runs/8236049117

**Comment by meeb** [comment]
v0.13.6 built properly so I'll close this for now. Feel free to comment if you continue to have issues.

**Comment by hadleyrich** [comment]
> You can safely use `:latest` really, you almost certainly always want the latest build as tubesync has to track yt-dlp versions as they are released to keep working.
> 
> v0.13.5 failed because yt-dlp remove their old ffmpeg builds when they autogenerate new builds, this breaks the hash check for ffmpeg. Whenever yt-dlp publish a new ffmpeg build the tubesync contaner build fails until it gets updated. I've pushed a new v0.13.6 release now which fixes this for now.

Thanks for taking the time and explaining, I can appreciate the difficulty with the upstream vendor stuff.

It was a bit of a drive by issue sorry, I just wanted to flag it but it wasn't super high priority.

Normally I like to use a tagged version so I can get notified by renovate of a new release and review to make sure there's no breaking changes etc. I realise this is me specific and I'm not trying to make demands on you. If I can try and find some space I'll see if I can contribute :)
