### ISSUE TITLE
Failed to extract_info

### ISSUE THREAD

**Issue by akhisyahmi** [meeb/tubesync#490]
Hi, im using unraid with your tubesync docker on Apps section. After I put the link, it show up this error message. I do read about this issue on another ticket: [git](https://github.com/meeb/tubesync/issues/137)

But that doesn't fix my problem as I follow your guide below that ticket issue and still can't get the youtuber unique ID.

```
Indexmedia from source "technotim", attempted 3 times
Error:` "Failed to extract_info for "https://www.youtube.com/c/@TechnoTim/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
```

**Comment by akhisyahmi** [comment]
I got the youtuber ID and still the same error

**Comment by meeb** [comment]
What's the exact error log once you're using the channel ID?

**Comment by akhisyahmi** [comment]
> What's the exact error log once you're using the channel ID?

The same error as above.

`Indexmedia from source "technotim", attempted 3 times
Error:` "Failed to extract_info for "https://www.youtube.com/c/@TechnoTim/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.`

**Comment by meeb** [comment]
You've not deleted and re-added the source using the channel ID?

**Comment by akhisyahmi** [comment]
![image](https://github.com/meeb/tubesync/assets/69383220/676f7f8d-fbec-480b-96f9-fde480438745)

It seems to work now. I need to delete and make new source using channel ID. Editing old source give me error.

**Comment by meeb** [comment]
Yep deleting and re-adding by channel ID would fix it.
