### ISSUE TITLE
Problems When TubeSync Attempts To Use A Colon ':' in a file name.

### ISSUE THREAD

**Issue by AshleyAshes** [meeb/tubesync#494]
When the 'friendly name' for a series or playlist contains a colon, for example 'Arcadology: Histories' and then {source_full} is used for the file name, all file names are instead broken with seemingly random characters or other issues.

If you remove the colon from the 'friendly name' {source_full} becomes safe to use again.

On that note, the remark 'Friendly name for the source, used locally in TubeSync only' may not be accurate, as whatever the 'friendly name' is even effects the 'showtitle' value in the exported NFO as well.

**Comment by meeb** [comment]
Most file systems can handle `:` in filenames fine, so it's very dependent on where you're storing your media. Windows being the exception here. That's also why `{source}` exists, which is the source name passed through a make-everything-safe "slufigy" filter.

Are you asking for a specific Windows save full source name variable which isn't sluggified? Can you not just use the sluggified version of the source name if your platform requires a limited set of characters in the filename?

**Comment by AshleyAshes** [comment]
No, I don't think this is a Windows issue, let me provide more details.  First, I'm running TubeSync in a Docker on an UnRAID server.  I'm trying to make a 'Series' out a youTube Playlist, this one: https://www.youtube.com/playlist?list=PL5UQ0JXkgmN2Eeh1QFKP58B9eSm89gU7a

And my file name format is as follows: {source_full} {yyyy_mm_dd} {title_full} [{resolution} WEB-DL].{ext}

The friendly name is 'Arcadology: Histories'

The folder is 'Arcadology Histories' with the colon removed.

The resulting filenames are this:

![image](https://github.com/meeb/tubesync/assets/33394709/10dabc17-d334-40cb-aa3b-85a68f9e0fcb)

This is resolved by removing the colon from the 'Friendly Name' and nothing else.

This is also resolved when using {source} instead of {source_full} but I rather prefer the human friendly filename when using {source_full} and this is definitely a bug all the same.

**Comment by meeb** [comment]
The above commit should strip some commonly used filename chars, including colons, from `{source_full}`. Note I would still suggest you do not use this field for filenames as it might still contain pretty much any unicode character. If you are using a filesystem that is doesn't handle anything that's not ASCII well you should really use `{source}`.

I'm not stripping non-ASCII otherwise anything not English is likely to break.
