### ISSUE TITLE
Emoji causes conflicts with Kodi

### ISSUE THREAD

**Issue by AshleyAshes** [meeb/tubesync#495]
Kodi has no real support for Emoji and such in the UTF-8 character set and it causes issues with parsing.  I used TubeSync to download the channel Phil's Computer Lab, where many of the descriptions contain emoji, and so do a few of episode titles which also results in file names with Emoji, so when scraping from NFO files, Kodi errors out.  Is it possible to get an option to filter such characters out to prevent issues?

**Comment by meeb** [comment]
You can trivially force the titles to be ASCII only, however this would break anything that requires unicode characters such as non-Latin alphabets. I don't use Kodi so can't really test this. Would stripping some UTF-8 chars such as just emojis but not other chars fix this?

**Comment by AshleyAshes** [comment]
Well, I'm not entirely sure what to suggest, but there is def an issue with Kodi not accepting the characters.  I've never run into this issue before, but when all previous scraping was using theTVDB, a source doesn't allow Emoji in names, or my own handwritten NFOs, it's just never been encountered before.

With Phil's Computer Lab however, some 795 videos, and a shocking amount containing Emoji, one even having Emoji in a filename, it caused a hell of a lot of problems.  My solution was to batch convert the NFO files to ASCII.  Manually editing the NFO files to remove those characters also worked but that was also rather slow.

Sorry to be hitting you with multiple issues, this is actually a super neat tool, I'm just running into issues here as I test it out.

Personally, I'd be fine with a 'Convert all characters to ASCII' with some friendly question marks or spaces where non-ASCII characters once were.  If you wanted to filter specific characters, well you're the dev, but I'm not exactly sure which characters in UTF8 Kodi doesn't support.

**Comment by meeb** [comment]
Seems related:

https://github.com/kodi-pvr/pvr.iptvsimple/issues/163

As the NFO writing feature is pretty much just for Kodi and derivatives I don't mind patching this. I can strip just emojis and flags, it's pretty hacky (blanket stripping unicode sequences between large ranges) but possible. This appears to be a Kodi bug in general, but given it seems generally trivial to work around I'll pop it in the next release.

I won't add a force-everything-to-ASCII filter, otherwise if anyone (for example) downloads a video with a title in Japanese their title string in the NFO would be an empty string.

**Comment by meeb** [comment]
The above commit should filter emojis from the NFO title, source (used as show title), uploader (used as the studio) and description (used as the plot). It'll be bundled into the next release.

**Comment by AshleyAshes** [comment]
That's great, thanks.  Sorry for all these issues, I just was testing out TubeSync last night, I think it's great, but I'm running into cases where it breaks with Kodi, so sorry as I post these.

**Comment by meeb** [comment]
All good, I don't think many people have deployed tubesync with Kodi so it's not unexpected you would find issues. This is the correct place to report issues!
