### ISSUE TITLE
Odd problem opening main page

### ISSUE THREAD

**Issue by morpheus2n2** [meeb/tubesync#501]
I have an odd problem, I can open and login to tubesync just from from any mobile device on my network.

But I can not get on with any desktop system, both run windows and MS edge, I just get the spinning circle of doom on the tab while its trying to load, however the logfiles for tubesync so that a connection with the browser has been established.
My mobile devices are both android and also using MS edge browser and they can open the page and us tubesync just fine lol

**Comment by meeb** [comment]
That certainly sounds like a local issue on your desktop specifically with Edge, I'm not sure there's much I can do to assist here. Try FireFox? Check your firewall rules? Make sure you're not defaulting to https:// for the container?

**Comment by morpheus2n2** [comment]
Ok I fixed it, it seemed to be the login pop up, I re deployed the image and disabled security and can access it fine lol
