### ISSUE TITLE
tasks not running

### ISSUE THREAD

**Issue by ntbritton** [meeb/tubesync#505]
I have 768 tasks showing an immidate schedule but nothing is running.    I have tried to do a task reset from the container, and wait a couple days but that does not seem to work.    

if I run 

python3 /app/manage.py process_tasks

It does not show anything running.  How is the best way to proceed.

**Comment by meeb** [comment]
Are any errors showing on your tasks page? Any errors in your container logs? `process_tasks` spawns the task runner itself, probably best leaving that to the container to manage.

**Comment by ntbritton** [comment]
Nothing in the container logs.   Not a single line since yesterday.

[image: image.png]

**Comment by meeb** [comment]
You're not giving me much here to help diagnose this. What happens when you restart the container? Anything in the host logs?

**Comment by ntbritton** [comment]
Sorry about that.   I am more than happy to provide you with anything that
you need.

On the task page, I do see one error for a database locked, and that its
scheduled to retry.

Here is the last 60 min after a restart of the container.


***@***.***:~# docker logs tubesync --since 60m --follow



s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service tubesync-worker: stopping
s6-rc: info: service nginx: stopping
s6-rc: info: service nginx successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service tubesync-worker successfully stopped
s6-rc: info: service gunicorn: stopping
[2024-06-10 09:19:45 -0500] [319] [INFO] Handling signal: term
[2024-06-10 09:19:45 -0500] [350] [INFO] Worker exiting (pid: 350)
[2024-06-10 09:19:45 -0500] [351] [INFO] Worker exiting (pid: 351)
[2024-06-10 09:19:45 -0500] [349] [INFO] Worker exiting (pid: 349)
[2024-06-10 09:19:46 -0500] [319] [INFO] Shutting down: Master
s6-rc: info: service gunicorn successfully stopped
s6-rc: info: service tubesync-init: stopping
s6-rc: info: service tubesync-init successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes,
sessions, sync
Running migrations:
  No migrations to apply.
  Your models in app(s): 'sync' have changes that are not yet reflected in
a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run
'manage.py migrate' to apply them.
s6-rc: info: service tubesync-init successfully started
s6-rc: info: service gunicorn: starting
s6-rc: info: service gunicorn successfully started
s6-rc: info: service tubesync-worker: starting
s6-rc: info: service nginx: starting
s6-rc: info: service tubesync-worker successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2024-06-10 09:19:54 -0500] [318] [INFO] Starting gunicorn 22.0.0
[2024-06-10 09:19:54 -0500] [318] [INFO] Listening at: http://127.0.0.1:8080
(318)
[2024-06-10 09:19:54 -0500] [318] [INFO] Using worker: sync
[2024-06-10 09:19:54 -0500] [348] [INFO] Booting worker with pid: 348
[2024-06-10 09:19:54 -0500] [349] [INFO] Booting worker with pid: 349
[2024-06-10 09:19:54 -0500] [350] [INFO] Booting worker with pid: 350

**Comment by meeb** [comment]
Ah, database locked is an SQLite error. Typically this might occur if you have a high number of tasks and possibly set worker count to > 1. Generally this is as sign you might want to use Postgres or MySQL as a backend instead.

**Comment by meeb** [comment]
Sure, the "lock" is two processes attempting to write to the SQLite database at the same time. Make sure your worker processes is set to 1, then restart the container. Then run `python3 /app/manage.py reset_tasks`. That should clear it.

**Comment by meeb** [comment]
Also with the sources you've added you really probably need to use Postgres or MySQL. There's a migration guide here:

https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md

**Comment by ntbritton** [comment]
Thats great insight!   Thank you.    I will take a look at that guide.   Is
there a preference of which to migrate to?

**Comment by meeb** [comment]
No, both should be more than adequate. Whatever you're most comfortable with. Personally I use Postgres over MySQL.

**Comment by ntbritton** [comment]
Thanks.   I will dig into that.

**Comment by ntbritton** [comment]
That process looked very straight forward, so I went for it.   I am to the
import part, and it does not seem to import.

***@***.***:~# cat /tmp/tubesyncdb.json | docker exec -i tubesync
python3 /app/manage.py loaddata - --format=json
2024-06-10 14:01:07,396 [tubesync/INFO] Using database connection:
***@***.***:5432/tubesync

***@***.***:~# ll -h /tmp/tubesyncdb.json
-rw-r--r-- 1 root root 3.3G Jun 10 13:31 /tmp/tubesyncdb.json

***@***.***:~# cat /data/apps/docker/docker-compose/tubesync-server.yml
version: '3.7'
services:
  tubesync-db:
    image: postgres:15.2
    container_name: tubesync-db
    restart: unless-stopped
    volumes:
      -
/data/docker/containers/tubesync-server/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /data/docker_local/postgresql/tubesync-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /data/docker_local/tubesync/config:/config
      - /data/media/tubesync/downloads:/downloads
    environment:
      - TZ=America/Chicago
      - PUID=1032
      - PGID=100
      - TUBESYNC_WORKERS=1
      - TUBESYNC_RESET_DOWNLOAD_DIR=False
      - ***@***.***
:5432/tubesync
    depends_on:
      - tubesync-db



s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
2024-06-10 13:47:38,740 [tubesync/INFO] Using database connection:
***@***.***:5432/tubesync
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes,
sessions, sync
Running migrations:
  No migrations to apply.
  Your models in app(s): 'sync' have changes that are not yet reflected in
a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run
'manage.py migrate' to apply them.
s6-rc: info: service tubesync-init successfully started
s6-rc: info: service gunicorn: starting
s6-rc: info: service gunicorn successfully started
s6-rc: info: service tubesync-worker: starting
s6-rc: info: service nginx: starting
s6-rc: info: service tubesync-worker successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2024-06-10 13:47:40 -0500] [314] [INFO] Starting gunicorn 22.0.0
[2024-06-10 13:47:40 -0500] [314] [INFO] Listening at: http://127.0.0.1:8080
(314)
[2024-06-10 13:47:40 -0500] [314] [INFO] Using worker: sync
[2024-06-10 13:47:40 -0500] [344] [INFO] Booting worker with pid: 344
[2024-06-10 13:47:40 -0500] [345] [INFO] Booting worker with pid: 345
[2024-06-10 13:47:40 -0500] [346] [INFO] Booting worker with pid: 346
2024-06-10 13:47:40,557 [tubesync/INFO] Using database connection:
***@***.***:5432/tubesync
2024-06-10 13:47:40,973 [tubesync/INFO] Using database connection:
***@***.***:5432/tubesync
2024-06-10 13:47:41,097 [tubesync/INFO] Using database connection:
***@***.***:5432/tubesync
2024-06-10 13:47:41,108 [tubesync/INFO] Using database connection:
***@***.***:5432/tubesync

**Comment by meeb** [comment]
What isn't working exactly? Is there data in your Postgres database tables? Also, you REALLY want to drop your workers to 1. If you have this set to more than one YouTube will end up just blocking your IP and your tasks will never complete. It's a legacy setting.

**Comment by ntbritton** [comment]
Correct, i dont see anything in the database, after the import, such as no
sources.

With using a postgres database , what should I set the workers to?  Are
there recommendations?  Is this the setting you are referring to dropping
to 1?
 - TUBESYNC_WORKERS=1

**Comment by meeb** [comment]
Yes, `TUBESYNC_WORKERS` should be `1`, the default. As for why the import didn't work, no idea, there's no information in your logs to tell why. Check the export looks like valid JSON to start with I guess. Also try moving the single dash `-` (meaning read from stdin) to the end on the import command.

**Comment by meeb** [comment]
Also the dumpdata / loaddata commands aren't tubesync specific, they're standard Django commands and have extensive docs if that's useful:

https://docs.djangoproject.com/en/5.0/ref/django-admin/#django-admin-dumpdata
https://docs.djangoproject.com/en/5.0/ref/django-admin/#django-admin-loaddata

The only extra part is piping the export into the container.

**Comment by ntbritton** [comment]
moved the "-" to the end of the command, no luck,

json looks good I think.  Here is a sample from a more on the file.

 more /tmp/tubesyncdb.json
[{"model": "auth.permission", "pk": 1, "fields": {"name": "Can add log
entry", "content_type": 1, "codename": "add_logentry"}}, {"model":
"auth.permission", "pk":
 2, "fields": {"name": "Can change log entry", "content_type": 1,
"codename": "change_logentry"}}, {"model": "auth.permission", "pk": 3,
"fields": {"name": "Can d
elete log entry", "content_type": 1, "codename": "delete_logentry"}},
{"model": "auth.permission", "pk": 4, "fields": {"name": "Can view log
entry", "content_type
": 1, "codename": "view_logentry"}}, {"model": "auth.permission", "pk": 5,
"fields": {"name": "Can add permission", "content_type": 2, "codename":
"add_permission
"}}, {"model": "auth.permission", "pk": 6, "fields": {"name": "Can change
permission", "content_type": 2, "codename": "change_permission"}},
{"model": "auth.permi
ssion", "pk": 7, "fields": {"name": "

**Comment by ntbritton** [comment]
It was a memory issue, trying to load a 3gb export file.

**Comment by meeb** [comment]
Yep buffering that then iterating over it is going to take a good chunk of RAM. Depending on your setup you might just want to re-add your sources into your Postgres-backed install and then import media:

https://github.com/meeb/tubesync/blob/main/docs/import-existing-media.md

**Comment by meeb** [comment]
No problem, glad you got it to work.

**Comment by meeb** [comment]
I'll close this for now as it seems resolved, feel free to comment back if it isn't.
