### ISSUE TITLE
X_FRAME_OPTIONS is defaulted to DENY

### ISSUE THREAD

**Issue by theoutsider24** [meeb/tubesync#51]
In order to embed WebSync in something like Organizr, `X_FRAME_OPTIONS = 'SAMEORIGIN'` should probably be used in settings.py to allow iframe embedding

**Comment by meeb** [comment]
Yep sounds OK given there's no security in TubeSync at the moment and the forms all have Django's default CSRF protection.

**Comment by meeb** [comment]
Fixed in `:latest`, will be bundled into the next release.
