### ISSUE TITLE
Error index media from source

### ISSUE THREAD

**Issue by Benavent21** [meeb/tubesync#514]
I always get this error when trying to download video from youtube channels:

![image](https://github.com/user-attachments/assets/bb1f3923-016b-44f5-923e-a4b850711e80)

Any idea?

**Comment by depuhitv** [comment]
It’s a known issue. Refer [#299](https://github.com/meeb/tubesync/issues/299)

**Comment by meeb** [comment]
As @depuhitv has linked to the answer I'll close this for now.
