### ISSUE TITLE
Video titles only showing ID, not title.

### ISSUE THREAD

**Issue by devanteweary** [meeb/tubesync#524]
Hey there. Awesome app. Been using it for a year now at least.  
Much better than TubeArchivist if I may say so!!!

I noticed today that the videos show random letters/numbers instead of the video title on both the recents and the media page.  
Not sure how long it has been like this. Maybe since the beginning for me. But wanted to let you know.

Here are some examples. For instance, in the first image after "Media" it should say the title, but rather it shows DcJNHg...etc...

![image](https://github.com/user-attachments/assets/52ecdb78-d0c8-4023-b872-472d57c11ac4)

![image](https://github.com/user-attachments/assets/a3004d7b-4cd8-40ca-b3ff-77d1842b7536)

OK that's about it. Thank you!

**Comment by meeb** [comment]
Thanks for the kind words! I'm not sure what's going on here. Your issue would imply that the metadata downloaded for a media item is only partial. Enough to contain format information but not the video title itself. Can you execute this on the host machine please?

```bash
$ docker exec -ti tubesync python3 manage.py youtube-dl-info "https://www.youtube.com/watch?v=DcJNHg_Ruxc"
```

This should spam out the metadata for that media item in JSON.

**Comment by devanteweary** [comment]
> Thanks for the kind words! I'm not sure what's going on here. Your issue would imply that the metadata downloaded for a media item is only partial. Enough to contain format information but not the video title itself. Can you execute this on the host machine please?
> 
> ```shell
> $ docker exec -ti tubesync python3 manage.py youtube-dl-info "https://www.youtube.com/watch?v=DcJNHg_Ruxc"
> ```
> 
> This should spam out the metadata for that media item in JSON.

You know what... I was trying to figure out how to get that .JSON into file form since the output exceeded my console history and I checked and the videos now have proper titles again so I don't know WHAT happened but it's working correctly again. I didn't do anything (other than run that command a couple times).

Oh well let's just say it was a fluke and I'll check to see if it ever happens again. :P'

Thank you for the fast response though!

**Comment by meeb** [comment]
Thanks for the update. It sounds like your metadata wasn't properly or fully downloaded. This does attempt to correct itself in some situations (or you can skip then unskip a media item to force it). Once the meatadata is refreshed your titles would have started working. You could likely have seen the metadata download tasks running in your tasks page.
