### ISSUE TITLE
Hello from ElevenLabs

### ISSUE THREAD

**Issue by Hello-ElevenLabs** [meeb/tubesync#525]
Hey @meeb, I'm Silvia from ElevenLabs. We came across your GitHub profile and love the contributions we've seen. Would you be open to engineering opportunities with us? silvia@elevenlabs.io

**Comment by meeb** [comment]
Hi Silvia, thanks for the comment. Always happy to have a chat, feel free to pop over some information to meeb@meeb.org. Given this is at best a meta-issue I'll close it for now.
