### ISSUE TITLE
Error Sign in to confirm your age. This video may be inappropriate for some users.

### ISSUE THREAD

**Issue by schmitzkr** [meeb/tubesync#528]
On some channels I have noticed that some media gives the error
'Sign in to confirm your age. This video may be inappropriate for some users.'
Is it possible to sign in with tubesync?

`2024-07-28 10:41:41,682 [tubesync/ERROR] ERROR: [youtube] T33dJMbE_jw: Sign in to confirm your age. This video may be inappropriate for some users.
Rescheduling Downloading metadata for "4006eb1a-e95c-404b-a060-f3025a5e6451"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 291, in download_media_metadata
    metadata = media.index_metadata()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/models.py", line 1476, in index_metadata
    return indexer(self.url)
           ^^^^^^^^^^^^^^^^^
  File "/app/sync/youtube.py", line 89, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=T33dJMbE_jw": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "4006eb1a-e95c-404b-a060-f3025a5e6451" for 0:10:30 later at 2024-07-28 17:52:11.690748+00:00`

**Comment by meeb** [comment]
It is possible to sign in with tubesync by exporting your YouTube cookies and saving them as a text file that tubesync can detect and pass down to `yt-dlp`, see: https://github.com/meeb/tubesync/blob/main/docs/using-cookies.md

Note that this is generally not considered a good idea though as it may allow YouTube to detect your usage of `yt-dlp` powered clients and link it to your real YouTube (and Google) accounts. Up to you though.

**Comment by crazy-max** [comment]
This seems related to https://github.com/yt-dlp/yt-dlp/issues/11296#issuecomment-2425188728 where the age-restriction workaround doesn't work anymore
