### ISSUE TITLE
source regex filter doesn't seem to work

### ISSUE THREAD

**Issue by schmitzkr** [meeb/tubesync#541]
When I use a regex filter nothing is downloaded.
Is there an example of what should appear in this field?
My filter was `\text\gi`

**Comment by meeb** [comment]
Try something like `(words|blah)`. The tickbox below the regex field inverts the regex from a match (so the example would *only* download media items with "words" or "blah" in the title) a negative match (so the example would skip media items with "words" or "blah" in the title).

**Comment by schmitzkr** [comment]
Thanks very much for the example, some changes to regex worked.
