### ISSUE TITLE
autoskip unavailable videos

### ISSUE THREAD

**Issue by snowytoxa** [meeb/tubesync#551]
Hi,

there is a number of videos in the playlist what are not being downloaded due to permanent errors, such as:

- _This video has been removed for violating YouTube's Terms of Service_
- _Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated._
- probably not the full list

It would be awesome if tubesync automatically marks these to skip instead of retrying them every now and then.

**Comment by meeb** [comment]
This is already the current behavior. Any failures to download a video are retried. After enough retries have failed, the video is marked to be permanently skipped. This can take a couple of days though.

**Comment by meeb** [comment]
No, you will need to click "unskip" to get them to retry their download.
