### ISSUE TITLE
Wrong audio language downloaded

### ISSUE THREAD

**Issue by henrikmaurin** [meeb/tubesync#568]
Since about a week, some of my videos have audio in the wrong language.
I guess Youtube have made some changes.

yt-dlp seems to get the correct (default) language when used without any special options.

So it would be super if Tubesync could automatically chose the default language
Even better would be an option to specify a prefered language, with fallback on default.

Or is there already some setting I have missed for this?

Example of video where my downloaded language became Italian:
https://www.youtube.com/watch?v=alH5rEy0LWs

**Comment by Nanganator** [comment]
There is a comment in #368 with a new utils.py that you need to use (it is in a utils.zip files attached to a comment). This will download the videos with English audio.

**Comment by superjedi27** [comment]
I'm not the best with unRAID but I finally figured it out, place the utils.py file in one of your shares. Then open the terminal for unRAID at the top and run the following command-
sudo docker cp /mnt/user/insertYourShareNameInfo/utils.py TubeSync:/app/sync

For me TubeSync is capitalized cause thats how I named the docker, so your might be all lower case or it could be something completely different, wahtever its named on the Docker tab, then restart tubesync and redownload the videos.

**Comment by henrikmaurin** [comment]
Thanks! I will try this...

So its not a new problem... Just two of my subscribed channels suddenly decided to add a bunch of translated languages in the last week

**Comment by meeb** [comment]
Yeah it's not a new issue. I'll close this as a dupe, you can follow it on the other issue. Thanks for reporting it though!
