### ISSUE TITLE
Select new FFmpeg build

### ISSUE THREAD

**Issue by tcely** [meeb/tubesync#575]
The current container is failing because the checksum doesn't match.

A 404 page is what I received in my browser for the URL.

**Comment by TheNewStellW** [comment]
latest docker build tells me ffmpeg is missing(?) when attempting to combine mp4 and m4a. Could this be related to your updated push?

**Comment by meeb** [comment]
No, the latest build contains working ffmpeg. Specifically what is your exact error message?
