### ISSUE TITLE
add subtitles parameter

### ISSUE THREAD

**Issue by LeendertPlas** [meeb/tubesync#61]
Would it be possible to add the subtitle parameter in the future? Youtube-dl already has al lot of these parameters so maybe a text field could be added where you can fill this in?

```
--write-sub                      Write subtitle file
--write-auto-sub                 Write automatic subtitle file (YouTube only)
--all-subs                       Download all the available subtitles of the video
--list-subs                      List all available subtitles for the video
--sub-format FORMAT              Subtitle format, accepts formats preference, for example: "srt" or "ass/srt/best"
--sub-lang LANGS                 Languages of the subtitles to download (optional) separated by commas, use IETF language tags like 'en,pt'
```

**Comment by meeb** [comment]
Hi, yes this is on the roadmap already. It's slightly more complex to handle than just adding in parameters, namely I need to look into how to verify subtitles were actually embedded (e.g. check with ffmpeg that the subtitle stream with the appropriate language details was created correctly post download). However, this is already being tracked and will be worked on in #7 so I'll close this as a dupe for now.
