### ISSUE TITLE
Web UI authentication

### ISSUE THREAD

**Issue by Jleagle** [meeb/tubesync#62]
I have all the software on my NAS port forwarded so i can access them outside the house.

I was surprised TubeSync had no authentication to secure this.

Is it possible for this to be added? Thanks.

**Comment by meeb** [comment]
Potentially. As stated in the FAQ TubeSync was designed to be as simple as possible to deploy and use and is already getting a bit more complex than my original personal use tool with all the extra features being added. It doesn't support SSL either out of the box and I'm probably not going to add that either.

The current suggestion is to deploy TubeSync behind a reverse proxy and apply SSL and any authentication you want that way which is relatively trivial to do assuming you're deploying it via a container.

I may add in basic HTTP authentication at some point with a simple `HTTP_USER` and `HTTP_PASS` style env vars, but full multi-user support and associated user management interface isn't on the roadmap for now.

**Comment by Jleagle** [comment]
> I may add in basic HTTP authentication at some point with a simple HTTP_USER and HTTP_PASS style env vars

This sounds perfect. Thanks.

**Comment by bcometa** [comment]
Some kind of basic authentication would be appreciated here too :)

**Comment by meeb** [comment]
Feature added in `:latest` and will be bundled into the future v1.0 release. Docs here:

https://github.com/meeb/tubesync#optional-authentication

**Comment by Jleagle** [comment]
Thanks 👍
