### ISSUE TITLE
Tasks stop queuing... "unexpected EOF"

### ISSUE THREAD

**Issue by bcometa** [meeb/tubesync#63]
Last line in log file is:

File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner

$Error grabbing logs: unexpected EOF

Please let me know what I can send to give you more info. This has happened to me few times. I can just restart docker container and it seems to eventually resume.

**Comment by bcometa** [comment]
Err... hum... even after restarting I have a bunch of scheduled tasks that say "task will run immediately" but they aren't running. ?

**Comment by meeb** [comment]
"Error grabbing logs: unexpected EOF" likely means it you failed to actually read the logs properly, that's not a TubeSync error. Are you sure tasks aren't running? Tasks run one at a time so "will run immediately" doesn't mean "is running now" it means "will run as soon as a worker is available". TubeSync is meant to be set and forget so if you add some large channels it can take a while for anything to appear, but activity will be in the logs.

Either way you will need to check in `docker logs tubesync` to see if there are any actual errors and paste a full stack trace of the error for me to be able to determine if there is a problem. Also confirm the version of TubeSync you're running, make sure you're running container v0.9.

**Comment by bcometa** [comment]
This was the error I found in the docker tubesync log. 

But, I've since deleted the container and re-added it. Now it just seems to do nothing. The interface opens, but no tasks are running, nothing is happening. 

Attached is the huge full log from prior to deleting/re-adding. You can see it was downloading fine
[tubesynclogs.zip](https://github.com/meeb/tubesync/files/6016835/tubesynclogs.zip)

 but then stopped on the 18th or 19th. Perhaps my IP is being blocked by YT (though, I can still watch YT videos)?  

Also attached the new small log after re-adding to docker.

**Comment by meeb** [comment]
Your "Error grabbing logs: unexpected EOF" is from your local Docker setup, not from TubeSync, Docker is saying it can't actually read the logs. That's an issue with your local Docker installation itself not with TubeSync. Search for "Error grabbing logs: unexpected EOF" for a load of other people with the same issue. It seems to be possibly macOS related and I suppose you could try a different `--log-driver` but that's out of the scope and unrelated to this project.

Try this:

1. Stop / delete / any existing TubeSync containers
2. Make sure you've pulled the latest container image with `docker pull ghcr.io/meeb/tubesync:latest` 
2. Start a new TubeSync container using `ghcr.io/meeb/tubesync:latest` WITHOUT the `-d` command line flag, that will cause TubeSync to run in the foreground and output logs to the console window
3. With that running in a terminal, go to the web interface and add a small channel or playlist as a test source, like `https://www.youtube.com/watch?v=XJ5-UkskZWk&list=PL2JiZAV5BmDVJICVl2DVJZnakJrcA3nVA` or similar
4. Watch what happens in the terminal if there are any errors paste the error and the traceback in this thread - An error will likely start with the word "Traceback" and end with a line telling you what the error was. This is an example Python error to give you an idea of what to look out for:

```python
Traceback (most recent call last):             # <- start of error, line starts with "Traceback:
  File "<stdin>", line 1, in <module>          # <- trace info about the error
ZeroDivisionError: division by zero            # <- error message itself
```

If you want to attach extensive logs, if you could please save them in plain text. As you seem to be on macOS, that's format -> make plain text from the menu bar. RTF isn't very useful.

**Comment by bcometa** [comment]
Thank you very much for your help!! 

1) Ok, deleted existing containers. 
2) Ran docker pull ghcr.io/meeb/tubesync:latest
3) Not sure if I did this right, but in terminal I did this:

163ea0e36418:~ cometa$ docker run \
> --name tubesync \
> -e PUID=501 \
> -e PGID=20 \
> -e TZ=America/Los_Angeles \
> -v ~/tubesync/config:/config \
> -v /Volumes/10\)\ 16TB\ 2020/Youtube\ \(via\ TubeSync\):/downloads \
> -p 4848:4848 \
> ghcr.io/meeb/tubesync:v0.9

4) I added this playlist, called it "TEST"
5) It is added as a task, but nothing else happens. It doesn't seem to do anything. Log (no errors though) attached. 

This just seems so strange since it worked for a day before this problem started happening (190 successful downloads, 78gb).

[tubesync log 1.txt](https://github.com/meeb/tubesync/files/6017224/tubesync.log.1.txt)

**Comment by meeb** [comment]
What's listed under your Tasks page? And does the "reset tasks" button do anything?

**Comment by bcometa** [comment]
Never noticed that button :)

I hit it, then confirmed, seemed to work. Tasks seem to be running again! It is cycling through tasks now with 1 running at a time. And more tasks are now scheduled than before doing the reset. 

But, it still doesn't seem to download anything. Every task/source seems to give this message:

"[tubesync/WARNING] Unable to download webpage: HTTP Error 429: Too Many Requests"

It's still running, but just keep giving this message (or, saying it's already been downloaded: "Download task triggeredd media: RaFsW9fOxCY (UUID: 6fa63450-75ab-4b14-a660-1125a7c69930) but it has already been marked as downloaded, not downloading again"). 

Full log attached and screenshot of tasks. 

[tubesync log 2 pre and post reset.txt](https://github.com/meeb/tubesync/files/6017276/tubesync.log.2.pre.and.post.reset.txt)
<img width="1036" alt="Screen Shot 2021-02-20 at 10 34 46 PM" src="https://user-images.githubusercontent.com/27237458/108617523-dee46f00-73cb-11eb-82ba-481e086834c5.png">

**Comment by meeb** [comment]
Ah, so you're being rate limited by YouTube. What I would suggest is just stopping the container for at least a few hours. If you have a dynamic IP, restart your router to get issued a new IP from your ISP.

Make absolutely sure no other copies of TubeSync are running, your symptoms could also be called by running more than one TubeSync container at the same time. The 429 rate limiting issues should have been (mostly) solved in v0.9.

`docker ps` to list containers, `docker stop idnumhere` to stop them, make sure there are NO TubeSync containers running for several hours, then start up a single v0.9 container and see if that solves your problems.

**Comment by meeb** [comment]
(The invalid label isn't for anything you did, just marking as such for my own reference managing tickets and because your issue doesn't appear to be with TubeSync itself).

**Comment by bcometa** [comment]
Got it. I only have one Tubesync running. I stopped it and also restarted router but still have same IP. So, I'll wait until tomorrow and then start 'er up again. Will report back. 

Thank you!

**Comment by bcometa** [comment]
Waited over 24 hours and getting same error. But, using VPN it's working. I guess I need to wait longer for IP to clear.

But, I noticed that many videos in my playlists are delisted or removed (i.e. https://www.youtube.com/watch?v=HxzXg8p4oU0 and https://www.youtube.com/watch?v=-O-HHi_0vsg). Perhaps it's the repeated retries on these videos that triggers some IP ban? The message in the log is "No metadata was returned by youtube-dl." Maybe you could exclude repeated checking for videos with no metadata?

**Comment by meeb** [comment]
The metadata indexing requests are not retried indefinitely so it's unlikely to be those, plus they have a back-off to avoid spamming too much. I would suspect your IP is just blacklisted from your past excessive requests for now which is why the VPN works.

**Comment by bcometa** [comment]
Gotcha. Is it normal that regular YT still works fine? It's just Tubesync that doesn't work.

Also, and maybe this should be a different thread, but I have several sources that are showing 0 videos and aren't in the "tasks" even after 12+ hours (set to 6 hour refresh).

Several sources with "0" videos:
<img width="668" alt="Screen Shot 2021-02-23 at 9 03 08 AM" src="https://user-images.githubusercontent.com/27237458/108879800-786f7480-75b6-11eb-9ed8-8feb506b68db.png">

All tasks:
<img width="487" alt="Screen Shot 2021-02-23 at 9 03 35 AM" src="https://user-images.githubusercontent.com/27237458/108879822-7dccbf00-75b6-11eb-87f5-30d5744e163d.png">

**Comment by meeb** [comment]
That probably means that indexing the source returned no media items (rate limited or could not connect to YouTube etc.). I would expect there to be something in the logs with an error for that.

You could try just removing all your sources, waiting 24 hours, then adding just one source and see if that works? If you have previous rate limiting issues adding 14 channels as an immediate block of work will probably just trigger it again.

**Comment by bcometa** [comment]
Original IP working again. New media downloading after editing sources and changing refresh rate (I wanted to change to 24 hours anyhow after initially doing 6). Everything seems to be working well now! Thank you!

P.S. Do you have a donation link? I'd love to help support you as I've been waiting for something like this for ages.

**Comment by bcometa** [comment]
Just found the Sponsor section :)

**Comment by meeb** [comment]
Excellent, thanks for the confirmation! Good to know it is resolvable with lower number of requests being issued and having quite a few people confirming the work-arounds do work now is helping. Rate limiting issues should improve in the v1.0 release as well to be less erratic in behaviour. Thanks for the offer of support as well, most appreciated.
