### ISSUE TITLE
{format} is different between the video file and the nfo/jpg file

### ISSUE THREAD

**Issue by Cycor** [meeb/tubesync#67]
I am running :latest

Newly downloaded videos have a different {format} in the video filename than the jpg/nfo file
Every new download has this issue.

Some examples:
MKV: Artist - Title (720p-avc1-opus)
JPG/NFO: Artist - Title (avc1-opus-30fps)
--
MKV: Artist - Title (480p-avc1-opus)
JPG/NFO: Artist - Title (avc1-opus-25fps)
--
MKV: Artist - Title (240p-avc1-mp4a)
JPG/NFO: Artist - Title (avc1-mp4a-30fps)

**Comment by meeb** [comment]
Interesting, they use exactly the same format string internally, what is your format set to? The {stuff}_{stuff} string at the source level.

**Comment by meeb** [comment]
Oh and a sample YouTube video you noticed this on. With those two I can recreate what you've found to debug it.

**Comment by Cycor** [comment]
my format is {yyyymmdd} {source_full} - {title_full} [{key}] ({format}).{ext}

https://www.youtube.com/c/TyPalowski/videos

2021-02-22 14:14:02,992 [tubesync/INFO] Copying media thumbnail from: 
/config/media/thumbs/ad/ad82275f-6725-42bc-b833-ddc4e4734176.jpg to: 
/downloads/video/Ty Palowski/20200916 Ty Palowski - DIY Garage Parking Assist Stoplight [pScwL8NoMn4] (avc1-opus-24fps).jpg

2021-02-22 14:14:03,020 [tubesync/INFO] Writing media NFO file to: to: 
/downloads/video/Ty Palowski/20200916 Ty Palowski - DIY Garage Parking Assist Stoplight [pScwL8NoMn4] (avc1-opus-24fps).nfo


2021-02-22 14:14:03,463 [tubesync/INFO] Downloading media: 126W0SS20d0 (UUID: 4d3753de-a14a-4ce3-972b-dbff7b2f14e4) to: 
"/downloads/video/Ty Palowski/20200814 Ty Palowski - DIY WiFi Controlled Blinds - DIY Builds [126W0SS20d0] (1080p-avc1-opus).mkv"

**Comment by meeb** [comment]
Thanks, most helpful. Pretty sure that's a reasonably easy bug fix. I'll stuff it into the next release.

**Comment by Cycor** [comment]
awesome, any idea yet to which format you are going to change it too, I am manually renaming all the files now and would like to know what format to pick.

**Comment by meeb** [comment]
Probably the MKV format, so renaming the NFO and JPGs to match the MKV file is likely sensible. Don't quote me on that until I review the format generation code though!
