### ISSUE TITLE
Add longer indexing duration options between indexing

### ISSUE THREAD

**Issue by meeb** [meeb/tubesync#68]
Currently the maximum indexing duration is 24 hours. Some longer duration intervals, say 3 day and 7 day could be useful here in addition to the existing preset intervals.

**Comment by Pytsh** [comment]
Hello,
Unless I missed something, I think a 'never' option would be useful here. A use case would be for ended seasons of web shows.

**Comment by meeb** [comment]
Yep a reasonable suggestion. Added to the milestone. Cheers.
