### ISSUE TITLE
Add source level options for subtitles

### ISSUE THREAD

**Issue by meeb** [meeb/tubesync#7]
As raised in #1 there should be some options to obtain subtitles automatically.

**Comment by meeb** [comment]
Bumped. Needs a lot of testing.

**Comment by Extarys** [comment]
If this is implemented, after that can we get an option to go download and embed subtitles for already downloaded videos? :) Would be useful for old documentaries and other big videos to not redownload everything <3

**Comment by meeb** [comment]
It isn't yet, sorry, but it is on the roadmap.

**Comment by Extarys** [comment]
Oh, I know! Just a thought :smiley: :hugs:

**Comment by meeb** [comment]
Oh sorry, my mistake. I read that as "Is this implemented yet" for some reason. I don't *think* `youtube-dl` supports arbitrary merging of subtitles to existing video files so if this is possible it would likely require downloading the video again completely which is probably not what you want.

**Comment by Extarys** [comment]
No worries :)

I'm guessing a simple bash script to detect the video id, grab the subtitles and merge them with the existing video (or just move it and name it as the video file) could also work - and it's simpler on you.

I'll take a look and post the script here if/when I do this :)

**Comment by tehniemer** [comment]
Has this gotten anywhere? If implemented, would it be able to retroactively get the subtitles for already downloaded media or would the source have to be purged and re-added?

**Comment by garret** [comment]
Hope there will be any development of this feature request at some point.

**Comment by meeb** [comment]
I believe this is now a feature flag I can pass through to `yt-dlp` so it should be a lot easier, I'll re-review it.

**Comment by meeb** [comment]
This has been added for a while, closing.
