### ISSUE TITLE
Support external databases

### ISSUE THREAD

**Issue by meeb** [meeb/tubesync#72]
While defaulting to SQLite works fine for the initial target use case of a simple PVR it's unsuitable for larger deployments of archivists adding hundreds of sources with tens of thousands of media items.

The total number of ongoing concurrent writes even just from metadata indexing will start to cause database locking issues.

To solve this as an advanced optional setup TubeSync should support external Postgres and MySQL database servers.

This should be configurable by passing in a DSN-style env var.

**Comment by cleverestx** [comment]
If I have Postgres just installed, how do I connect Tubesync to this database using an ENV file? Would you be willing to post an example, as I'm very new to PostGres and Tubesync. I have a ENV file set up for the password stuff, but nothing about a database is configured in any ENV yet...do add a line in the same ENV? What line? Thanks.
