### ISSUE TITLE
Changing download cap

### ISSUE THREAD

**Issue by ibanez88** [meeb/tubesync#77]
Hi there - Great package, very impressed with it's function as is. 

Bug I've noticed is that when you setup a source, and you go back to edit it, if you increase the download cap, say from 30 days to 90 days the additional videos which are in that additional time-frame are not added even after the channel has been re-indexed. 

Perhaps if there was a mechanism to force a full re-download of everything when the download cap is increased?

Thanks!

**Comment by meeb** [comment]
Ah, well spotted, this is because when a media item is found to be older than the download cap it's "skip" flag is set and this is nto re-checked if you modify the download cap date again so it stays capped. Should be a reasonably easy fix.

**Comment by meeb** [comment]
As usual, adding an extra value to a drop-down menu causes ripples of issues elsewhere...
