### ISSUE TITLE
Allow --write-info-json so downloads can work with emby

### ISSUE THREAD

**Issue by retrospectvideo** [meeb/tubesync#78]
Allow --write-info-json so downloads can work with emby, currently does not read any of the metadata for downloaded channels.

**Comment by meeb** [comment]
Sure I can look into this, sounds reasonable to add as an extra metadata file option.

**Comment by retrospectvideo** [comment]
actually here is the issue with emby. the nfo file has to match the video filename. the filename for nfo file does not work. I fixed it simply by changing the filename.

**Comment by meeb** [comment]
Ah perfect. Is this actually just a dupe of #67 then?

**Comment by retrospectvideo** [comment]
thats right good call.

**Comment by meeb** [comment]
Nice, thanks for the confirmation. I'll close this as a dupe for now.
