### ISSUE TITLE
Redownload Media not removing thumb and nfo

### ISSUE THREAD

**Issue by itmunky** [meeb/tubesync#83]
When using the "Really delete and redownload media" function the video / audio file is deleted however the associated thumb (.jpg) and NFO (.nfo) remain in the download folder. 

I noticed this after changing the media format (naming) option wanting to remove old files and re-download as new media format (naming format).

**Comment by meeb** [comment]
TubeSync does actually delete the NFO files and thumbnails, however I would suspect this is a duplicate of #67 - the NFO likely was written with the wrong file name which is why it was not removed. Could you confirm please?
