### ISSUE TITLE
Docker Container Unable to download JSON metadata

### ISSUE THREAD

**Issue by martykiico** [meeb/tubesync#84]
Hi,

before 1 Week there were no problems to use tubesync, but today there are some errors to execute the sheduled tasks.

`Rescheduling Index media from source "strongandflexde"
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
func(*args, **kwargs)
File "/app/sync/tasks.py", line 163, in index_source_task
raise NoMediaException(f'Source "{source}" (ID: {source_id}) returned no '
common.errors.NoMediaException: Source "strongandflexde" (ID: 258866dc-1baa-4e5b-b9a8-cec7ed971f4d) returned no media to index, is the source key valid? Check the source configuration is correct and that the source is reachable
Rescheduling task Index media from source "strongandflexde" for 0:21:41 later at 2021-03-03 09:14:39.992057+00:00
2021-03-03 10:08:00,139 [tubesync/DEBUG] [youtube:tab] TheGeekFreaks: Downloading webpage
2021-03-03 10:08:00,427 [tubesync/DEBUG] [download] Downloading playlist: The Geek Freaks - Videos
2021-03-03 10:08:00,428 [tubesync/DEBUG] [youtube:tab] Downloading page 1
2021-03-03 10:08:00,563 [tubesync/ERROR] ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by martykiico** [comment]
think there is a dependencie issue in the docker container of the creator

**Comment by meeb** [comment]
That error means the YouTube channel you added now returns a 404 / not found error. Did you fix this? If not, let me know what the "key" is added to your source and what the source type is (e.g. channel) and I'll check it. I don't think this is an issue with TubeSync though at face value.

**Comment by Ateroz** [comment]
I also had issues with this error. It's caused by youtube-dl being out of date, and an update to the latest version fixes it.

I would recommend adding some method of updating youtube-dl at least daily to your 1.0 milestone. Youtube-dl is updated very frequently, sometimes several times a day, to fix things like this.

**Comment by meeb** [comment]
`youtube-dl` is currently updated in TubeSync weekly, I do check nothing breaks between updates so there's some manual overhead here which automation probably wouldn't be useful for. I've just bumped `youtube-dl` from 2021.2.22 to 2021.3.3 though if that helps you.

**Comment by Ateroz** [comment]
That definitely fixes the issue. Thanks for the quick response. Maybe add a button to manually update to the current version if automating it isn't your style? I thought I was being rate limited when I first my indexes failing a day or so ago. I'm surprised more people haven't been reporting issues.

Thanks for all the hard work!

**Comment by meeb** [comment]
I'll see if there's some sensible tests I can write and automate it a bit then. Probably an update every few days is sensible. Having an entire new TubeSync release every time `youtube-dl` updates might not be sane, given loads of people are going to be pulling `:latest` and update TubeSync multiple times a day which could be a bit spammy. A button could work, but, it would be a pain to code as you would need to restart a bunch of processes and the update would be lost when the container was restarted.

I've personally noticed no issues with weekly updates so far, but it's a reasonable point so I'll keep an eye out for how frequent issues are reported.

**Comment by martykiico** [comment]
iam using tubesync on my unraid Server.
iam already created a answer in the certain thread: [https://forums.unraid.net/topic/101947-support-ptrfrll-docker-images/page/2/](url)

it looks for me that there is it needed to update youtube-dl. But i cant do more then this to trigger the update for the docker image or iam wrong?

**Comment by meeb** [comment]
`youtube-dl` is already updated in `:latest` - try that. Also, check your source settings are correct and the link at the top of the page for the source to the YouTube channel is valid and working.

**Comment by martykiico** [comment]
with `:latest`
it works.

TubeSync version 0.9 with youtube-dl version 2021.03.03 and FFmpeg version 4.3.1-static. niceee

**Comment by meeb** [comment]
OK, just bear in mind `:latest` if you update automatically can have experimental or potentially broken stuff it in sometimes as it's also the dev branch. This should become a lot more sane after the 1.0 release.
