### ISSUE TITLE
raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '

### ISSUE THREAD

**Issue by martykiico** [meeb/tubesync#85]
TubeSync version 0.9 with youtube-dl version 2021.03.03 and FFmpeg version 4.3.1-static. 

Following error exists:
`Rescheduling Index media from source "strongandflextv"
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
func(*args, **kwargs)
File "/app/sync/tasks.py", line 161, in index_source_task
videos = source.index_media()
File "/app/sync/models.py", line 465, in index_media
response = indexer(self.index_url)
File "/app/sync/youtube.py", line 50, in get_media_info
raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/c/StrongandFlexTV/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.`

**Comment by meeb** [comment]
That's because your channel name is wrong. It's "StrongandflexDe".

https://www.youtube.com/c/StrongandFlexTV/videos Is indeed a 404, click it.

https://www.youtube.com/c/StrongandflexDe/videos works fine.

Edit your source, update the "key" to be "StrongandflexDe" to fix this.

**Comment by meeb** [comment]
This will also be less confusing soon once work on issues like #33 is done, currently you must be absolutely accurate with the channel names. In your case "StrongandFlexTV" is the user with a vanity name, like https://www.youtube.com/user/StrongandFlexTV but the channel name is StrongandflexDe for some reason. This is indeed not obvious in some cases and should improve in usability over time.

**Comment by martykiico** [comment]
you are right...thanks for support! Now it works.
