### ISSUE TITLE
Request: ability to download single video

### ISSUE THREAD

**Issue by writerinthedark** [meeb/tubesync#89]
First I love TubeSync and thanks for all your hard work.

TubeSync is the best youtube-dl app I've used on my Unraid box but often I just want to pull a single video. Would it be possible to add this feature?

The UI and options in TubeSync outclass everything else I've tried.

**Comment by StillTruckin** [comment]
I setup a special unlisted playlist for just that I found it serves my needs. I add it to the playlist and the Tubesync does the rest. if you need a work around...

**Comment by writerinthedark** [comment]
@StillTruckin Oh that's a smart work around. Thanks!

**Comment by StillTruckin** [comment]
@writerinthedark "unlisted" works in my setup as your providing the link and that the only prerequisite

**Comment by writerinthedark** [comment]
@writerinthedark Totally forgot about unlisted. Thanks!

I just now saw the note about "Can I use TubeSync to download single videos?" on the main github page. I get where the author is coming from but if I'm downloading a single video it's typically because I want that video ASAP. I'd still appreciate an option to download a single video.

**Comment by meeb** [comment]
Thanks for the kind comments! This could potentially be a feature, but there are other projects that provide this exact feature, for example:

https://github.com/Tzahi12345/YoutubeDL-Material

Single video downloading doesn't really fit into what a PVR really should be doing and the "private playlist" route is the current best and advised way to handle this. If there is considerable demand I'll look into it, but at the moment there's already months of work in the queue so I'm not going to add it to the roadmap at the moment.

Thanks for the suggestion though and feel free to comment or create more issues if you have further or additional suggestions.
